query CheckOriginalCategoryMetaData {
  category(by: {id: 20}, taxonomy: "dummy-category") {
    id
    metaKeys
    meta(keys: $__metaKeys) 
  }
}

mutation AddCategoryMeta {
  addCategoryMeta(input: {
    id: 20
    key: "description"
    value: "Description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}

mutation UpdateCategoryMeta {
  updateCategoryMeta: updateCategoryMeta(input: {
    id: 20
    key: "description"
    value: "Updated description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}

mutation DeleteCategoryMeta {
  deleteCategoryMeta: deleteCategoryMeta(input: {
    id: 20
    key: "description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}

mutation SetCategoryMeta {
  setCategoryMeta(input: {
    id: 20
    entries: {
      description: [
        "some value",
      ],
    }
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}

mutation RevertSetCategoryMeta {
  revertSetCategoryMeta: setCategoryMeta(input: {
    id: 20
    entries: {
      description: null,
    }
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}

query ExecuteAll @depends(on: [
  "CheckOriginalCategoryMetaData",
  "AddCategoryMeta",
  "UpdateCategoryMeta",
  "DeleteCategoryMeta",
  "SetCategoryMeta",
  "RevertSetCategoryMeta",
]) {
}
