mutation {
  category(by: {id: 20}, taxonomy: "dummy-category") {
    id
    metaKeys
    meta(keys: $__metaKeys) 
  }
  
  addCategoryMeta(input: {
    id: 20
    key: "description"
    value: "Description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
  
  updateCategoryMeta(input: {
    id: 20
    key: "description"
    value: "Updated description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
  
  deleteCategoryMeta(input: {
    id: 20
    key: "description"
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
  
  setCategoryMeta(input: {
    id: 20
    entries: {
      description: [
        "some value",
      ],
    }
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
  
  revertSetCategoryMeta: setCategoryMeta(input: {
    id: 20
    entries: {
      description: null,
    }
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    category {
      __typename
      id
      metaKeys
      meta(keys: $__metaKeys) 
    }
  }
}