<?php

// Loader Pages
//--------------------------------------------------------
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_POSTS_FIELDS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_USERS_FIELDS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_TAGS_FIELDS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_COMMENTS_FIELDS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_POSTS_LAYOUTS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_USERS_LAYOUTS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_TAGS_LAYOUTS', false);
// define('POP_CMSMODEL_DEPRECATEDPAGE_LOADERS_COMMENTS_LAYOUTS', false);
