<?php

// Categories
//--------------------------------------------------------
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09', false);

// Pages from the Main Navigation
//--------------------------------------------------------
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09', false);

// List Content Pages
//--------------------------------------------------------
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS00', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS01', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS02', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS03', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS04', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS05', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS06', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS07', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS08', false);
define ('POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS09', false);
