<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

class PoPTheme_Wassup_CategoryProcessors_ConfigUtils {

	public static function get_cats() {

		return array_filter(
			array(
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09,
			)
		);	
	}

	public static function get_cat_pages() {

		$ret = array();
		$cats = self::get_cats();
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_mypages() {

		return array_filter(
			array(
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS00,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS01,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS02,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS03,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS04,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS05,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS06,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS07,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS08,
				POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS09,
			)
		);	
	}

	public static function get_cat_authorblockgroups() {

		$ret = array();
		$cats = self::get_cats();
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_cat_tagblockgroups() {

		$ret = array();
		$cats = self::get_cats();
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_page_cats() {

		return array_flip(self::get_cat_pages());	
	}

	public static function get_pages() {

		return array_values(self::get_cat_pages());	
	}

	public static function get_page_authorblockgroups() {

		$cat_pages = self::get_cat_pages();
		$cat_authorblockgroups = self::get_cat_authorblockgroups();
		$page_authorblockgroups = array();
		foreach ($cat_pages as $cat => $page) {
			$page_authorblockgroups[$page] = $cat_authorblockgroups[$cat];
		}

		return $page_authorblockgroups;
	}
}
