<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('POP_CATEGORYPROCESSORS_CONFIGUTILS_POSTS', 'posts');
define ('POP_CATEGORYPROCESSORS_CONFIGUTILS_WEBPOSTS', 'webposts');

class PoPTheme_Wassup_CategoryProcessors_ConfigUtils {

	protected static function get_all_types() {

		return array(
			POP_CATEGORYPROCESSORS_CONFIGUTILS_POSTS, 
			POP_CATEGORYPROCESSORS_CONFIGUTILS_WEBPOSTS,
		);	
	}

	public static function get_cats($type = array()) {

		$type = $type ? $type : self::get_all_types();
		return array_merge(
			in_array(POP_CATEGORYPROCESSORS_CONFIGUTILS_POSTS, $type) ? 
				array_filter(array(
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09,
				)) : array()
			,
			in_array(POP_CATEGORYPROCESSORS_CONFIGUTILS_WEBPOSTS, $type) ?
				array_filter(array(
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS00,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS01,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS02,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS03,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS04,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS05,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS06,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS07,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS08,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS09,
				)) : array()
		);	
	}

	public static function get_cat_pages($type = array()) {

		$ret = array();
		$cats = self::get_cats($type);
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYWEBPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_mypages($type = array()) {

		$type = $type ? $type : self::get_all_types();
		return array_merge(
			in_array(POP_CATEGORYPROCESSORS_CONFIGUTILS_POSTS, $type) ? 
				array_filter(array(
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS00,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS01,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS02,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS03,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS04,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS05,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS06,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS07,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS08,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYPOSTS09,
				)) : array(),
			in_array(POP_CATEGORYPROCESSORS_CONFIGUTILS_WEBPOSTS, $type) ? 
				array_filter(array(
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS00,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS01,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS02,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS03,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS04,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS05,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS06,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS07,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS08,
					POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_MYCATEGORYWEBPOSTS09,
				)) : array()
		);	
	}

	public static function get_cat_authorblockgroups($type = array()) {

		$ret = array();
		$cats = self::get_cats($type);
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_cat_tagblockgroups($type = array()) {

		$ret = array();
		$cats = self::get_cats($type);
		$all = array(
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS00 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS00,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS01 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS01,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS02 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS02,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS03 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS03,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS04 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS04,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS05 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS05,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS06 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS06,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS07 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS07,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS08 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS08,
			POPTHEME_WASSUP_CATEGORYPROCESSORS_CAT_CATEGORYWEBPOSTS09 => GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYWEBPOSTS09,
		);
		foreach ($cats as $cat)	 {
			$ret[$cat] = $all[$cat];
		}
		return $ret;
	}

	public static function get_page_cats($type = array()) {

		return array_flip(self::get_cat_pages($type));	
	}

	public static function get_pages($type = array()) {

		return array_values(self::get_cat_pages($type));	
	}

	public static function get_page_authorblockgroups($type = array()) {

		$cat_pages = self::get_cat_pages($type);
		$cat_authorblockgroups = self::get_cat_authorblockgroups($type);
		$page_authorblockgroups = array();
		foreach ($cat_pages as $cat => $page) {
			$page_authorblockgroups[$page] = $cat_authorblockgroups[$cat];
		}

		return $page_authorblockgroups;
	}
}
