<?php

// Categories
//--------------------------------------------------------
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_MESSAGES_HOME', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_STORIES', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_STORYLINKS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_THOUGHTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_PROJECTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_PROJECTLINKS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_DISCUSSIONS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_DISCUSSIONLINKS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_BLOG', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_ANNOUNCEMENTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_ANNOUNCEMENTLINKS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_FEATURED', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_UNCATEGORIZED', false);

// Pages from the Main Navigation
//--------------------------------------------------------
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED', false);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_RESOURCES', false);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_THOUGHTS', false);

// About us Pages
//--------------------------------------------------------
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_HOWTOUSEWEBSITE', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_CONTENTGUIDELINES', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURMISSION', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_WHOWEARE', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSTORY', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_VOLUNTEERWITHUS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_SPONSORUS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_INTHEMEDIA', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSPONSORS', false);

// Add / Edit / List Content Pages
//--------------------------------------------------------
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECT', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECT', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECTLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECTLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORY', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORY', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORYLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORYLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSION', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSION', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSIONLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSIONLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDFEATURED', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITFEATURED', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENT', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENT', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENTLINK', false);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENTLINK', false);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYRESOURCES', false);

