<?php

declare(strict_types=1);

namespace GatoGraphQLStandalone\GatoGraphQL\Overrides\Upstream\ModuleResolvers;

use GatoGraphQL\GatoGraphQL\ModuleResolvers\DeprecatedClientFunctionalityModuleResolver as UpstreamDeprecatedClientFunctionalityModuleResolver;

class DeprecatedClientFunctionalityModuleResolver extends UpstreamDeprecatedClientFunctionalityModuleResolver
{
    use OverrideToDisableModuleResolverTrait;
}
