query {
  posts(pagination: { limit: 10 }) {
    excerpt
    title
    author {
      name
      posts(pagination: { limit: 10 }) {
        title
        tags(pagination: { limit: 10 }) {
          slug
          posts(pagination: { limit: 10 }) {
            title
            comments(pagination: { limit: 10 }) {
              content
              date
              author {
                name
                posts(pagination: { limit: 10 }) {
                  title
                  comments(pagination: { limit: 10 }) {
                    content
                    date
                    author {
                      name
                      username
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
