<?php

declare(strict_types=1);

namespace PHPUnitForGatoGraphQL\GatoGraphQL\Unit\Faker;

use GraphQLByPoP\GraphQLServer\Unit\DisabledFixtureQueryExecutionGraphQLServerTestCaseTrait;

class DisabledExposeCoreFunctionalityWPFakerFixtureQueryExecutionGraphQLServerTest extends AbstractExposeCoreFunctionalityWPFakerFixtureQueryExecutionGraphQLServerTestCase
{
    use DisabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
