########################################################################
# 
# Variables:
#   - mailchimpDataCenterCode: Code for the data center of your account on Mailchimp (See: https://mailchimp.com/developer/marketing/docs/fundamentals/#api-structure)
#   - mailchimpAudienceID: Audience ID for the list on Mailchimp to which to subscribe the email
#
# *********************************************************************
#
# === Description ===
#
# This GraphQL query captures the email from the visitors who ticked
# the "Subscribe to mailing list" checkbox from InstaWP (when creating
# a new sandbox site), and subscribes this email to a Mailchimp list.
#
# *********************************************************************
# 
# Required PHP code:
#   - Define in `wp-config.php`:
#     define( 'MAILCHIMP_API_CREDENTIALS_USERNAME', '{ username }' );
#     define( 'MAILCHIMP_API_CREDENTIALS_PASSWORD', '{ password }' );
# 
# *********************************************************************
#
# More info:
#   - https://gatographql.com/blog/instawp-gatographql/
#
########################################################################

query HasSubscribedToNewsletter {
  hasSubscriberOptin: _httpRequestHasParam(name: "marketing_optin")
  subscriberOptin: _httpRequestStringParam(name: "marketing_optin")
  isNotSubscriberOptinNAValue: _notEquals(value1: $__subscriberOption, value2: "NA")
  subscribedToNewsletter: _and(values: [$__hasSubscriberOption, $__isNotSubscriberOptionNAValue])
    @export(as: "subscribedToNewsletter")
}

query RegisterNewsletterSubscriberFromInstaWPToMailchimp(
  $mailchimpDataCenterCode: String!
  $mailchimpAudienceID: String!
)
   @depends(on: "HasSubscribedToNewsletter")
   @include(if: $subscribedToNewsletter)
{
  subscriberEmail: _httpRequestStringParam(name: "email")
  
  mailchimpUsername: _env(name: "MAILCHIMP_API_CREDENTIALS_USERNAME")
    @remove
  mailchimpPassword: _env(name: "MAILCHIMP_API_CREDENTIALS_PASSWORD")
    @remove
  
  mailchimpAPIEndpoint: _sprintf(
    string: "https://%s.api.mailchimp.com/3.0/lists/%s/members",
    values: [$mailchimpDataCenterCode, $mailchimpAudienceID]
  )
  
  mailchimpListMembersJSONObject: _sendJSONObjectItemHTTPRequest(input: {
    url: $__mailchimpAPIEndpoint,
    method: POST,
    options: {
      auth: {
        username: $__mailchimpUsername,
        password: $__mailchimpPassword
      },
      json: {
        email_address: $__subscriberEmail,
        status: "subscribed"
      }
    }
  })
}