<?php

declare(strict_types=1);

namespace GraphQLAPI\GraphQLAPI\Registries;

class PersistedQueryEndpointSchemaConfigurationExecuterRegistry extends AbstractSchemaConfigurationExecuterRegistry implements PersistedQueryEndpointSchemaConfigurationExecuterRegistryInterface
{
}
