<?php

declare(strict_types=1);

namespace GraphQLAPI\GraphQLAPI;

class Environment
{
    public const MODULE_URL_BASE = 'MODULE_URL_BASE';
    public const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public const EMPTY_LABEL = 'EMPTY_LABEL';
    public const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public const ENDPOINT_SLUG_BASE = 'ENDPOINT_SLUG_BASE';
    public const PERSISTED_QUERY_SLUG_BASE = 'PERSISTED_QUERY_SLUG_BASE';
    public const EDITING_ACCESS_SCHEME = 'EDITING_ACCESS_SCHEME';
}
