{
  posts(pagination: { limit: 5 }) {
    id
    title
    blocks {
      ...BlockData
    }
  }
}

fragment BlockData on Block {
    name
    attributes
    innerBlocks {
        name
        attributes
        innerBlocks {
        name
        attributes
        innerBlocks {
            name
            attributes
            innerBlocks {
            name
            attributes
            innerBlocks {
                name
                attributes
                innerBlocks {
                name
                attributes
                innerBlocks {
                    name
                    attributes
                }
                }
            }
            }
        }
        }
    }
}