{
  categories(taxonomy: "dummy-category") {
    __typename
    ...GenericCategoryData
    ...CategoryData
  }
  
  customPosts(
    filter: {
      customPostTypes: ["post","dummy-cpt"]
    }
    pagination: {
      limit: 30
    }
  ) {
    __typename
    ...on CustomPost {
      id
      title
      customPostType
    }
    ...on GenericCustomPost {
      categories(taxonomy: "dummy-category") {
        __typename
        id
        name
        taxonomy
      }
    }
    ...on Post {
      categories {
        __typename
        id
        name
        slug
        slugPath
      }
    }
  }

  customPostsByCategoryIDs: customPosts(
    filter: {
      categoryIDs: [28, 33]
      categoryTaxonomy: "dummy-category"
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }

  postCategories: categories(taxonomy: category) {
    ...CategoryData
  }
  postCategoryByID: category(taxonomy: category, by: { id: 1 }) {
    ...CategoryData
  }
  postCategoryBySlug: category(taxonomy: category, by: { slug: "resource" }) {
    ...CategoryData
  }
  postCategoryCount: categoryCount(taxonomy: category)
  postCategoryNames: categoryNames(taxonomy: category)

  dummyCategories: categories(taxonomy: "dummy-category") {
    ...CategoryData
  }
  dummyCategoryByID: category(taxonomy: "dummy-category", by: { id: 27 }) {
    ...CategoryData
  }
  dummyCategoryBySlug: category(taxonomy: "dummy-category", by: { slug: "nostradamus" }) {
    ...CategoryData
  }
  dummyCategoryCount: categoryCount(taxonomy: "dummy-category")
  dummyCategoryNames: categoryNames(taxonomy: "dummy-category")
}

fragment CategoryData on Category {
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  slugPath
  url
  urlPath
}

fragment GenericCategoryData on GenericCategory {
  taxonomy   
  customPostCount
  customPosts(sort: {by: ID, order: ASC}) {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on CustomPost {
  id
  title
  categories(taxonomy: "dummy-category") {
    __typename
    ...on Category {
      id
      name
    }
  }
}