{
  postsByIDs: posts(
    filter: {
      tags: {
        includeBy: {
          ids: [15, 14]
        }
      }
      categories: {
        includeBy: {
          ids: [1, 4]
        }
      }
    }
  ) {
    id
    title
    tags {
      id
    }
    categories {
      id
    }
  }

  postsBySlugAndIDs: posts(
    filter: {
      tags: {
        includeBy: {
          slugs: ["release", "plugin"]
        }
      }
      categories: {
        includeBy: {
          ids: [1, 4]
        },
        excludeBy: {
          slugs: "advanced"
        }
      }
    }
  ) {
    id
    title
    tags {
      slug
    }
    categories {
      id
    }
  }
}