<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLClientsForWP;

class Environment
{
    public const GRAPHQL_CLIENTS_COMPONENT_URL = 'GRAPHQL_CLIENTS_COMPONENT_URL';
    public const DISABLE_GRAPHIQL_CLIENT_ENDPOINT = 'DISABLE_GRAPHIQL_CLIENT_ENDPOINT';
    public const GRAPHIQL_CLIENT_ENDPOINT = 'GRAPHIQL_CLIENT_ENDPOINT';
    public const USE_GRAPHIQL_EXPLORER = 'USE_GRAPHIQL_EXPLORER';
    public const DISABLE_VOYAGER_CLIENT_ENDPOINT = 'DISABLE_VOYAGER_CLIENT_ENDPOINT';
    public const VOYAGER_CLIENT_ENDPOINT = 'VOYAGER_CLIENT_ENDPOINT';
}
