<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLClientsForWP;

class Environment
{
    public final const GRAPHQL_CLIENTS_COMPONENT_URL = 'GRAPHQL_CLIENTS_COMPONENT_URL';
    public final const DISABLE_GRAPHIQL_CLIENT_ENDPOINT = 'DISABLE_GRAPHIQL_CLIENT_ENDPOINT';
    public final const GRAPHIQL_CLIENT_ENDPOINT = 'GRAPHIQL_CLIENT_ENDPOINT';
    public final const USE_GRAPHIQL_EXPLORER = 'USE_GRAPHIQL_EXPLORER';
    public final const DISABLE_VOYAGER_CLIENT_ENDPOINT = 'DISABLE_VOYAGER_CLIENT_ENDPOINT';
    public final const VOYAGER_CLIENT_ENDPOINT = 'VOYAGER_CLIENT_ENDPOINT';
}
