query ExecuteInternalQuery(
    $postTitle: String!,
    $postStatus: String!
) {
    newPostTitle: _echo(value: $postTitle)
    newPostStatus: _echo(value: $postStatus)
    
    # Also add a non-existing field, to check that its
    # feedback is printed in the nested output
    nonExistingField
}