{
  categories(taxonomy: "dummy-category") {
    __typename
    ...GenericCategoryData
    ...CategoryData
  }
  
  customPosts(
    filter: {
      customPostTypes: ["post","dummy-cpt"]
    }
    pagination: {
      limit: 30
    }
  ) {
    __typename
    ...on IsCustomPost {
      id
      title
      customPostType
    }
    ...on GenericCustomPost {
      categories(taxonomy: "dummy-category") {
        __typename
        id
        name
        taxonomy
      }
    }
    ...on Post {
      categories {
        __typename
        id
        name
      }
    }
  }

  customPostsByCategoryIDs: customPosts(
    filter: {
      categoryIDs: [26, 28]
      categoryTaxonomy: "dummy-category"
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }
}

fragment CategoryData on IsCategory {
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  url
  urlAbsolutePath
}

fragment GenericCategoryData on GenericCategory {
  taxonomy   
  customPostCount
  customPosts {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on IsCustomPost {
  id
  title
  categories(taxonomy: "dummy-category") {
    __typename
    ...on IsCategory {
      id
      name
    }
  }
}