{
  post(by:{ id: 21 }) {
    comments {
      ...CommentData
      responses {
        ...CommentData
      }
    }
  }
}

fragment CommentData on Comment {
  approved
  author {
    id
    name
  }
  authorEmail
  authorIP
  authorName
  authorURL
  content
  customPost {
    id
    title
  }
  customPostID
  date
  dateStr
  id
  karma
  metaValue(key: "description")
  parent {
    id
  }
  rawContent
  responseCount
  status
  type
}