{
  customPostsByIDs: customPosts(
    filter: {
      tagIDs: [20, 27]
      tagTaxonomy: "dummy-tag"
      categoryIDs: [26, 28]
      categoryTaxonomy: "dummy-category"
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(taxonomy: "dummy-tag") {
        id
      }
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }

  customPostsBySlugAndIDs: customPosts(
    filter: {
      tagSlugs: "classical"
      tagTaxonomy: "dummy-tag"
      categoryIDs: [26, 28]
      categoryTaxonomy: "dummy-category"
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(taxonomy: "dummy-tag") {
        slug
      }
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }
}