{
  tags(taxonomy: "dummy-tag") {
    __typename
    ...GenericTagData
    ...TagData
  }
}

fragment TagData on IsTag {
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  url
  urlAbsolutePath
}

fragment GenericTagData on GenericTag {
  taxonomy   
  customPostCount
  customPosts {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on IsCustomPost {
  id
  title
  tags(taxonomy: "dummy-tag") {
    __typename
    ...on IsTag {
      id
      name
    }
  }
}