############################################################
# After having disabled module "Users",
# check if the User type is available or not
############################################################
{
  __schema {
    userType: type(name: "User") {
      name
    }
  }
}