################################################
# dateStr(format:) is not mandatory, but it cannot be null,
# hence in this query, as the variable value is not provided,
# it will inject `null`, and the validation must kick in
################################################
query ($missingFormat: String) {
  posts {
    id
    dateStr(format: $missingFormat)
  }
}