<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts00'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts01'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts02'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts03'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts04'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts05'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts06'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts07'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts08'));
define ('GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('blockgroup-home-widgetarea-categoryposts09'));

class CPP_Template_Processor_CustomBlockGroups extends GD_Template_Processor_ListBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09,
		);
	}

	function get_blockgroup_blocks($template_id) {

		$ret = parent::get_blockgroup_blocks($template_id);

		switch ($template_id) {
				
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09:

				$blocks = array(
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS00_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS01_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS02_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS03_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS04_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS05_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS06_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS07_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS08_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS09_CAROUSEL,
				);

				$ret[] = GD_TEMPLATE_BLOCK_EVENTS_CAROUSEL;
				$ret[] = $blocks[$template_id];
				break;
		}

		return $ret;
	}

	protected function get_blocksections_classes($template_id) {

		$ret = parent::get_blocksections_classes($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09:

				// Allow the ThemeStyle Expansive to make it into 2 columns
				if (apply_filters(POP_HOOK_BLOCKGROUP_TOPWIDGETS_INCOLUMNS, false)) {
					$ret['blocksection-extensions'] = 'row';
				}
				break;
		}

		return $ret;
	}

	function init_atts_blockgroup_block($blockgroup, $blockgroup_block, &$blockgroup_block_atts, $blockgroup_atts) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09:

				$blocks = array(
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS00_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS01_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS02_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS03_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS04_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS05_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS06_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS07_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS08_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS09_CAROUSEL,
				);
				if ($blockgroup_block == $blocks[$blockgroup]) {

					// Make it lazy-load
					// $this->add_att($blockgroup_block, $blockgroup_block_atts, 'content-loaded', false);
					$this->add_att($blockgroup_block, $blockgroup_block_atts, 'hidden-if-empty', true);
				}
				elseif ($blockgroup_block == GD_TEMPLATE_BLOCK_EVENTS_CAROUSEL) {

					$this->add_att($blockgroup_block, $blockgroup_block_atts, 'hidden-if-empty', true);
				}
				break;
		}

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09:

				$blocks = array(
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS00 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS00_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS01 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS01_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS02 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS02_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS03 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS03_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS04 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS04_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS05 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS05_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS06 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS06_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS07 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS07_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS08 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS08_CAROUSEL,
					GD_TEMPLATE_BLOCKGROUP_HOME_WIDGETAREA_CATEGORYPOSTS09 => GD_TEMPLATE_BLOCK_CATEGORYPOSTS09_CAROUSEL,
				);

				// Allow the ThemeStyle Expansive to make it into 2 columns
				if (apply_filters(POP_HOOK_BLOCKGROUP_TOPWIDGETS_INCOLUMNS, false)) {
				
					$classes = array(
						GD_TEMPLATE_BLOCK_EVENTS_CAROUSEL => 'col-sm-8',
						$blocks[$blockgroup] => 'col-sm-4',
					);
					$this->append_att($blockgroup_block, $blockgroup_block_atts, 'class', $classes[$blockgroup_block]);
				}
				break;
		}

		return parent::init_atts_blockgroup_block($blockgroup, $blockgroup_block, $blockgroup_block_atts, $blockgroup_atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CustomBlockGroups();
