<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts00'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts01'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts02'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts03'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts04'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts05'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts06'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts07'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts08'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-tagcategoryposts09'));

class CPP_Template_Processor_TagSectionTabPanelBlockGroups extends GD_Template_Processor_TagSectionTabPanelBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09,
		);
	}

	function get_blockgroup_blocks($template_id) {

		$ret = parent::get_blockgroup_blocks($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_LIST,
						// GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLLMAP,
					)
				);
				break;
		}

		return $ret;
	}

	function get_panel_headers($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09:

				$ret = array(
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_LIST,
					),
				);
				break;
		}

		if ($ret) {
			return apply_filters('CPP_Template_Processor_TagSectionTabPanelBlockGroups:panel_headers', $ret, $template_id);
		}

		return parent::get_panel_headers($template_id, $atts);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09:

				return GD_TEMPLATE_FILTER_TAGWILDCARDPOSTS;
		}
		
		return parent::get_filter_template($template_id);
	}

	function get_panel_header_fontawesome($blockgroup, $blockunit) {

		$details = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_LIST,
		);

		if (in_array($blockunit, $details)) {

			return 'fa-th-list';
		}
		elseif (in_array($blockunit, $simpleviews)) {
			
			return 'fa-angle-right';
		}
		elseif (in_array($blockunit, $fullviews)) {
			
			return 'fa-angle-double-right';
		}
		elseif (in_array($blockunit, $thumbnails)) {
			
			return 'fa-th';
		}
		elseif (in_array($blockunit, $lists)) {
			
			return 'fa-list';
		}

		return parent::get_panel_header_fontawesome($blockgroup, $blockunit);
	}
	function get_panel_header_title($blockgroup, $blockunit, $atts) {

		$details = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_TAGCATEGORYPOSTS09_SCROLL_LIST,
		);

		if (in_array($blockunit, $details)) {

			return __('Details', 'poptheme-wassup-organikprocessors');
		}
		elseif (in_array($blockunit, $simpleviews)) {
			
			return __('Feed', 'poptheme-wassup');
		}
		elseif (in_array($blockunit, $fullviews)) {
			
			return __('Extended', 'poptheme-wassup');
		}
		elseif (in_array($blockunit, $thumbnails)) {
			
			return __('Thumbnail', 'poptheme-wassup-organikprocessors');
		}
		elseif (in_array($blockunit, $lists)) {
			
			return __('List', 'poptheme-wassup-organikprocessors');
		}

		return parent::get_panel_header_title($blockgroup, $blockunit, $atts);
	}
	function get_panel_header_tooltip($blockgroup, $blockunit) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09:
				
				return $this->get_panel_header_title($blockgroup, $blockunit, $atts);
		}

		return parent::get_panel_header_tooltip($blockgroup, $blockunit);
	}

	function get_default_active_blockunit($template_id) {

		$pages_id = array_flip(PoPTheme_Wassup_CategoryProcessors_ConfigUtils::get_page_tagblockgroups());
		if ($page_id = $pages_id[$template_id]) {

			global $gd_template_settingsmanager;
			return $gd_template_settingsmanager->get_page_block($page_id, GD_SETTINGS_HIERARCHY_TAG);
		}
	
		return parent::get_default_active_blockunit($template_id);
	}

	function init_atts($template_id, &$atts) {

		$class = '';
		$feeds = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_TAGCATEGORYPOSTS09,
		);
		if (in_array($template_id, $feeds)) {
			$class = 'feed';
		}
		if ($class) {
			$this->append_att($template_id, $atts, 'class', $class);
		}
		
		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_TagSectionTabPanelBlockGroups();
