<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts00'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts01'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts02'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts03'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts04'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts05'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts06'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts07'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts08'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategoryposts09'));

define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts00'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts01'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts02'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts03'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts04'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts05'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts06'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts07'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts08'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-authorcategorywebposts09'));

class CPP_Template_Processor_AuthorSectionTabPanelBlockGroups extends GD_Template_Processor_AuthorSectionTabPanelBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09,
		);
	}

	protected function get_block_inner_templates($template_id) {

		$ret = parent::get_block_inner_templates($template_id);

		$vars = GD_TemplateManager_Utils::get_vars();
		$author = $vars['global-state']['author']/*global $author*/;
		if (gd_ure_is_community($author)) {

			switch ($template_id) {

				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09:

				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09:

					$ret[] = GD_URE_TEMPLATE_CONTROLGROUP_CONTENTSOURCE;
					break;
			}
		}
	
		return $ret;
	}

	function get_blockgroup_blocks($template_id) {

		$ret = parent::get_blockgroup_blocks($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLLMAP,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_FULLVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLLMAP,
					)
				);
				break;				
		}

		return $ret;
	}

	function get_panel_headers($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_LIST,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09:

				$ret = array(
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_SIMPLEVIEW => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_SIMPLEVIEW,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_FULLVIEW,
					),
					GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_THUMBNAIL,
						GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_LIST,
					),
				);
				break;				
		}

		if ($ret) {
			return apply_filters('CPP_Template_Processor_AuthorSectionTabPanelBlockGroups:panel_headers', $ret, $template_id);
		}

		return parent::get_panel_headers($template_id, $atts);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09:

				return GD_TEMPLATE_FILTER_AUTHORWILDCARDPOSTS;
		}
		
		return parent::get_filter_template($template_id);
	}

	function get_panel_header_fontawesome($blockgroup, $blockunit) {

		$details = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_LIST,
		);

		if (in_array($blockunit, $details)) {

			return 'fa-th-list';
		}
		elseif (in_array($blockunit, $simpleviews)) {
			
			return 'fa-angle-right';
		}
		elseif (in_array($blockunit, $fullviews)) {
			
			return 'fa-angle-double-right';
		}
		elseif (in_array($blockunit, $thumbnails)) {
			
			return 'fa-th';
		}
		elseif (in_array($blockunit, $lists)) {
			
			return 'fa-list';
		}

		return parent::get_panel_header_fontawesome($blockgroup, $blockunit);
	}
	function get_panel_header_title($blockgroup, $blockunit, $atts) {

		$details = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYPOSTS09_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS00_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS01_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS02_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS03_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS04_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS05_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS06_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS07_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS08_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_AUTHORCATEGORYWEBPOSTS09_SCROLL_LIST,
		);

		if (in_array($blockunit, $details)) {

			return __('Details', 'poptheme-wassup-organikprocessors');
		}
		elseif (in_array($blockunit, $simpleviews)) {
			
			return __('Feed', 'poptheme-wassup');
		}
		elseif (in_array($blockunit, $fullviews)) {
			
			return __('Extended', 'poptheme-wassup');
		}
		elseif (in_array($blockunit, $thumbnails)) {
			
			return __('Thumbnail', 'poptheme-wassup-organikprocessors');
		}
		elseif (in_array($blockunit, $lists)) {
			
			return __('List', 'poptheme-wassup-organikprocessors');
		}

		return parent::get_panel_header_title($blockgroup, $blockunit, $atts);
	}
	function get_panel_header_tooltip($blockgroup, $blockunit) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09:

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09:
				
				return $this->get_panel_header_title($blockgroup, $blockunit, $atts);
		}

		return parent::get_panel_header_tooltip($blockgroup, $blockunit);
	}

	function get_default_active_blockunit($template_id) {

		$pages_id = array_flip(PoPTheme_Wassup_CategoryProcessors_ConfigUtils::get_page_authorblockgroups());
		if ($page_id = $pages_id[$template_id]) {

			global $gd_template_settingsmanager;
			return $gd_template_settingsmanager->get_page_block($page_id, GD_SETTINGS_HIERARCHY_AUTHOR);
		}
	
		return parent::get_default_active_blockunit($template_id);
	}

	function init_atts($template_id, &$atts) {

		$class = '';
		$feeds = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS00,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS01,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS02,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS03,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS04,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS05,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS06,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS07,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS08,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORCATEGORYWEBPOSTS09,
		);
		if (in_array($template_id, $feeds)) {
			$class = 'feed';
		}
		if ($class) {
			$this->append_att($template_id, $atts, 'class', $class);
		}
		
		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_AuthorSectionTabPanelBlockGroups();
