<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_SECTION_ANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-announcements-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_BLOG_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-blog-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_DISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-discussions-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-featured-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_LOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-locationposts-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_STORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-stories-sidebar'));

define ('GD_TEMPLATE_BLOCKGROUP_SECTION_MYANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-myannouncements-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_MYDISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-mydiscussions-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_MYLOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-mylocationposts-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SECTION_MYSTORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-section-mystories-sidebar'));

// define ('GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-authorannouncements-sidebar'));
// define ('GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-authordiscussions-sidebar'));
// define ('GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-authorfeatured-sidebar'));
// define ('GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-authorlocationposts-sidebar'));
// define ('GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-authorstories-sidebar'));

define ('GD_TEMPLATE_BLOCKGROUP_TAG_ANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-tag-announcements-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_TAG_DISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-tag-discussions-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_TAG_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-tag-featured-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_TAG_LOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-tag-locationposts-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_TAG_STORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-tag-stories-sidebar'));

define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-blog-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-announcement-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-announcement-relatedcontentsidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-announcement-highlightssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-announcement-postauthorssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-announcement-recommendedbysidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-discussion-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-discussion-relatedcontentsidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-discussion-highlightssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-discussion-postauthorssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-discussion-recommendedbysidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-featured-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-featured-relatedcontentsidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-featured-highlightssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-featured-postauthorssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-featured-recommendedbysidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-locationpost-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-locationpost-relatedcontentsidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-locationpost-highlightssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-locationpost-postauthorssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-locationpost-recommendedbysidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-story-sidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-story-relatedcontentsidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-story-highlightssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-story-postauthorssidebar'));
define ('GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR', PoP_TemplateIDUtils::get_template_definition('blockgroup-single-story-recommendedbysidebar'));

class PoPSP_Template_Processor_SidebarBlockGroups extends GD_Template_Processor_SidebarBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_SECTION_ANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_BLOG_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_DISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_LOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_STORIES_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_MYANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_MYDISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_MYLOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SECTION_MYSTORIES_SIDEBAR,
			// GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR,
			// GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR,
			// GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR,
			// GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR,
			// GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_TAG_ANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_TAG_DISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_TAG_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_TAG_LOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_TAG_STORIES_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR,
			GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR,
		);
	}

	function get_inner_blocks($template_id) {

		$ret = parent::get_inner_blocks($template_id);

		switch ($template_id) {

			// case GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR:

			// 	$author = $vars['global-state']['author']/*global $author*/;
			// 	$filters = array(
			// 		GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR,
			// 		GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR,
			// 		GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR => GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR,
			// 		GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR,
			// 		GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR,
			// 	);
			// 	$ret[] = $filters[$template_id];

			// 	if (gd_ure_is_organization($author)) {
					
			// 		$ret[] = GD_TEMPLATE_BLOCK_AUTHOR_SIDEBAR_ORGANIZATION;
			// 	}
			// 	elseif (gd_ure_is_individual($author)) {

			// 		$ret[] = GD_TEMPLATE_BLOCK_AUTHOR_SIDEBAR_INDIVIDUAL;
			// 	}
			// 	break;

			// Add also the filter block for the Single Related Content, etc
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR:

				$filters = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
				);
				$ret[] = $filters[$template_id];
				$ret[] = GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR;
				break;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR:

				$filters = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
				);
				$ret[] = $filters[$template_id];
				$ret[] = GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR;
				break;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR:

				$filters = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
				);
				$ret[] = $filters[$template_id];
				$ret[] = GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR;
				break;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR:

				$filters = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
				);
				$ret[] = $filters[$template_id];
				$ret[] = GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR;
				break;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR:

				$filters = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
				);
				$ret[] = $filters[$template_id];
				$ret[] = GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR;
				break;
			
			default:
				
				$blocks = array(
					GD_TEMPLATE_BLOCKGROUP_SECTION_ANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_ANNOUNCEMENTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_BLOG_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_BLOG_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_DISCUSSIONS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_DISCUSSIONS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_FEATURED_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_FEATURED_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_LOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_LOCATIONPOSTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_STORIES_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_STORIES_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_MYANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_MYANNOUNCEMENTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_MYDISCUSSIONS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_MYDISCUSSIONS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_MYLOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_MYLOCATIONPOSTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SECTION_MYSTORIES_SIDEBAR => GD_TEMPLATE_BLOCK_SECTION_MYSTORIES_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_TAG_ANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_TAG_DISCUSSIONS_SIDEBAR => GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_TAG_FEATURED_SIDEBAR => GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_TAG_LOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_TAG_STORIES_SIDEBAR => GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR,
				);
				if ($block = $blocks[$template_id]) {

					$ret[] = $block;
				}
				break;
		}

		return $ret;
	}

	function get_screen($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_SECTION_ANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_DISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_LOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_STORIES_SIDEBAR:

				return POP_SCREEN_SECTION;

			case GD_TEMPLATE_BLOCKGROUP_TAG_ANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_DISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_LOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_STORIES_SIDEBAR:

				return POP_SCREEN_TAGSECTION;

			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYDISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYLOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYSTORIES_SIDEBAR:

				return POP_SCREEN_MYCONTENT;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR:
				
				return POP_SCREEN_SINGLE;
			
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR:

				return POP_SCREEN_SINGLESECTION;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR:
				
				return POP_SCREEN_SINGLEHIGHLIGHTS;

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR:

				return POP_SCREEN_SINGLEUSERS;

			// case GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR:
		
			// 	return POP_SCREEN_AUTHORSECTION;
		}
		
		return parent::get_screen($template_id);
	}

	function get_screengroup($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_SECTION_ANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_DISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_LOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_STORIES_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_ANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_DISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_LOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_TAG_STORIES_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_RECOMMENDEDBYSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RELATEDCONTENTSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_HIGHLIGHTSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_POSTAUTHORSSIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_RECOMMENDEDBYSIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORANNOUNCEMENTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORDISCUSSIONS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORFEATURED_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORLOCATIONPOSTS_SIDEBAR:
			// case GD_TEMPLATE_BLOCKGROUP_AUTHORSTORIES_SIDEBAR:

				return POP_SCREENGROUP_CONTENTREAD;

			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYDISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYLOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SECTION_MYSTORIES_SIDEBAR:
			
				return POP_SCREENGROUP_CONTENTWRITE;
		}
		
		return parent::get_screengroup($template_id);
	}

	function init_atts_blockgroup_block($blockgroup, $blockgroup_block, &$blockgroup_block_atts, $blockgroup_atts) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR:
			case GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR:

				$inners = array(
					GD_TEMPLATE_BLOCKGROUP_SINGLE_ANNOUNCEMENT_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_BLOG_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_DISCUSSION_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_FEATURED_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_LOCATIONPOST_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR,
					GD_TEMPLATE_BLOCKGROUP_SINGLE_STORY_SIDEBAR => GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR,
				);
				if ($inners[$blockgroup] == $blockgroup_block) {

					// Comment Leo 10/12/2016: in the past, we did .active, however that doesn't work anymore for when alt+click to open a link, instead must pick the last added .tab-pane with selector "last-child"
					$mainblock_taget = '#'.GD_TEMPLATEID_PAGESECTIONID_MAIN.' .pop-pagesection-page.toplevel:last-child > .blockgroup-singlepost > .blocksection-extensions > .pop-block > .blocksection-inners > .content-single';

					// Make the block be collapsible, open it when the main feed is reached, with waypoints
					$this->append_att($blockgroup_block, $blockgroup_block_atts, 'class', 'collapse');
					$this->merge_att($blockgroup_block, $blockgroup_block_atts, 'params', array(
						'data-collapse-target' => $mainblock_taget
					));
					$this->merge_block_jsmethod_att($blockgroup_block, $blockgroup_block_atts, array('waypointsToggleCollapse'));
				}
				break;
		}

		return parent::init_atts_blockgroup_block($blockgroup, $blockgroup_block, $blockgroup_block_atts, $blockgroup_atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new PoPSP_Template_Processor_SidebarBlockGroups();
