<?php

declare(strict_types=1);

namespace PHPUnitForGraphQLAPI\WebserverRequests;

class Environment
{
    public final const INTEGRATION_TESTS_WEBSERVER_DOMAIN = 'INTEGRATION_TESTS_WEBSERVER_DOMAIN';
    public final const INTEGRATION_TESTS_AUTHENTICATED_USER_USERNAME = 'INTEGRATION_TESTS_AUTHENTICATED_USER_USERNAME';
    public final const INTEGRATION_TESTS_AUTHENTICATED_USER_PASSWORD = 'INTEGRATION_TESTS_AUTHENTICATED_USER_PASSWORD';
}
