{
  postCategories: categories(taxonomy: category) {
    ...CategoryData
  }
  postCategory: category(taxonomy: category, by: { id: 1 }) {
    ...CategoryData
  }
  postCategoryCount: categoryCount(taxonomy: category)
  postCategoryNames: categoryNames(taxonomy: category)

  dummyCategories: categories(taxonomy: "dummy-category") {
    ...CategoryData
  }
  dummyCategory: category(taxonomy: "dummy-category", by: { id: 19 }) {
    ...CategoryData
  }
  dummyCategoryCount: categoryCount(taxonomy: "dummy-category")
  dummyCategoryNames: categoryNames(taxonomy: "dummy-category")
}

fragment CategoryData on IsCategory {
  __typename
  id
  name
}
