########################################################################
#
# This Persisted GraphQL query imports a post from some a WordPress RSS feed.
#
# *********************************************************************
# 
# URL params:
#   - url: WordPress single post RSS URL. It usually is the blog post URL + appending "/feed/rss/?withoutcomments=1"
#       eg: https://newapi.getpop.org/blogroll/a-tale-of-two-cities-teaser/feed/rss/?withoutcomments=1
#
########################################################################

query GetPostFromRSSFeedAndExportData(
  $url: URL!
) {
  _sendHTTPRequest(input: {
    url: $url,
    method: GET
  }) {
    body
    rssJSON: _strDecodeXMLAsJSON(
      xml: $__body
      alwaysArrayTagNames: [
        "category",
      ],
    )

    # Fields to be imported
    authorUsername: _objectProperty(
      object: $__rssJSON,
      by: {
        path: "rss.channel.item.dc:creator"
      }
    )
      @export(as: "authorUsername")

    # categorySlugs: _objectProperty(
    #   object: $__rssJSON,
    #   by: {
    #     path: "rss.channel.item.category"
    #   }
    # )

    content:  _objectProperty(
      object: $__rssJSON,
      by: {
        path: "rss.channel.item.content:encoded"
      }
    )
      @export(as: "content")

    excerpt:  _objectProperty(
      object: $__rssJSON,
      by: {
        path: "rss.channel.item.description"
      }
    )
      @export(as: "excerpt")

    title:  _objectProperty(
      object: $__rssJSON,
      by: {
        path: "rss.channel.item.title"
      }
    )
      @export(as: "title")
  }
}

# If the author's username exists in this site, keep it
# Otherwise, use "admin"
query CheckAuthorExistsOrChange(
  $adminUsername: String! = "admin"
)
  @depends(on: "GetPostFromRSSFeedAndExportData")
  @configureWarningsOnExportingDuplicateVariable(enabled: false)
{
  existingUserByUsername: user(by: { username: $authorUsername })
  {
    id
    username
  }
  existingUserByUsernameOrLocal: user(by: { username: $authorUsername })
    @default(value: $adminUsername)
  {
    id
       @export(as: "authorID")
    username
  }
}

mutation ImportPostFromRSSFeed
  @depends(on: "CheckAuthorExistsOrChange")
{
  createPost(input: {
    status: draft,
    authorBy: {
      id: $authorID
    },
    contentAs: {
      html: $content
    },
    excerpt: $excerpt
    title: $title
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    post {
      id
      slug
      date
      status

      author {
        id
        username
      }
      content
      excerpt
      title
    }
  }
}