{
    dummyReceivingInputObjectWithNestedValidationField(
        input: {
            input: {
                input: {
                    name: "Hola"
                }
            }
        }
    )
}