<?php

declare(strict_types=1);

namespace PHPUnitForGraphQLAPI\GraphQLAPI\Integration;

abstract class AbstractNonAuthenticatedUserValidationQueryExecutionFixtureWebserverRequestTestCase extends AbstractUserValidationQueryExecutionFixtureWebserverRequestTestCase
{
}
