<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-singlerelatedopinionatedvotecontent'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-singlerelatedopinionatedvotecontent-pro'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-singlerelatedopinionatedvotecontent-against'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL', PoP_ServerUtils::get_template_definition('blockgroup-tabpanel-singlerelatedopinionatedvotecontent-neutral'));

class VotingProcessors_Template_Processor_SingleSectionTabPanelBlockGroups extends GD_Template_Processor_DefaultActiveTabPanelBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL,
		);
	}

	function get_blockgroup_blocks($template_id) {

		$ret = parent::get_blockgroup_blocks($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
					)
				);
				break;
		}

		// Allow Events Manager to add the Map format
		$ret = apply_filters('VotingProcessors_Template_Processor_SingleSectionTabPanelBlockGroups:blocks', $ret, $template_id);

		return $ret;
	}

	function get_panel_headers($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:

				$ret = array(
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW => array(),
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_DETAILS => array(
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_DETAILS,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
					// ),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:

				$ret = array(
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW => array(),
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_DETAILS => array(
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_DETAILS,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
					// ),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:

				$ret = array(
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW => array(),
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_DETAILS => array(
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_DETAILS,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
					// ),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				$ret = array(
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW => array(),
					// GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_DETAILS => array(
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_DETAILS,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
					// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
					// ),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
					),
				);
				break;
		}

		if ($ret) {
			return apply_filters('VotingProcessors_Template_Processor_SingleSectionTabPanelBlockGroups:panel_headers', $ret, $template_id);
		}

		return parent::get_panel_headers($template_id, $atts);
	}

	function intercept($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				return true;
		}

		return parent::intercept($template_id);
	}

	protected function get_controlgroup_bottom($template_id) {

		// Do not add for the quickview, since it is a modal and can't open a new modal (eg: Embed) on top
		$vars = GD_TemplateManager_Utils::get_vars();
		if (!$vars['fetching-json-quickview']) {

			switch ($template_id) {

				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

					global $post;
					if (get_post_status($post->ID) == 'publish')  {
						
						return GD_TEMPLATE_CONTROLGROUP_SUBMENUPOSTLIST;
					}
					break;
			}
		}

		return parent::get_controlgroup_bottom($template_id);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
				
				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:
				
				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES_STANCE;
		}
		
		return parent::get_filter_template($template_id);
	}

	function get_title($template_id) {

		global $gd_template_settingsmanager;
		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				return GD_Template_Processor_CustomSectionBlocksUtils::get_single_title();
		}
		
		return parent::get_title($template_id);
	}

	function get_submenu($template_id) {

		// Do not add for the quickview
		$vars = GD_TemplateManager_Utils::get_vars();
		if (!$vars['fetching-json-quickview']) {

			switch ($template_id) {

				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

					if ($submenu = GD_Template_Processor_CustomSectionBlocksUtils::get_single_submenu()) {
						return $submenu;
					}
					break;
			}
		}
		
		return parent::get_submenu($template_id);
	}

	function get_panel_header_fontawesome($blockgroup, $blockunit) {

		// $details = array(
		// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_DETAILS,
		// );
		$fullviews = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW,
		);
		$grids = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
		);
		
		/*if (in_array($blockunit, $details)) {

			return 'fa-th-list';
		}
		else*/if (in_array($blockunit, $fullviews)) {
			
			return 'fa-road';
		}
		elseif (in_array($blockunit, $grids)) {
			
			return 'fa-th';
		}
		elseif (in_array($blockunit, $lists)) {
			
			return 'fa-list';
		}

		return parent::get_panel_header_fontawesome($blockgroup, $blockunit);
	}
	function get_panel_header_title($blockgroup, $blockunit, $atts) {

		// $details = array(
		// 	GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_DETAILS,
		// );
		$fullviews = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW,
		);
		$grids = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
		);

		/*if (in_array($blockunit, $details)) {

			return __('Details', 'poptheme-wassup-votingprocessors');
		}
		else*/if (in_array($blockunit, $fullviews)) {
			
			return __('Full view', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $grids)) {
			
			return __('Grid', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $lists)) {
			
			return __('List', 'poptheme-wassup-votingprocessors');
		}

		return parent::get_panel_header_title($blockgroup, $blockunit, $atts);
	}
	function get_panel_header_tooltip($blockgroup, $blockunit) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:
				
				return $this->get_panel_header_title($blockgroup, $blockunit, $atts);
		}

		return parent::get_panel_header_tooltip($blockgroup, $blockunit);
	}
	
	function is_active_blockunit($blockgroup, $blockunit) {

		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				global $gd_template_settingsmanager;
				if ($page_id = GD_TemplateManager_Utils::get_hierarchy_page_id()) {
					return ($gd_template_settingsmanager->get_page_block($page_id, GD_SETTINGS_HIERARCHY_SINGLE) == $blockunit);
				}
				break;
		}
	
		return parent::is_active_blockunit($blockgroup, $blockunit);
	}

	function get_default_active_blockunit($template_id) {

		$pages_id = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT => POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO => POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST => POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL => POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL,
		);
		if ($page_id = $pages_id[$template_id]) {

			global $gd_template_settingsmanager;
			return $gd_template_settingsmanager->get_page_block($page_id, GD_SETTINGS_HIERARCHY_SINGLE);
		}
	
		return parent::get_default_active_blockunit($template_id);
	}

	function init_atts_blockgroup_block($blockgroup, $blockgroup_block, &$blockgroup_block_atts, $blockgroup_atts) {

		global $gd_template_settingsmanager;

		// Set lazy for the blocks
		$active_blockunit = $this->get_active_blockunit($blockgroup, true);
		switch ($blockgroup) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				// Hide the Title, Controls, Filter
				$this->add_att($blockgroup_block, $blockgroup_block_atts, 'title', '');		
				$this->add_att($blockgroup_block, $blockgroup_block_atts, 'filter-hidden', true);	
				$this->add_att($blockgroup_block, $blockgroup_block_atts, 'show-controls', false);	

				// Do not load the content if not showing it initially
				if ($active_blockunit != $blockgroup_block) {

					$this->add_att($blockgroup_block, $blockgroup_block_atts, 'content-loaded', false);		
				}
				break;

		}

		return parent::init_atts_blockgroup_block($blockgroup, $blockgroup_block, $blockgroup_block_atts, $blockgroup_atts);
	}

	function init_atts($template_id, &$atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL:

				// Hide the tab title
				$this->append_att($template_id, $atts, 'class', 'pop-tabtitle-hidden');
				break;
		}

		$class = '';
		$feeds = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL,
		);
		if (in_array($template_id, $feeds)) {
			$class = 'feed';
		}
		if ($class) {
			$this->append_att($template_id, $atts, 'class', $class);
		}

		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new VotingProcessors_Template_Processor_SingleSectionTabPanelBlockGroups();
