<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-byorganizations-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-byindividuals-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-pro-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-against-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-neutral-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-pro-general-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-against-general-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-neutral-general-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-pro-article-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-against-article-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE', PoP_ServerUtils::get_template_definition('blockgroup-opinionatedvotes-neutral-article-tabpanel'));
define ('GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES', PoP_ServerUtils::get_template_definition('blockgroup-myopinionatedvotes-tabpanel'));

class VotingProcessors_Template_Processor_SectionTabPanelBlockGroups extends GD_Template_Processor_SectionTabPanelBlockGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES,
		);
	}

	function get_block_jsmethod($template_id, $atts) {

		$ret = parent::get_block_jsmethod($template_id, $atts);
		
		switch ($template_id) {
		
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES:

				// Only reload/destroy if these are main blocks
				if ($this->get_att($template_id, $atts, 'is-mainblock')) {
					$this->add_jsmethod($ret, 'destroyPageOnUserLoggedOut');
					$this->add_jsmethod($ret, 'refetchBlockGroupOnUserLoggedIn');
				}
				break;
		}

		return $ret;
	}

	function get_blockgroup_blocks($template_id) {

		$ret = parent::get_blockgroup_blocks($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_FULLVIEW,
						// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_DETAILS,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_THUMBNAIL,
					)
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES:

				$ret = array_merge(
					$ret,
					array(
						GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_TABLE_EDIT,
						GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_SCROLL_FULLVIEWPREVIEW,
					)
				);
				break;
		}

		$ret = apply_filters('VotingProcessors_Template_Processor_SectionTabPanelBlockGroups:blocks', $ret, $template_id);

		return $ret;
	}

	function get_panel_headers($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
					),
					// GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_DETAILS => array(
					// 	GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_DETAILS,
					// 	GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
					// 	GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
					// ),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_THUMBNAIL,
					),
				);
				break;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE:

				$ret = array(
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_FULLVIEW => array(),
					GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST => array(
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST,
						GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_THUMBNAIL,
					),
				);
				break;
		}

		if ($ret) {
			return apply_filters('VotingProcessors_Template_Processor_SectionTabPanelBlockGroups:panel_headers', $ret, $template_id);
		}

		return parent::get_panel_headers($template_id, $atts);
	}

	protected function get_controlgroup_top($template_id) {

		// Do not add for the quickview, since it is a modal and can't open a new modal (eg: Embed) on top
		$vars = GD_TemplateManager_Utils::get_vars();
		if (!$vars['fetching-json-quickview']) {

			switch ($template_id) {

				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE:
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE:
				
					return GD_TEMPLATE_CONTROLGROUP_POSTLIST;
				
				case GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES:
				
					return GD_TEMPLATE_CONTROLGROUP_MYPOSTLIST;
			}
		}

		return parent::get_controlgroup_top($template_id);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES:
				
				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS:

				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES_AUTHORROLE;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE:
			
				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES_STANCE;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL:
			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL:
			
				return GD_TEMPLATE_FILTER_OPINIONATEDVOTES_GENERALSTANCE;

			case GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES:
				
				return GD_TEMPLATE_FILTER_MYOPINIONATEDVOTES;
		}
		
		return parent::get_filter_template($template_id);
	}

	function get_panel_header_fontawesome($blockgroup, $blockunit) {

		// $details = array(
		// 	GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_DETAILS,
		// );
		$fullviews = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_FULLVIEW,
		);
		$grids = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST,
		);
		$edits = array(
			GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_TABLE_EDIT,
		);
		$fullviewpreviews = array(
			GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_SCROLL_FULLVIEWPREVIEW,
		);

		/*if (in_array($blockunit, $details)) {

			return 'fa-th-list';
		}
		else*//*if (in_array($blockunit, $fullviews)) {
			
			return 'fa-road';
		}*/
		if (in_array($blockunit, $fullviews) || in_array($blockunit, $fullviewpreviews)) {
			
			return 'fa-angle-double-right';
		}
		elseif (in_array($blockunit, $grids)) {
			
			return 'fa-th';
		}
		elseif (in_array($blockunit, $lists)) {
			
			return 'fa-list';
		}
		elseif (in_array($blockunit, $edits)) {
			
			return 'fa-edit';
		}
		// elseif (in_array($blockunit, $fullviewpreviews)) {
			
		// 	return 'fa-eye';
		// }

		return parent::get_panel_header_fontawesome($blockgroup, $blockunit);
	}
	function get_panel_header_title($blockgroup, $blockunit) {
	// function get_panel_header_tooltip($blockgroup, $blockunit) {

		// $details = array(
		// 	GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_DETAILS,
		// );
		$fullviews = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_FULLVIEW,
		);
		$grids = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST,
			GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST,
		);
		$edits = array(
			GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_TABLE_EDIT,
		);
		$fullviewpreviews = array(
			GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_SCROLL_FULLVIEWPREVIEW,
		);

		/*if (in_array($blockunit, $details)) {

			return __('Details', 'poptheme-wassup-votingprocessors');
		}
		else*/if (in_array($blockunit, $fullviews)) {
			
			return __('Full view', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $grids)) {
			
			return __('Grid', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $lists)) {
			
			return __('List', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $edits)) {
			
			return __('Edit', 'poptheme-wassup-votingprocessors');
		}
		elseif (in_array($blockunit, $fullviewpreviews)) {
			
			return __('View/Preview', 'poptheme-wassup-votingprocessors');
		}

		return parent::get_panel_header_title($blockgroup, $blockunit);
	}

	function init_atts($template_id, &$atts) {

		$class = '';
		$feeds = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE,
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE,
		);
		$tables = array(
			GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES,
		);
		if (in_array($template_id, $feeds)) {
			$class = 'feed';
		}
		elseif (in_array($template_id, $tables)) {
			$class = 'tableblock';
		}
		if ($class) {
			$this->append_att($template_id, $atts, 'class', $class);
		}
		
		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new VotingProcessors_Template_Processor_SectionTabPanelBlockGroups();
