services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPWPSchema\Blocks\TypeAPIs\BlockTypeTypeAPIInterface:
        class: \PoPWPSchema\Blocks\TypeAPIs\BlockTypeTypeAPI

    PoPWPSchema\Blocks\FilterInputs\:
        resource: '../src/FilterInputs/*'
