{
  customPosts(
    filter:{
      customPostTypes: [
        "post",
        "page",
        "attachment",
        "nav_menu_item",
        "custom_css",
        "revision"
      ],
      status:[
        publish,
        inherit
      ]
    },
    pagination: {
      limit: 12
    }
    sort: {
      by: ID
      order: ASC
    }
  ) {
    id
    title
    customPostType
    status
    __typename
  }
  
  dummyCustomPosts: customPosts(
    filter:{
      customPostTypes: "dummy-cpt"
    }
  ) {
    __typename
    ...on GenericCustomPost {
      id
      title
      customPostType
    }
  }
}