{
  customPosts(
    filter:{
      customPostTypes: [
        "post",
        "page",
        "attachment",
        "nav_menu_item",
        "custom_css",
        "revision"
      ],
      status:[
        publish,
        inherit
      ]
    },
    pagination: {
      limit: 15
    }
    sort: {
      order: ASC
    }
  ) {
    id
    title
    customPostType
    status
    __typename
  }
}