query GetTypeInfoByIntrospection {
  __schema {
    customPostUnionType: type(name: "CustomPostUnion") {
      name
      possibleTypes {
        name
      }
    }
    customPostEnumType: type(name: "CustomPostEnumString") {
      name
      extensions {
        possibleValues
      }
    }
  }
}