<?php

/**---------------------------------------------------------------------------------------------------------------
 *
 * IDs Configuration
 *
 * ---------------------------------------------------------------------------------------------------------------*/

// Placeholders for images
//--------------------------------------------------------
define ('POPTHEME_WASSUPHOSTS_THUMB_ALIRAN', 23541);
define ('POPTHEME_WASSUPHOSTS_THUMB_ALTERNET', 23542);
define ('POPTHEME_WASSUPHOSTS_THUMB_ASETUFTSGDAE', 23543);
define ('POPTHEME_WASSUPHOSTS_THUMB_ASTROAWANI', 23544);
define ('POPTHEME_WASSUPHOSTS_THUMB_BERITADAILY', 23545);
define ('POPTHEME_WASSUPHOSTS_THUMB_BERITAHARIAN', 23546);
define ('POPTHEME_WASSUPHOSTS_THUMB_BFM', 23547);
define ('POPTHEME_WASSUPHOSTS_THUMB_BLOOMBERGTYMALAYSIA', 23548);
define ('POPTHEME_WASSUPHOSTS_THUMB_BREITBART', 23549);
define ('POPTHEME_WASSUPHOSTS_THUMB_CHICAGOTRIBUNE', 23550);
define ('POPTHEME_WASSUPHOSTS_THUMB_CLEANMALAYSIA', 23551);
define ('POPTHEME_WASSUPHOSTS_THUMB_COMMONDREAMS', 23552);
define ('POPTHEME_WASSUPHOSTS_THUMB_EFF', 23553);
define ('POPTHEME_WASSUPHOSTS_THUMB_FB', 23554);
define ('POPTHEME_WASSUPHOSTS_THUMB_FINANCIALPOST', 23555);
define ('POPTHEME_WASSUPHOSTS_THUMB_FOREIGNPOLICY', 23556);
define ('POPTHEME_WASSUPHOSTS_THUMB_FREEMALAYSIATODAY', 23557);
define ('POPTHEME_WASSUPHOSTS_THUMB_FTAMALAYSIA', 23558);
define ('POPTHEME_WASSUPHOSTS_THUMB_HUMANRIGHTSWATCH', 23559);
define ('POPTHEME_WASSUPHOSTS_THUMB_HUFFINGTONPOST', 23560);
define ('POPTHEME_WASSUPHOSTS_THUMB_INFOJUSTICE', 23561);
define ('POPTHEME_WASSUPHOSTS_THUMB_JANGANJUALNEGARA', 23562);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEJAPANTIMES', 23563);
define ('POPTHEME_WASSUPHOSTS_THUMB_JAPANTODAY', 23564);
define ('POPTHEME_WASSUPHOSTS_THUMB_KINITV', 23565);
define ('POPTHEME_WASSUPHOSTS_THUMB_LINKEDIN', 23566);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYSIAKINI', 23567);
define ('POPTHEME_WASSUPHOSTS_THUMB_MESYM', 23568);
define ('POPTHEME_WASSUPHOSTS_THUMB_MICHAELGEIST', 23569);
define ('POPTHEME_WASSUPHOSTS_THUMB_MITI', 23570);
define ('POPTHEME_WASSUPHOSTS_THUMB_NANYANG', 23571);
define ('POPTHEME_WASSUPHOSTS_THUMB_NST', 23572);
define ('POPTHEME_WASSUPHOSTS_THUMB_NYT', 23573);
define ('POPTHEME_WASSUPHOSTS_THUMB_NZHERALD', 23574);
define ('POPTHEME_WASSUPHOSTS_THUMB_POLITICO', 23575);
define ('POPTHEME_WASSUPHOSTS_THUMB_RABBLECA', 23576);
define ('POPTHEME_WASSUPHOSTS_THUMB_THERAKYATPOST', 23577);
define ('POPTHEME_WASSUPHOSTS_THUMB_RAPPLER', 23578);
define ('POPTHEME_WASSUPHOSTS_THUMB_REUTERS', 23579);
define ('POPTHEME_WASSUPHOSTS_THUMB_RT', 23580);
define ('POPTHEME_WASSUPHOSTS_THUMB_SOUTHCHINAMORNINGPOST', 23581);
define ('POPTHEME_WASSUPHOSTS_THUMB_SEATTLETIMES', 23582);
define ('POPTHEME_WASSUPHOSTS_THUMB_SINARHARIAN', 23583);
define ('POPTHEME_WASSUPHOSTS_THUMB_SINCHEW', 23584);
define ('POPTHEME_WASSUPHOSTS_THUMB_STUFF', 23585);
define ('POPTHEME_WASSUPHOSTS_THUMB_TECHDIRT', 23586);
define ('POPTHEME_WASSUPHOSTS_THUMB_THANHNIENNEWS', 23587);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEBORNEOPOST', 23588);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEBUREAUOFINVESTIGATIVEJOURNALISM', 23589);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEEDGEMARKETS', 23590);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEGLOBEANDMAIL', 23591);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEGUARDIAN', 23592);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEJAKARTAPOST', 23593);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYMAILONLINE', 23594);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYSIANINSIDER', 23595);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEMALAYSIANRESERVE', 23596);
define ('POPTHEME_WASSUPHOSTS_THUMB_THENATION', 23597);
define ('POPTHEME_WASSUPHOSTS_THUMB_THESTAR', 23598);
define ('POPTHEME_WASSUPHOSTS_THUMB_THESUNDAILY', 23599);
define ('POPTHEME_WASSUPHOSTS_THUMB_THETYEE', 23600);
define ('POPTHEME_WASSUPHOSTS_THUMB_THIRDWORLDNETWORK', 23601);
define ('POPTHEME_WASSUPHOSTS_THUMB_TODAYONLINE', 23602);
define ('POPTHEME_WASSUPHOSTS_THUMB_TPPDEBATE', 23603);
define ('POPTHEME_WASSUPHOSTS_THUMB_TWITTER', 23604);
define ('POPTHEME_WASSUPHOSTS_THUMB_VARIETY', 23605);
define ('POPTHEME_WASSUPHOSTS_THUMB_WASHINGTONPOST', 23606);
define ('POPTHEME_WASSUPHOSTS_THUMB_WASHINGTONTIMES', 23607);
define ('POPTHEME_WASSUPHOSTS_THUMB_WSJ', 23608);
define ('POPTHEME_WASSUPHOSTS_THUMB_XINHUANET', 23609);
