<?php

// Routes
//--------------------------------------------------------
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS00')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS00', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS01')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS01', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS02')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS02', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS03')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS03', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS04')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS04', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS05')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS05', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS06')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS06', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS07')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS07', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS08')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS08', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS09')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS09', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS10')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS10', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS11')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS11', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS12')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS12', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS13')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS13', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS14')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS14', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS15')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS15', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS16')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS16', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS17')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS17', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS18')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS18', false);
}
if (!defined('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS19')) {
	define('POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS19', false);
}

\PoP\Root\App::addFilter(
    \PoP\RoutingWP\RouteHookNames::ROUTES,
    function($routes) {
    	return array_merge(
    		$routes,
    		array_filter([
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS00,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS01,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS02,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS03,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS04,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS05,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS06,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS07,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS08,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS09,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS10,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS11,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS12,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS13,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS14,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS15,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS16,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS17,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS18,
				POP_CATEGORYPOSTSCREATION_ROUTE_MYCATEGORYPOSTS19,
    		])
    	);
    }
);
