<?php

/**---------------------------------------------------------------------------------------------------------------
 *
 * IDs Configuration
 *
 * ---------------------------------------------------------------------------------------------------------------*/

// Gravity Forms Field Ids
//--------------------------------------------------------
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FIELDNAME_NAME_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FIELDNAME_EMAIL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FIELDNAME_TOPIC_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FIELDNAME_SUBJECT_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUS_FIELDNAME_MESSAGE_ID', false);

define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_NAME_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_EMAIL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_SUBJECT_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_MESSAGE_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_PAGEURL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_PAGETITLE_ID', false);

define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_NAME_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_EMAIL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PHONE_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_WHYVOLUNTEER_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PAGEURL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PAGETITLE_ID', false);

define ('POP_GENERICFORMS_GF_FORM_FLAG_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_FLAG_FIELDNAME_NAME_ID', false);
define ('POP_GENERICFORMS_GF_FORM_FLAG_FIELDNAME_EMAIL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_FLAG_FIELDNAME_WHYFLAG_ID', false);
define ('POP_GENERICFORMS_GF_FORM_FLAG_FIELDNAME_PAGEURL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_FLAG_FIELDNAME_PAGETITLE_ID', false);

define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_NAME_ID', false);
define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_DESTINATIONEMAILS_ID', false);
define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_ADDITIONALMESSAGE_ID', false);
define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_PAGEURL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_PAGETITLE_ID', false);

define ('POP_GENERICFORMS_GF_FORM_NEWSLETTER_FORM_ID', false);
define ('POP_GENERICFORMS_GF_FORM_NEWSLETTER_FIELDNAME_EMAIL_ID', false);
define ('POP_GENERICFORMS_GF_FORM_NEWSLETTER_FIELDNAME_NAME_ID', false);

