<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categoryposts09'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedback-categorywebposts09'));

define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategoryposts09'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedback-mycategorywebposts09'));

class CPP_Template_Processor_CustomListMessageFeedbacks extends GD_Template_Processor_MessageFeedbacksBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS09,
		);
	}

	function get_inner_template($template_id) {

		$inners = array(
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS00 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS01 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS02 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS03 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS04 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS05 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS06 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS07 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS08 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYPOSTS09 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS00 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS01 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS02 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS03 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS04 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS05 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS06 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS07 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS08 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_CATEGORYWEBPOSTS09 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS00 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS01 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS02 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS03 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS04 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS05 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS06 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS07 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS08 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYPOSTS09 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS00 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS01 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS02 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS03 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS04 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS05 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS06 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS07 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS08 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS09 => GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS09,
		);

		if ($inner = $inners[$template_id]) {

			return $inner;
		}

		return parent::get_inner_template($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CustomListMessageFeedbacks();