<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categoryposts09'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-categorywebposts09'));

define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategoryposts09'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts00'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts01'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts02'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts03'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts04'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts05'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts06'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts07'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts08'));
define ('GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('messagefeedbackinner-mycategorywebposts09'));

class CPP_Template_Processor_CustomListMessageFeedbackInners extends GD_Template_Processor_MessageFeedbackInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS09,
		);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		$layouts = array(
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_CATEGORYWEBPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_MESSAGEFEEDBACKINNER_MYCATEGORYWEBPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS09,
		);

		if ($layout = $layouts[$template_id]) {

			$ret[] = $layout;
		}

		return $ret;
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CustomListMessageFeedbackInners();