<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-categoryposts09'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts09'));

class CPP_Template_Processor_CustomListMessageFeedbackFrameLayouts extends GD_Template_Processor_MessageFeedbackFrameLayoutsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09,
		);
	}

	function get_layout($template_id) {

		$layouts = array(
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS09,
		);

		if ($layout = $layouts[$template_id]) {

			return $layout;
		}

		return parent::get_layout($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CustomListMessageFeedbackFrameLayouts();