<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categoryposts09'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-categorywebposts09'));

define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategoryposts09'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts00'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts01'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts02'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts03'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts04'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts05'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts06'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts07'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts08'));
define ('GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('layout-messagefeedbackframe-mycategorywebposts09'));

class CPP_Template_Processor_CustomListMessageFeedbackFrameLayouts extends GD_Template_Processor_MessageFeedbackFrameLayoutsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS09,
		);
	}

	function get_layout($template_id) {

		$layouts = array(
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_CATEGORYWEBPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYPOSTS09,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS00 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS00,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS01 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS01,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS02 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS02,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS03 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS03,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS04 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS04,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS05 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS05,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS06 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS06,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS07 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS07,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS08 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS08,
			GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME_MYCATEGORYWEBPOSTS09 => GD_TEMPLATE_LAYOUT_MESSAGEFEEDBACK_MYCATEGORYWEBPOSTS09,
		);

		if ($layout = $layouts[$template_id]) {

			return $layout;
		}

		return parent::get_layout($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CustomListMessageFeedbackFrameLayouts();