########################################################################
#
# This Persisted GraphQL query fetches the data for all blocks in the post
# (including inner blocks) while filtering them by `core/image` type,
# and extracts the URL property from each.
#
# *********************************************************************
# 
# Variables:
#   - postId: ID of the post to fetch the images from
#
# *********************************************************************
#
# More info:
#   - https://gatographql.com/tutorial/retrieving-structured-data-from-blocks/
#
########################################################################

query GetImageBlockImageURLs($postId: ID!) {
  post(by: { id: $postId } ) {
    coreImageURLs: blockFlattenedDataItems(
      filterBy: { include: "core/image" }
    )
      @underEachArrayItem(
        passValueOnwardsAs: "blockDataItem"
      )
        @applyField(
          name: "_objectProperty"
          arguments: {
            object: $blockDataItem,
            by: {
              path: "attributes.url"
            }
          }
          setResultInResponse: true
        )
      @arrayUnique
  }
}