########################################################################
#
# This Persisted GraphQL query retrieves all users with a certain locale,
# providing a regex to identify them.
#
# *********************************************************************
# 
# Variables:
#   - localeRegex: The regex to identify the locale
#       eg: "es_[A-Z]+" for the Spanish locale (es_AR for Argentina, es_ES for Spain, etc)
#
# *********************************************************************
#
# More info:
#   - https://gatographql.com/recipes/searching-wordpress-data/
#
########################################################################

query FetchUsersByLocale(
  $localeRegex: String!
) {
  usersByLocale: users(
    filter: { metaQuery: {
      key: "locale",
      compareBy: {
        stringValue: {
          value: $localeRegex
          operator: REGEXP
        }
      }
    }},
    pagination: { limit: -1 }
  ) {
    id
    name
    locale: metaValue(key: "locale")
  }
}