########################################################
# This query tests that the pre-defined module configuration
# on the admin endpoint (set on
# `doGetPredefinedAdminEndpointModuleClassConfiguration`)
# has taken effect. For instance, all custom post types
# are queryable.
########################################################
{
  __schema {
    customPostEnumType: type(name: "CustomPostEnumString") {
      name
      extensions {
        possibleValues
      }
    }
    tagTaxonomyEnumType: type(name: "TagTaxonomyEnumString") {
      name
      extensions {
        possibleValues
      }
    }
  }
}