<?php

// // Categories
// //--------------------------------------------------------
// define ('GETPOP_PROCESSORS_CAT_DOCUMENTATION', false);

// Pages
//--------------------------------------------------------
define ('GETPOP_PROCESSORS_PAGE_CONTACTABOUTUS', false);
define ('GETPOP_PROCESSORS_PAGE_WHATISIT', false);
// define ('GETPOP_PROCESSORS_PAGE_DISCOVER', false);
define ('GETPOP_PROCESSORS_PAGE_FRAMEWORK', false);
define ('GETPOP_PROCESSORS_PAGE_HOME', false);

define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_COMINGSOON', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_OVERVIEW', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULARITY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULEHIERARCHY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_PROPERTIES', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATALOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATAPOSTING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSONSTRUCTURE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_APPLICATIONSTATE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_USABILITY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_BACKGROUNDLOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_LAZYLOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CACHE', false);

// URLs
//--------------------------------------------------------
define ('GETPOP_URL_DEMOWEBSITE', false);
define ('GETPOP_URL_DOWNLOADLINK', false);
define ('GETPOP_URL_GITHUBREPOSITORY', false);
define ('GETPOP_URL_EXTERNALWEBSITEDOMAIN', false);
define ('GETPOP_URL_EXTERNALWEBSITENAME', false);
