<?php

// // Categories
// //--------------------------------------------------------
// define ('GETPOP_PROCESSORS_CAT_DOCUMENTATION', false);

// Pages
//--------------------------------------------------------
define ('GETPOP_PROCESSORS_PAGE_CONTACTABOUTUS', false);
define ('GETPOP_PROCESSORS_PAGE_WHATISIT', false);
// define ('GETPOP_PROCESSORS_PAGE_DISCOVER', false);
define ('GETPOP_PROCESSORS_PAGE_FRAMEWORK', false);
define ('GETPOP_PROCESSORS_PAGE_HOME', false);

// Documentation
//========================================================
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_OVERVIEW', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONARCHITECTURE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONCONTROLLER', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONMODEL', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONVIEW', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONAPPLICATIONLOGIC', false);

// Section Architecture
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_POPENGINE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_PLUGINSHIERARCHY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULARITY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULEHIERARCHY', false);

// Section Controller
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_PROPERTIES', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSONSTRUCTURE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_APPLICATIONSTATE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_USABILITY', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_BACKGROUNDLOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_LAZYLOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CACHE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CHECKPOINTS', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CRAWLABLE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_IOHANDLER', false);

// Section Model
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATALOADING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATAPOSTING', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FORMS', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FILTERS', false);

// Section View
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FRONTENDOVERVIEW', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSFUNCTIONS', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_INITIALIZINGJS', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSOBJECTSTATE', false);
// define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSLIFECYCLE', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DYNAMICTEMPLATES', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DOMINTERACTION', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_REPLICATION', false);

// Section Application Logic
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_BOOTSTRAP', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_USERROLES', false);
define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_EVENTS', false);


// define ('GETPOP_PROCESSORS_PAGE_DOCUMENTATION_COMINGSOON', false);

// URLs
//--------------------------------------------------------
define ('GETPOP_URL_DEMOWEBSITE', false);
define ('GETPOP_URL_DOWNLOADLINK', false);
define ('GETPOP_URL_GITHUBREPOSITORY', false);
define ('GETPOP_URL_EXTERNALWEBSITEDOMAIN', false);
define ('GETPOP_URL_EXTERNALWEBSITENAME', false);
