<?php

declare(strict_types=1);

namespace GatoGraphQLStandalone\GatoGraphQL;

class Environment
{
    public final const ENABLE_ADVANCED_MODE = 'ENABLE_ADVANCED_MODE';
    public final const DISABLE_AUTOMATIC_CONFIG_UPDATES = 'DISABLE_AUTOMATIC_CONFIG_UPDATES';
    public final const OVERRIDE_ERROR_FEEDBACK_ITEM_PROVIDER_OBJECT_NOT_FOUND_ERROR_MESSAGE = 'OVERRIDE_ERROR_FEEDBACK_ITEM_PROVIDER_OBJECT_NOT_FOUND_ERROR_MESSAGE';
}
