###########################################################
# The commented values under the input `metaQuery`
# are the default values
###########################################################
query {
  postsByMetaQuery: posts(
    filter: {
      metaQuery: {
        key: "_thumbnail_id",
        compareBy: {
          key: {
            # operator: EXISTS
          }
        }
      }
    }
  ) {
    id
    title
  }
}
