<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class DisabledConvertInputValueFromSingleToListFixtureQueryExecutionGraphQLServerTest extends AbstractConvertInputValueFromSingleToListFixtureQueryExecutionGraphQLServerTest
{
    use DisabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
