<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class DisabledExposeGlobalFieldsInRootTypeOnlyInGraphQLSchemaWithNestedMutationsFixtureQueryExecutionGraphQLServerTest extends AbstractExposeGlobalFieldsInRootTypeOnlyInGraphQLSchemaWithNestedMutationsFixtureQueryExecutionGraphQLServerTest
{
    use DisabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
