<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class DisabledSkipDangerouslyNonSpecificTypeTypeFixtureQueryExecutionGraphQLServerTest extends AbstractSkipDangerouslyNonSpecificTypeTypeFixtureQueryExecutionGraphQLServerTest
{
    use DisabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
