<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class EnabledExposeGlobalFieldsInRootTypeOnlyInGraphQLSchemaFixtureQueryExecutionGraphQLServerTest extends AbstractExposeGlobalFieldsInRootTypeOnlyInGraphQLSchemaFixtureQueryExecutionGraphQLServerTestCase
{
    use EnabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
