<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class EnabledConvertInputValueFromSingleToListFixtureQueryExecutionGraphQLServerTest extends AbstractConvertInputValueFromSingleToListFixtureQueryExecutionGraphQLServerTestCase
{
    use EnabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
