<?php

declare(strict_types=1);

namespace GraphQLByPoP\GraphQLServer\Unit;

class EnabledSkipDangerouslyNonSpecificTypeTypeFixtureQueryExecutionGraphQLServerTest extends AbstractSkipDangerouslyNonSpecificTypeTypeFixtureQueryExecutionGraphQLServerTest
{
    use EnabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
