<?php

const POP_MODELINSTANCECOMPONENTTYPE_PAGE_ID = 'page-id';
const POP_MODELINSTANCECOMPONENTTYPE_PAGE_MAINCONTENTMODULE = 'page-main-content-module';
const POP_MODELINSTANCECOMPONENTTYPE_AUTHOR_ROLE = 'author-role';
const POP_MODELINSTANCECOMPONENTTYPE_SINGLE_POSTTYPE = 'single-posttype';
const POP_MODELINSTANCECOMPONENTTYPE_SINGLE_CATEGORIES = 'single-categories';
