<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLLINNER_MYMEMBERS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mymembers-fullviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-navigator'));

define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-addons'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-addons'));

define ('GD_TEMPLATE_SCROLLINNER_COMMUNITIES_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-communities-details'));
define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-details'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-details'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-authormembers-details'));

define ('GD_TEMPLATE_SCROLLINNER_COMMUNITIES_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-communities-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-authormembers-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_COMMUNITIES_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-communities-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-authormembers-thumbnail'));

define ('GD_TEMPLATE_SCROLLINNER_COMMUNITIES_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-communities-list'));
define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-list'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-list'));
// define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONMEMBERS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizationmembers-list'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-authormembers-list'));

define ('GD_TEMPLATE_SCROLLINNER_COMMUNITIES_MAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-communities-map'));
define ('GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_MAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-organizations-map'));
define ('GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_MAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-individuals-map'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_MAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-authormembers-map'));

class GD_URE_Template_Processor_CustomScrollInners extends GD_Template_Processor_ScrollInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLLINNER_MYMEMBERS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_COMMUNITIES_DETAILS,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_COMMUNITIES_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_COMMUNITIES_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_COMMUNITIES_LIST,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_LIST,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_LIST,
			// GD_TEMPLATE_SCROLLINNER_ORGANIZATIONMEMBERS_LIST,
			GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_LIST,
			GD_TEMPLATE_SCROLLINNER_COMMUNITIES_MAP,
			GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_MAP,
			GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_MAP,
			GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_MAP,
			GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_FULLVIEW,
		);
	}

	function get_layout_grid($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_COMMUNITIES_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_THUMBNAIL:

				return array(
					'row-items' => 4, 
					'class' => 'col-xsm-3'
				);

			case GD_TEMPLATE_SCROLLINNER_MYMEMBERS_FULLVIEWPREVIEW:

			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_NAVIGATOR:

			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_ADDONS:

			case GD_TEMPLATE_SCROLLINNER_COMMUNITIES_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_DETAILS:

			case GD_TEMPLATE_SCROLLINNER_COMMUNITIES_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_FULLVIEW:

			case GD_TEMPLATE_SCROLLINNER_COMMUNITIES_LIST:
			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_LIST:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_LIST:
			// case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONMEMBERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_LIST:

			case GD_TEMPLATE_SCROLLINNER_COMMUNITIES_MAP:
			case GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_MAP:
			case GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_MAP:
			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_MAP:

			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_FULLVIEW:

				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12'
				);
		}

		return parent::get_layout_grid($template_id, $atts);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_DETAILS:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_THUMBNAIL:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_LIST:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_LIST;
				break;
			
			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_FULLVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_FULLUSER;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORMEMBERS_MAP:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_MAPDETAILS;
				break;

			default:

				$layouts = array(
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_NAVIGATOR,

					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_ADDONS,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_ADDONS,

					GD_TEMPLATE_SCROLLINNER_COMMUNITIES_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_DETAILS,
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_DETAILS,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_DETAILS,

					GD_TEMPLATE_SCROLLINNER_COMMUNITIES_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_THUMBNAIL,

					GD_TEMPLATE_SCROLLINNER_COMMUNITIES_LIST => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_LIST,
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_LIST,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_LIST,

					// GD_TEMPLATE_SCROLLINNER_ORGANIZATIONMEMBERS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATIONMEMBERS_LIST,
					
					GD_TEMPLATE_SCROLLINNER_COMMUNITIES_MAP => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_MAPDETAILS,
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_MAP => GD_TEMPLATE_LAYOUT_PREVIEWUSER_ORGANIZATION_MAPDETAILS,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_MAP => GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_MAPDETAILS,

					GD_TEMPLATE_SCROLLINNER_COMMUNITIES_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLUSER_ORGANIZATION,
					GD_TEMPLATE_SCROLLINNER_ORGANIZATIONS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLUSER_ORGANIZATION,
					GD_TEMPLATE_SCROLLINNER_INDIVIDUALS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLUSER_INDIVIDUAL,

					GD_TEMPLATE_SCROLLINNER_MYMEMBERS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_MULTIPLEUSER_FULLUSER,
				);

				if ($layout = $layouts[$template_id]) {

					$ret[] = $layout;
				}
				break;
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_URE_Template_Processor_CustomScrollInners();