services:
    _defaults:
        public: true
        autowire: true

    PoPCMSSchema\MetaMutations\FieldResolvers\:
        resource: '../src/FieldResolvers/*'

    PoPCMSSchema\MetaMutations\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
