{
  posts(pagination: { limit: 6 }) {
    id
    title
    blocks {
      ...BlockData
    }
    blockDataItems
    blockFlattenedDataItems
  }

  includeBlockFilter1: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        include: "core/heading"
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        include: "core/heading"
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        include: "core/heading"
      }
    )
  }

  includeBlockFilter2: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        include: [
          "core/heading",
          "core/columns"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/columns"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/columns"
        ]
      }
    )
  }

  includeBlockFilter3: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        include: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    )
  }

  includeBlockFilter4: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        include: [
          "core/heading",
          "core/column"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/column"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        include: [
          "core/heading",
          "core/column"
        ]
      }
    )
  }

  excludeBlockFilter1: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        exclude: "core/heading"
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        exclude: "core/heading"
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        exclude: "core/heading"
      }
    )
  }

  excludeBlockFilter2: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns"
        ]
      }
    )
  }

  excludeBlockFilter3: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/columns",
          "core/column"
        ]
      }
    )
  }

  excludeBlockFilter4: post(by: { id: 1119 }) {
    id
    blocks(
      filterBy: {
        exclude: [
          "core/heading",
          "core/column"
        ]
      }
    ) {
      ...BlockData
    }
    blockDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/column"
        ]
      }
    )
    blockFlattenedDataItems(
      filterBy: {
        exclude: [
          "core/heading",
          "core/column"
        ]
      }
    )
  }

  page(by: { id: 2 }) {
    id
    title
    blocks {
      ...BlockData
    }
    blockDataItems
    blockFlattenedDataItems
  }

  customPost(by: { id: 1654 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }

  contentWithoutBlocks: customPost(by: { id: 1619 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }

  nonExistingBlocks: customPost(by: { id: 1656 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }

  noContent: customPost(by: { id: 1658 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }

  serverSideRegisteredBlocks: customPost(by: { id: 1680 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }

  notServerSideRegisteredBlocks: customPost(by: { id: 1660 }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      rawContent
      customPostType
      blocks {
        ...BlockData
      }
      blockDataItems
      blockFlattenedDataItems
    }
  }
  
  # This post contains blocks containing blocks containing blocks
  singleLevelBlockPost: post(by: {id: 1128}) {
    id
    title
    blocks {
      ...BlockData
    }
    blockDataItems
    blockFlattenedDataItems
  }

  # This post contains blocks containing blocks containing blocks,
  # and a last level with empty attributes (that must be returned)
  # as {}, not as []
  multiLevelBlockPost: post(by: {id: 1140}) {
    id
    title
    blocks {
      ...BlockData
    }
    blockDataItems
    blockFlattenedDataItems
  }
}

fragment BlockData on Block {
  name
  attributes
  # innerHTML
  contentSource
  innerBlocks {
    name
    attributes
    # innerHTML
    contentSource
    innerBlocks {
      name
      attributes
      # innerHTML
      contentSource
      innerBlocks {
        name
        attributes
        # innerHTML
        contentSource
        innerBlocks {
          name
          attributes
          # innerHTML
          contentSource
          innerBlocks {
            name
            attributes
            # innerHTML
            contentSource
            innerBlocks {
              name
              attributes
              # innerHTML
              contentSource
              innerBlocks {
                name
                attributes
                # innerHTML
                contentSource
              }
            }
          }
        }
      }
    }
  }
}
