{
  categories(
    taxonomy: "dummy-category"
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...GenericCategoryData
    ...CategoryData
  }
  
  customPosts(
    filter: {
      customPostTypes: ["post","dummy-cpt"]
    }
    pagination: {
      limit: 30
    }
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on CustomPost {
      id
      title
      customPostType
    }
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        __typename
        id
        name
        taxonomy
      }
    }
    ...on Post {
      categories {
        __typename
        id
        name
        slug
        slugPath
      }
    }
  }

  customPostsByCategoryIDs: customPosts(
    filter: {
      categories: {
        includeBy: {
          ids: [23, 32]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsExcludeByCategoryIDs: customPosts(
    filter: {
      categories: {
        excludeBy: {
          ids: [23, 32]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsByCategorySlugs: customPosts(
    filter: {
      categories: {
        includeBy: {
          slugs: ["capullo"]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsExcludeByCategorySlugs: customPosts(
    filter: {
      categories: {
        excludeBy: {
          slugs: ["capullo"]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }
  
  customPostsExcludeByCategorySlugsOnCPT: customPosts(
    filter: {
      customPostTypes: "dummy-cpt"
      categories: {
        excludeBy: {
          slugs: ["capullo"]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      categories(
        taxonomy: "dummy-category"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  postCategories: categories(
    taxonomy: category
    sort: { by: ID, order: ASC }
  ) {
    ...CategoryData
  }
  postCategoryByID: category(taxonomy: category, by: { id: 1 }) {
    ...CategoryData
  }
  postCategoryBySlug: category(taxonomy: category, by: { slug: "resource" }) {
    ...CategoryData
  }
  postCategoryCount: categoryCount(taxonomy: category)
  postCategoryNames: categoryNames(taxonomy: category)

  dummyCategories: categories(
    taxonomy: "dummy-category"
    sort: { by: ID, order: ASC }
  ) {
    ...CategoryData
  }
  dummyCategoryByID: category(taxonomy: "dummy-category", by: { id: 23 }) {
    ...CategoryData
  }
  dummyCategoryBySlug: category(taxonomy: "dummy-category", by: { slug: "nostradamus" }) {
    ...CategoryData
  }
  dummyCategoryCount: categoryCount(taxonomy: "dummy-category")
  dummyCategoryNames: categoryNames(taxonomy: "dummy-category")
}

fragment CategoryData on Category {
  taxonomy
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  slugPath
  url
  urlPath
}

fragment GenericCategoryData on GenericCategory {
  taxonomy   
  customPostCount
  customPosts(sort: {by: ID, order: ASC}) {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on CustomPost {
  id
  title
  categories(
    taxonomy: "dummy-category"
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on Category {
      id
      name
    }
  }
}