{
  post(by:{ id: 1121 }) {
    comments {
      ...CommentData
      responses {
        ...CommentData
      }
    }
    commentsByDateQuery: comments(filter: { dateQuery: { before: "2022-01-02" } }) {
      id
    }
    commentsByExcludeIDs: comments(filter: { excludeIDs: [7] }) {
      id
    }
    commentsByExcludeParentIDs: comments(filter: { excludeParentIDs: [7] }) {
      id
    }
    emptyCommentsByIds: comments(filter: { ids: [] }) {
      id
    }
    commentsByIds: comments(filter: { ids: [7] }) {
      id
    }
    commentsByMetaQuery: comments(filter: { metaQuery: {
      key: "_thumbnail_id",
      compareBy:{
        key: {
          operator: NOT_EXISTS
        }
      }
    } }) {
      id
    }
    commentsByParentID: comments(filter: { parentID: 7 }) {
      id
    }
    commentsByParentIDs: comments(filter: { parentID: null, parentIDs: [4, 7] }) {
      id
    }
    commentsBySearch: comments(filter: { search: "endpoint" }) {
      id
    }
    commentsByStatus: comments(filter: { status: [hold] }) {
      id
    }
    commentsByTypes: comments(filter: { types: [pingback] }) {
      id
    }
    
    commentsBySortASC: comments(sort: { by: DATE, order: ASC }) {
      id
      date
    }
    commentsBySortDESC: comments(sort: { by: DATE, order: DESC }) {
      id
      date
    }
  }

  commentsByCommentAuthor: comments(
    filter: { author: { ids: [1, 3] } }
    pagination: { limit: 3 }
    sort: { by: ID, order: ASC }
  ) {
    id
  }
  commentsByExcludeCommentAuthor: comments(
    filter: { author: { excludeIDs: [1, 3] } }
    pagination: { limit: 3 }
    sort: { by: ID, order: ASC }
  ) {
    id
  }
  commentsByCustomPostAuthor: comments(
    filter: { customPostAuthor: { ids: [1, 3] } }
    pagination: { limit: 3 }
    sort: { by: ID, order: ASC }
  ) {
    id
  }
  commentsByExcludeCustomPostAuthor: comments(
    filter: { customPostAuthor: { excludeIDs: [1, 3] } }
    pagination: { limit: 3 }
    sort: { by: ID, order: ASC }
  ) {
    id
  }
}

fragment CommentData on Comment {
  approved
  author {
    id
    name
  }
  authorEmail
  authorIP
  authorName
  authorURL
  content
  customPost {
    id
    title
  }
  customPostID
  date
  dateStr
  id
  karma
  metaValue(key: "description")
  parent {
    id
  }
  rawContent
  responseCount
  status
  type
}