query {
  customPosts(filter: { ids: [1, 2, 1113] }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      areCommentsOpen
      author {
        id
        name
      }
      commentCount
      comments {
        id
      }
      content
      customPostType
      date
      dateStr
      excerpt
      ...on WithFeaturedImage {
        featuredImage {
          id
          src
        }
      }
      hasComments
      ...on WithFeaturedImage {
        hasFeaturedImage
      }
      id
      isStatus(status: pending)
      metaValue(key: "_thumbnail_id")
      # These ones produce the value of data being inserted to DB, so can't save fixed value for testing
      # modifiedDate
      # modifiedDateStr(format: "m-d")
      rawContent
      slug
      status
      title
      url
      urlPath
    }
  }

  customPostsByAuthorIDs: customPosts(filter: { author: { ids: 5 } }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByAuthorSlug: customPosts(filter: { author: { slug: "blogger" } }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByCustomPostTypes: customPosts(filter: { customPostTypes: "page" }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByDateQuery: customPosts(filter: { dateQuery: { before: "2020-04-20" } }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByExcludeAuthorIDs: customPosts(filter: { author: { excludeIDs: 4 } }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByExcludeIDs: customPosts(filter: { excludeIDs: [1, 1128] }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByHasPassword: customPosts(filter: { hasPassword: true }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByIds: customPosts(filter: { ids: [1, 1128] }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByMetaQuery: customPosts(filter: { metaQuery: { key: "_thumbnail_id", compareBy: { key: { operator: EXISTS } } } }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByPassword: customPosts(filter: { password: "password" }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsBySearch: customPosts(filter: { search: "hello" }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsByStatus: customPosts(filter: { status: draft }, sort: { by: ID, order: ASC }) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  
  customPostsSortedASC: customPosts(pagination: { limit: 3 }, sort: { by: TITLE, order: ASC}) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  customPostsSortedDESC: customPosts(pagination: { limit: 3 }, sort: { by: TITLE, order: DESC}) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }

  singleCustomPost: customPost(by: { id: 1619 }) {
    __typename
    ...on CustomPost {
      id
      title
      content
      customPostType
    }
  }
}
