query {
  customPostsWithParent: customPosts(filter: { ids: [1682, 1684, 1688] }, sort: { by: ID, order: ASC }) {
    __typename
    ...on GenericCustomPost {
      id
      title
      parent {
        id
        title
      }
      ancestors {
        id
        title
      }
      # draftAncestors: ancestors(filter: { status: draft }) {
      #   id
      #   title
      # }
      # publishedAncestors: ancestors(filter: { status: publish }) {
      #   id
      #   title
      # }
      children {
        id
        title
      }
      draftChildren: children(filter: { status: draft }) {
        id
        title
      }
      publishedChildren: children(filter: { status: publish }) {
        id
        title
      }
      childCount
      draftChildCount: childCount(filter: { status: draft })
      publishedChildCount: childCount(filter: { status: publish })
    }
  }
}
