query {
  defaultMediaItems: mediaItems(pagination: { limit: 3 }, sort: { by: ID, order: ASC }) {
    ...MediaItemData
  }
  anyMimeTypeMediaItems: mediaItems(pagination: { limit: 3 }, sort: { by: ID, order: ASC }, filter: { mimeTypes: "*" }) {
    ...MediaItemData
  }

  mediaItemsByAuthorIDs: mediaItems(filter: { author: { ids: 2 }, mimeTypes: "*" }) {
    id
    title
  }
  mediaItemsByAuthorSlug: mediaItems(filter: { author: { slug: "blogger" }, mimeTypes: "*" }) {
    id
    title
  }
  mediaItemsByDateQuery: mediaItems(filter: { dateQuery: { before: "2022-05-26" }, mimeTypes: "*" }) {
    id
    title
  }
  mediaItemsByExcludeAuthorIDs: mediaItems(filter: { author: { excludeIDs: 2 }, mimeTypes: "*", dateQuery: { before: "2024-01-01" } }) {
    id
    title
  }
  mediaItemsByExcludeIDs: mediaItems(filter: { excludeIDs: [1361], mimeTypes: "*", dateQuery: { before: "2024-01-01" } }) {
    id
    title
  }
  mediaItemsByIds: mediaItems(filter: { ids: [1361, 1363], mimeTypes: "*" }) {
    id
    title
  }
  mediaItemsByMimeTypes: mediaItems(filter: { mimeTypes: ["text/"] }, pagination: { limit: 3 }, sort: { by: ID, order: ASC }) {
    id
    title
  }
  mediaItemsBySearch: mediaItems(filter: { search: "graphql", mimeTypes: "*" }) {
    id
    title
  }

  mediaItemsSortedASC: mediaItems(pagination: { limit: 3 }, sort: { by: DATE, order: ASC }) {
    id
    title
    date
  }
  mediaItemsSortedDESC: mediaItems(pagination: { limit: 3 }, sort: { by: DATE, order: DESC }, filter: { dateQuery: { before: "2024-01-01" } }) {
    id
    title
    date
  }

  mediaItemById: mediaItem(by: { id: 1361 }) {
    id
    title
    slug
  }
  mediaItemBySlug: mediaItem(by: { slug: "graphql-api-search-results" }) {
    id
    title
    slug
  }
  nonExistingMediaItemById: mediaItem(by: { id: 88888 }) {
    id
    title
    slug
  }
  nonExistingMediaItemBySlug: mediaItem(by: { slug: "non-existing" }) {
    id
    title
    slug
  }
}

fragment MediaItemData on Media {
  altText
  author {
    id
    name
  } 
  caption
  date
  dateStr(format: "F j")
  description
  height
  id
  mimeType
  # modifiedDate
  # modifiedDateStr
  sizes
  slug
  src
  srcSet
  title
  url
  urlPath
  width
}