query {
  menus {
    ...MenuData
  }

  menuBySlug: menu(by: {slug: "top-menu"}) {
    ...MenuData
  }

  # id 55 => "Bottom menu" in the initial dataset
  menuByID: menu(by: {id: 55}) {
    ...MenuData
  }
}

fragment MenuData on Menu {
  id
  name
  slug
  count
  locations
  itemDataEntries
  flatItemDataEntries: itemDataEntries(flat: true)
  items {
    ...MenuItemData
    children {
      ...MenuItemData
      children {
        ...MenuItemData
        children {
          ...MenuItemData
        }
      }
    }
  }
}

fragment MenuItemData on MenuItem {
  id
  localURLPath
  label
  title
  rawTitle
  url
  classes
  target
  description
  objectID
  parentID
  linkRelationship
}
