query {
  menus {
    ...MenuData
  }

  menuBySlug: menu(by: {slug: "top-menu"}) {
    ...MenuData
  }

  # id 47 => "Bottom menu" in the initial dataset
  menuByID: menu(by: {id: 47}) {
    ...MenuData
  }
}

fragment MenuData on Menu {
  id
  name
  slug
  count
  locations
  itemDataEntries
  flatItemDataEntries: itemDataEntries(flat: true)
  itemDataEntriesByInclude: itemDataEntries(propertiesBy: {include: ["label", "title", "rawTitle", "url", "cssClasses", "target", "description", "linkRelationship"]})
  itemDataEntriesByExclude: itemDataEntries(propertiesBy: {exclude: ["label", "title", "rawTitle", "url", "cssClasses", "target", "description", "linkRelationship"]})
  flatItemDataEntriesByInclude: itemDataEntries(flat: true, propertiesBy: {include: ["label", "title", "rawTitle", "url", "cssClasses", "target", "description", "linkRelationship"]})
  flatItemDataEntriesByExclude: itemDataEntries(flat: true, propertiesBy: {exclude: ["label", "title", "rawTitle", "url", "cssClasses", "target", "description", "linkRelationship"]})
  items {
    ...MenuItemData
    children {
      ...MenuItemData
      children {
        ...MenuItemData
        children {
          ...MenuItemData
        }
      }
    }
  }
}

fragment MenuItemData on MenuItem {
  id
  itemType
  objectType
  objectID
  parentID
  localURLPath
  label
  rawLabel
  titleAttribute
  url
  cssClasses
  target
  description
  linkRelationship
}
