query {
  pages(pagination: { limit: 3 }, sort: { by: ID, order: ASC }) {
    areCommentsOpen
    author {
      id
      name
    }
    children {
      id
      title
    }
    childCount
    commentCount
    comments {
      id
    }
    content
    customPostType
    date
    dateStr
    excerpt
    featuredImage {
      id
      src
    }
    hasComments
    hasFeaturedImage
    id
    isStatus(status: pending)
    menuOrder
    metaValue(key: "_thumbnail_id")
    # These ones produce the value of data being inserted to DB, so can't save fixed value for testing
    # modifiedDate
    # modifiedDateStr(format: "m-d")
    parent {
      id
      title
    }
    rawContent
    rawTitle
    rawExcerpt
    slug
    status
    title
    url
    urlPath
  }

  pagesByAuthorIDs: pages(filter: { author: { ids: 2 } }) {
    id
    title
  }
  pagesByAuthorSlug: pages(filter: { author: { slug: "blogger" } }) {
    id
    title
  }
  pagesByDateQuery: pages(filter: { dateQuery: { before: "2020-04-20" } }) {
    id
    title
  }
  pagesByExcludeAuthorIDs: pages(filter: { author: { excludeIDs: 2 } }) {
    id
    title
  }
  pagesByExcludeIDs: pages(filter: { excludeIDs: [2, 3] }) {
    id
    title
  }
  pagesByHasPassword: pages(filter: { hasPassword: true }) {
    id
    title
  }
  emptyPagesByIds: pages(filter: { ids: [], status: [publish, draft] }) {
    id
    title
  }
  pagesByIds: pages(filter: { ids: [2, 3], status: [publish, draft] }) {
    id
    title
  }
  pagesByMetaQuery: pages(filter: { metaQuery: { key: "_thumbnail_id", compareBy: { key: { operator: NOT_EXISTS } } } }) {
    id
    title
  }
  pagesByParentID: pages(filter: { parentID: 2 }) {
    id
    title
  }
  pagesByParentIDs: pages(filter: { parentIDs: 2 }) {
    id
    title
  }
  pagesByPassword: pages(filter: { password: "password" }) {
    id
    title
  }
  pagesBySearch: pages(filter: { search: "sample" }) {
    id
    title
  }
  pagesByStatus: pages(filter: { status: draft }) {
    id
    title
  }

  pagesSortedASC: pages(filter: { status: [publish, draft] }, sort: { by: TITLE, order: ASC}) {
    id
    title
  }
  pagesSortedDESC: pages(filter: { status: [publish, draft] }, sort: { by: TITLE, order: DESC}) {
    id
    title
  }
}
