{
  postTags {
    ...PostTagData
  }

  postTagsWithTaxonomy: postTags(taxonomy: post_tag) {
    ...PostTagData
  }

  additionalPostTags: postTags(taxonomy: "additional-post-tag") {
    ...PostTagData
  }

  allPostTags: postTags(taxonomy: null) {
    ...PostTagData
  }

  nonEmptyPostTags: postTags(filter: {hideEmpty: true}) {
    id
    name
  }

  post(by:{ id: 1125 }) {
    tags {
      ...PostTagData
    }
    additionalTags: tags(taxonomy: "additional-post-tag") {
      ...PostTagData
    }
    allTags: tags(taxonomy: null) {
      ...PostTagData
    }
    tagsByExcludeIDs: tags(filter: { excludeIDs: [5] }) {
      id
    }
    emptyTagsByIds: tags(filter: { ids: [] }) {
      id
    }
    tagsByIds: tags(filter: { ids: [5] }) {
      id
    }
    tagsByMetaQuery: tags(filter: { metaQuery: {
      key: "someMetaKeyThatDoesntExist",
      compareBy:{
        key: {
          operator: NOT_EXISTS
        }
      }
    } }) {
      id
    }
    tagsBySearch: tags(filter: { search: "secur" }) {
      id
    }
    tagsBySlugs: tags(filter: { slugs: ["features", "non-existing"] }) {
      id
    }
    
    tagsBySortASC: tags(sort: { by: NAME, order: ASC }) {
      id
      name
    }
    tagsBySortDESC: tags(sort: { by: NAME, order: DESC }) {
      id
      name
    }
  }

  postsByTagIDs: posts(
    filter: { tags: { includeBy: { ids: [15, 14] } } }
  ) {
    id
    title
    tags {
      id
    }
  }

  postsByTagIDsWithTaxonomy: posts(
    filter: {
      tags: { includeBy: { ids: [15, 14] }, taxonomy: post_tag }
    }
  ) {
    id
    title
    tags {
      id
    }
  }

  postsExcludeByTagIDs: posts(
    filter: { tags: { excludeBy: { ids: [15, 14] } } }
  ) {
    id
    title
    tags {
      id
    }
  }

  postsByTagSlugs: posts(
    filter: { tags: { includeBy: { slugs: ["release", "plugin"] } } }
  ) {
    id
    title
    tags {
      slug
    }
  }

  postsByTagSlugsWithTaxonomy: posts(
    filter: {
      tags: { includeBy: { slugs: ["release", "plugin"] }, taxonomy: post_tag }
    }
  ) {
    id
    title
    tags {
      slug
    }
  }

  postsExcludeByTagSlugs: posts(
    filter: { tags: { excludeBy: { slugs: ["release", "plugin"] } } }
  ) {
    id
    title
    tags {
      slug
    }
  }

  postsByTagByID: postTag(by: { id: 15 }) {
    ...PostTagData
  }
  postsByTagBySlug: postTag(by: { slug: "wordpress" }) {
    ...PostTagData
  }
  
  postTagCount
  postTagNames
  
  allPostTagCount: postTagCount(taxonomy: null)
  allPostTagNames: postTagNames(taxonomy: null)

  postsByTagByNonExistingID: postTag(by: { id: 8888 }) {
    ...PostTagData
  }
  postsByTagByNonExistingSlug: postTag(by: { slug: "non-existing" }) {
    ...PostTagData
  }

  postsByTagByDifferentTaxonomyID: postTag(by: { id: 25 }) {
    ...PostTagData
  }
  postsByTagByDifferentTaxonomySlug: postTag(by: { slug: "classical" }) {
    ...PostTagData
  }
}

fragment PostTagData on PostTag {
  taxonomy
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  postCount
  posts {
    id
    title
  }
  postCountWithoutTaxonomy: postCount(filter: { taxonomy: null })
  postsWithoutTaxonomy: posts(filter: { taxonomy: null }) {
    id
    title
  }
  slug
  url
  urlPath
}