query {
  posts(pagination: { limit: 3 }, sort: { by: ID, order: ASC }) {
    areCommentsOpen
    author {
      id
      name
    }
    categories {
      id
      name
    }
    categoryCount
    categoryNames
    commentCount
    comments {
      id
    }
    content
    customPostType
    date
    dateStr
    wpAdminEditURL
    excerpt
    featuredImage {
      id
      src
    }
    hasComments
    hasFeaturedImage
    id
    isStatus(status: pending)
    isSticky
    metaValue(key: "_thumbnail_id")
    # These ones produce the value of data being inserted to DB, so can't save fixed value for testing
    # modifiedDate
    # modifiedDateStr(format: "m-d")
    postFormat
    rawContent
    rawTitle
    rawExcerpt
    slug
    status
    tagCount
    tagNames
    tags {
      id
      name
    }
    title
    url
    urlPath
  }

  postsByAuthorIDs: posts(filter: { author: { ids: 5 } }) {
    id
    title
  }
  postsByAuthorSlug: posts(filter: { author: { slug: "blogger" } }) {
    id
    title
  }
  postsByCategoryIDs: posts(filter: { categories: { includeBy: { ids: [1] } } }) {
    id
    title
  }
  postsByDateQuery: posts(filter: { dateQuery: { before: "2020-04-20" } }) {
    id
    title
  }
  postsByExcludeAuthorIDs: posts(filter: { author: { excludeIDs: 5 } }) {
    id
    title
  }
  postsByExcludeIDs: posts(filter: { excludeIDs: [1, 1128] }) {
    id
    title
  }
  postsByHasPassword: posts(filter: { hasPassword: true }) {
    id
    title
  }
  postsByIds: posts(filter: { ids: [1, 1128] }) {
    id
    title
  }
  postsByIsSticky: posts(filter: { isSticky: true }) {
    id
    title
  }
  postsByMetaQuery: posts(filter: { metaQuery: { key: "_thumbnail_id", compareBy: { key: { operator: EXISTS } } } }) {
    id
    title
  }
  postsByPassword: posts(filter: { password: "password" }) {
    id
    title
  }
  postsBySearch: posts(filter: { search: "hello" }) {
    id
    title
  }
  postsByStatus: posts(filter: { status: draft }) {
    id
    title
  }
  postsByTagIDs: posts(filter: { tags: { includeBy: { ids: [8, 9] } } }) {
    id
    title
  }
  postsByTagSlugs: posts(filter: { tags: { includeBy: { slugs: ["plugin", "release"] } } }) {
    id
    title
  }

  postsSortedASC: posts(pagination: { limit: 3 }, sort: { by: TITLE, order: ASC}) {
    id
    title
  }
  postsSortedDESC: posts(pagination: { limit: 3 }, sort: { by: TITLE, order: DESC}) {
    id
    title
  }
}
