{
  postCategories {
    ...PostCategoryData
    children {
      ...PostCategoryData
    }
  }

  postCategoriesWithTaxonomy: postCategories(taxonomy: category) {
    ...PostCategoryData
    children {
      ...PostCategoryData
    }
  }

  additionalPostCategories: postCategories(taxonomy: "additional-post-category") {
    ...PostCategoryData
    children {
      ...PostCategoryData
      additionalPostCount: postCount(filter: { categories: { taxonomy: "additional-post-category" } })
      additionalPosts: posts(filter: { categories: { taxonomy: "additional-post-category" } }) {
        id
        title
      }
    }
    additionalPostCount: postCount(filter: { categories: { taxonomy: "additional-post-category" } })
    additionalPosts: posts(filter: { categories: { taxonomy: "additional-post-category" } }) {
      id
      title
    }
  }

  allPostCategories: postCategories(taxonomy: null) {
    ...PostCategoryData
    children {
      ...PostCategoryData
    }
  }

  nonEmptyPostCategories: postCategories(filter: {hideEmpty: true}) {
    id
    name
  }

  post(by:{ id: 1125 }) {
    categories {
      ...PostCategoryData
      children {
        ...PostCategoryData
      }
    }
    additionalCategories: categories(taxonomy: "additional-post-category") {
      ...PostCategoryData
      children {
        ...PostCategoryData
      }
    }
    allCategories: categories(taxonomy: null) {
      ...PostCategoryData
      children {
        ...PostCategoryData
      }
    }
    categoriesByExcludeIDs: categories(filter: { excludeIDs: [2] }) {
      id
    }
    emptyCategoriesByIds: categories(filter: { ids: [] }) {
      id
    }
    categoriesByIds: categories(filter: { ids: [2] }) {
      id
    }
    categoriesByMetaQuery: categories(filter: { metaQuery: {
      key: "someMetaKeyThatDoesntExist",
      compareBy:{
        key: {
          operator: NOT_EXISTS
        }
      }
    } }) {
      id
    }
    categoriesByParentID: categories(filter: { parentID: 3 }) {
      id
    }
    categoriesBySearch: categories(filter: { search: "blo" }) {
      id
    }
    categoriesBySlugs: categories(filter: { slugs: ["advanced", "non-existing"] }) {
      id
    }
    
    categoriesBySortASC: categories(sort: { by: NAME, order: ASC }) {
      id
      name
    }
    categoriesBySortDESC: categories(sort: { by: NAME, order: DESC }) {
      id
      name
    }
  }

  postsByCategoryIDs: posts(
    filter: { categories: { includeBy: { ids: [1, 4] } } }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsByCategoryIDsWithTaxonomy: posts(
    filter: {
      categories: { includeBy: { ids: [1, 4] }, taxonomy: category }
    }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsExcludeByCategoryIDs: posts(
    filter: { categories: { excludeBy: { ids: [1, 4] } } }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsByCategorySlugs: posts(
    filter: { categories: { includeBy: { slugs: ["resource"] } } }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsByCategorySlugsWithTaxonomy: posts(
    filter: {
      categories: { includeBy: { slugs: ["resource"] }, taxonomy: category }
    }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsExcludeByCategorySlugs: posts(
    filter: { categories: { excludeBy: { slugs: ["resource"] } } }
  ) {
    id
    title
    categories {
      id
    }
  }

  postsByCategoryByID: postCategory(by: { id: 1 }) {
    ...PostCategoryData
  }
  postsByCategoryBySlug: postCategory(by: { slug: "resource" }) {
    ...PostCategoryData
  }
  
  postCategoryCount
  postCategoryNames
  
  allPostCategoryCount: postCategoryCount(taxonomy: null)
  allPostCategoryNames: postCategoryNames(taxonomy: null)

  postsByCategoryByNonExistingID: postCategory(by: { id: 8888 }) {
    ...PostCategoryData
  }
  postsByCategoryByNonExistingSlug: postCategory(by: { slug: "non-existing" }) {
    ...PostCategoryData
  }

  postsByCategoryByDifferentTaxonomyID: postCategory(by: { id: 19 }) {
    ...PostCategoryData
  }
  postsByCategoryByDifferentTaxonomySlug: postCategory(by: { slug: "absolute-brilliance" }) {
    ...PostCategoryData
  }
}

fragment PostCategoryData on PostCategory {
  taxonomy
  childCount
  childNames
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  parent {
    id
  }
  postCount
  posts {
    id
    title
  }
  slug
  url
  urlPath
}