{
  optionValue(name: "siteurl")
  isGutenbergEditorEnabled
  isGutenbergEditorEnabledForPost: useGutenbergEditorWithCustomPostType(customPostType: "post")
  isGutenbergEditorEnabledForDummyCPT: useGutenbergEditorWithCustomPostType(customPostType: "dummy-cpt")
  # isGutenbergEditorEnabledForEvent: useGutenbergEditorWithCustomPostType(customPostType: "event")
}
