{
  existingValue: optionValue(name: "siteurl")
  nonExistingValue: optionValue(name: "nonExisting")
  existingArray: optionValues(name: "active_plugins")
  nonExistingArray: optionValues(name: "nonExisting")
  existingObject: optionObjectValue(name: "wp_user_roles")
  nonExistingObject: optionObjectValue(name: "nonExisting")
  isGutenbergEditorEnabled
  isGutenbergEditorEnabledForPost: isGutenbergEditorEnabledForCustomPostType(customPostType: "post")
  isGutenbergEditorEnabledForDummyCPT: isGutenbergEditorEnabledForCustomPostType(customPostType: "dummy-cpt")
  isGutenbergEditorEnabledForEvent: isGutenbergEditorEnabledForCustomPostType(customPostType: "event")
}