{
  existingValue: optionValue(name: "siteurl")
  nonExistingValue: optionValue(name: "nonExisting")
  existingArray: optionValues(name: "active_plugins")
  nonExistingArray: optionValues(name: "nonExisting")
  existingObject: optionObjectValue(name: "wp_user_roles")
  nonExistingObject: optionObjectValue(name: "nonExisting")
  existingObjects: optionObjectValues(name: "list_of_objects")
  nonExistingObjects: optionObjectValues(name: "nonExisting")
  valueWithQuotes: optionValue(name: "value_with_quotes")
  arrayWithQuotes: optionValues(name: "list_of_values_with_quotes")
  objectWithQuotes: optionObjectValue(name: "object_with_quotes")
  isGutenbergEditorEnabled
  isGutenbergEditorEnabledForPost: useGutenbergEditorWithCustomPostType(customPostType: "post")
  isGutenbergEditorEnabledForDummyCPT: useGutenbergEditorWithCustomPostType(customPostType: "dummy-cpt")
  # isGutenbergEditorEnabledForEvent: useGutenbergEditorWithCustomPostType(customPostType: "event")
}