{
  tags(
    taxonomy: "dummy-tag"
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...GenericTagData
    ...TagData
  }

  tagsWithoutTaxonomy: tags(
    sort: { by: ID, order: ASC }
    pagination: { limit: 20 }
  ) {
    __typename
    ...PostTagData
    ...GenericTagData
    ...TagData
  }
  
  customPosts(
    filter: {
      customPostTypes: ["post","dummy-cpt"]
    }
    pagination: { limit: 30 }
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on CustomPost {
      id
      title
      customPostType
    }
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        __typename
        id
        name
        taxonomy
      }
      tagsWithoutTaxonomy: tags(
        sort: { by: ID, order: ASC }
      ) {
        __typename
        id
        name
        taxonomy
      }
    }
    ...on Post {
      tags {
        __typename
        id
        name
        taxonomy
      }
    }
  }

  customPostsByTagIDs: customPosts(
    filter: {
      tags: {
        includeBy: {
          ids: [25, 29]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsExcludeByTagIDs: customPosts(
    filter: {
      tags: {
        excludeBy: {
          ids: [25, 29]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsByTagSlugs: customPosts(
    filter: {
      tags: {
        includeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }

  customPostsExcludeByTagSlugs: customPosts(
    filter: {
      tags: {
        excludeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }

  customPostsExcludeByTagSlugsOnCPT: customPosts(
    filter: {
      customPostTypes: "dummy-cpt"
      tags: {
        excludeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }

  postTagCount: tagCount(taxonomy: post_tag)
  postTagNames: tagNames(taxonomy: post_tag)

  dummyTagCount: tagCount(taxonomy: "dummy-tag")
  dummyTagNames: tagNames(taxonomy: "dummy-tag")

  allTagCount: tagCount
  allTagNames: tagNames
}

fragment TagData on Tag {
  taxonomy
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  url
  urlPath
}

fragment GenericTagData on GenericTag {
  customPostCount
  customPosts(sort: { by: ID, order: ASC }) {
    __typename
    ...CustomPostData
  }
}

fragment PostTagData on PostTag {
  postCount
  posts(sort: { by: ID, order: ASC }) {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on CustomPost {
  id
  title
  tags(
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on Tag {
      id
      name
      taxonomy
    }
  }
}