{
  customPostsByIDs: customPosts(
    filter: {
      tags: {
        includeBy: {
          ids: [25, 29]
        }
        taxonomy: "dummy-tag"
      }
      categories: {
        includeBy: {
          ids: [32, 37]
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(taxonomy: "dummy-tag") {
        id
      }
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }

  customPostsBySlugAndIDs: customPosts(
    filter: {
      tags: {
        includeBy: {
          slugs: "rock"
        }
        taxonomy: "dummy-tag"
      }
      categories: {
        includeBy: {
          ids: [32, 36]
        }
        excludeBy: {
          slugs: "world-cup"
        }
        taxonomy: "dummy-category"
      }
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(taxonomy: "dummy-tag") {
        slug
      }
      categories(taxonomy: "dummy-category") {
        id
      }
    }
  }
}