{
  tags(
    taxonomy: "dummy-tag"
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...GenericTagData
    ...TagData
  }
  
  customPosts(
    filter: {
      customPostTypes: ["post","dummy-cpt"]
    }
    pagination: {
      limit: 30
    }
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on CustomPost {
      id
      title
      customPostType
    }
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        __typename
        id
        name
        taxonomy
      }
    }
    ...on Post {
      tags {
        __typename
        id
        name
      }
    }
  }

  customPostsByTagIDs: customPosts(
    filter: {
      tags: {
        includeBy: {
          ids: [25, 29]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsExcludeByTagIDs: customPosts(
    filter: {
      tags: {
        excludeBy: {
          ids: [25, 29]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        id
      }
    }
  }

  customPostsByTagSlugs: customPosts(
    filter: {
      tags: {
        includeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }

  customPostsExcludeByTagSlugs: customPosts(
    filter: {
      tags: {
        excludeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }

  customPostsExcludeByTagSlugsOnCPT: customPosts(
    filter: {
      customPostTypes: "dummy-cpt"
      tags: {
        excludeBy: {
          slugs: ["tango", "rock"]
        }
        taxonomy: "dummy-tag"
      }
    }
    pagination: {
      limit: 20
    },
    sort: {
      by: ID,
      order: ASC
    }
  ) {
    id
    title
    ...on GenericCustomPost {
      tags(
        taxonomy: "dummy-tag"
        sort: { by: ID, order: ASC }
      ) {
        slug
      }
    }
  }
}

fragment TagData on Tag {
  taxonomy
  count
  description
  id
  metaValue(key: "not-existing")
  metaValues(key: "also-not-existing")
  name
  slug
  url
  urlPath
}

fragment GenericTagData on GenericTag {
  taxonomy   
  customPostCount
  customPosts(sort: { by: ID, order: ASC }) {
    __typename
    ...CustomPostData
  }
}

fragment CustomPostData on CustomPost {
  id
  title
  tags(
    taxonomy: "dummy-tag"
    sort: { by: ID, order: ASC }
  ) {
    __typename
    ...on Tag {
      id
      name
    }
  }
}