<?php

declare(strict_types=1);

namespace PoPSchema\Comments;

class Environment
{
    public const ROOT_COMMENT_LIST_DEFAULT_LIMIT = 'ROOT_COMMENT_LIST_DEFAULT_LIMIT';
    public const CUSTOMPOST_COMMENT_OR_COMMENT_RESPONSE_LIST_DEFAULT_LIMIT = 'CUSTOMPOST_COMMENT_OR_COMMENT_RESPONSE_LIST_DEFAULT_LIMIT';
    public const COMMENT_LIST_MAX_LIMIT = 'COMMENT_LIST_MAX_LIMIT';
    public const MUST_USER_BE_LOGGED_IN_TO_ADD_COMMENT = 'MUST_USER_BE_LOGGED_IN_TO_ADD_COMMENT';
}
