<?php

// Gravity Forms Field Ids
//--------------------------------------------------------
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FORM_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_NAME_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_EMAIL_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PHONE_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_WHYVOLUNTEER_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PAGEURL_ID', false);
define('POP_GENERICFORMS_GF_FORM_VOLUNTEER_FIELDNAME_PAGETITLE_ID', false);
