<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

class PoPTheme_Wassup_SectionProcessors_Template_SettingsProcessor extends GD_Template_SettingsProcessorBase {

	function get_checkpoints($hierarchy) {

		$ret = array();

		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE) {

			return array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECT => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECTLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENT => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENTLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSION => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSIONLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORY => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORYLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDFEATURED => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),

				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
				
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECT => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECTLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORY => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORYLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENT => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENTLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSION => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSIONLINK => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITFEATURED => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
			);
		}
	
		return parent::get_checkpoints($hierarchy);
	}

	function get_page_blockgroups($hierarchy, $include_common = true) {

		$ret = array();

		// Page or Blocks inserted in Home
		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE || $hierarchy == GD_SETTINGS_HIERARCHY_HOME) {

			$pageblockgroups = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_PROJECTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_STORIES,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_ANNOUNCEMENTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_DISCUSSIONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED => GD_TEMPLATE_BLOCKGROUP_TABPANEL_FEATURED,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG => GD_TEMPLATE_BLOCKGROUP_TABPANEL_BLOG,

				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYPROJECTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYSTORIES,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYANNOUNCEMENTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYDISCUSSIONS,

				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_WHOWEARE => GD_TEMPLATE_BLOCKGROUP_WHOWEARE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSPONSORS => GD_TEMPLATE_BLOCKGROUP_OURSPONSORS,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		// Author page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_AUTHOR) {

			$pageblockgroups = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORPROJECTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORSTORIES,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORANNOUNCEMENTS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHORDISCUSSIONS,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		return $ret;
	}

	function get_page_blocks($hierarchy, $include_common = true) {

		$ret = array();

		// $include_common: used to tell if we include also the common blocks in the response.
		// These common blocks are needed to produce the dataload-source of, eg, the Navigator Blocks, even
		// when first loading the website on an Author or Single page. Without the Navigator blocks placed in
		// common, then we can't get their dataload-source.
		// However, when generating the cache (file generator.php) these are not needed, so then skip them
		// Common blocks
		if ($include_common) {

			// Default
			$pageblocks_allothers = array(

				// Add Content
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECT => GD_TEMPLATE_BLOCK_PROJECT_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECTLINK => GD_TEMPLATE_BLOCK_PROJECTLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORY => GD_TEMPLATE_BLOCK_STORY_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORYLINK => GD_TEMPLATE_BLOCK_STORYLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENT => GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENTLINK => GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSION => GD_TEMPLATE_BLOCK_DISCUSSION_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSIONLINK => GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDFEATURED => GD_TEMPLATE_BLOCK_FEATURED_CREATE,
				
				// My Content
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECT => GD_TEMPLATE_BLOCK_PROJECT_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECTLINK => GD_TEMPLATE_BLOCK_PROJECTLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORY => GD_TEMPLATE_BLOCK_STORY_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORYLINK => GD_TEMPLATE_BLOCK_STORYLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENT => GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENTLINK => GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSION => GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSIONLINK => GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITFEATURED => GD_TEMPLATE_BLOCK_FEATURED_UPDATE,

				// About
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_HOWTOUSEWEBSITE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_CONTENTGUIDELINES => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURMISSION => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSTORY => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_VOLUNTEERWITHUS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_SPONSORUS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_INTHEMEDIA => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT => GD_TEMPLATE_BLOCK_MENU_BODY_ABOUT,
			
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_THOUGHTS  => GD_TEMPLATE_BLOCK_THOUGHTS_SCROLL,
			);
			foreach ($pageblocks_allothers as $page => $block) {
				$ret[$page]['blocks']['default'] = $block;
			}

			// Actions 
			$pageactions = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECT => GD_TEMPLATE_ACTION_PROJECT_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDPROJECTLINK => GD_TEMPLATE_ACTION_PROJECTLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECT => GD_TEMPLATE_ACTION_PROJECT_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITPROJECTLINK => GD_TEMPLATE_ACTION_PROJECTLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORY => GD_TEMPLATE_ACTION_STORY_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORYLINK => GD_TEMPLATE_ACTION_STORYLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORY => GD_TEMPLATE_ACTION_STORY_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORYLINK => GD_TEMPLATE_ACTION_STORYLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENT => GD_TEMPLATE_ACTION_ANNOUNCEMENT_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENTLINK => GD_TEMPLATE_ACTION_ANNOUNCEMENTLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENT => GD_TEMPLATE_ACTION_ANNOUNCEMENT_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENTLINK => GD_TEMPLATE_ACTION_ANNOUNCEMENTLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSION => GD_TEMPLATE_ACTION_DISCUSSION_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSIONLINK => GD_TEMPLATE_ACTION_DISCUSSIONLINK_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSION => GD_TEMPLATE_ACTION_DISCUSSION_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSIONLINK => GD_TEMPLATE_ACTION_DISCUSSIONLINK_UPDATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDFEATURED => GD_TEMPLATE_ACTION_FEATURED_CREATE,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITFEATURED => GD_TEMPLATE_ACTION_FEATURED_UPDATE,
			);
			foreach ($pageactions as $page => $action) {
				$ret[$page]['action'] = $action;
			}
		}

		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE || $hierarchy == GD_SETTINGS_HIERARCHY_HOME) {

			$default_format_section = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_SCREEN_SECTION);
			$default_format_mycontent = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_SCREEN_MYCONTENT);
			
			$pageblocks_typeahead = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_TYPEAHEAD,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_TYPEAHEAD,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_TYPEAHEAD,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_TYPEAHEAD,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_TYPEAHEAD,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_TYPEAHEAD,
			);
			foreach ($pageblocks_typeahead as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_TYPEAHEAD] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_TYPEAHEAD) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}

			// Navigator
			$pageblocks_navigator = array(						
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_NAVIGATOR,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_NAVIGATOR,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_NAVIGATOR,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_NAVIGATOR,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_NAVIGATOR,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_NAVIGATOR,
			);
			foreach ($pageblocks_navigator as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_NAVIGATOR] = $block;
			}

			// Addons
			$pageblocks_addons = array(						
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_ADDONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_ADDONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_ADDONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_ADDONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_ADDONS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_ADDONS,
			);
			foreach ($pageblocks_addons as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_ADDONS] = $block;
			}

			$pageblocks_details = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_DETAILS,
			);
			foreach ($pageblocks_details as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_DETAILS] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_DETAILS) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_simpleview = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_SIMPLEVIEW,
			);
			foreach ($pageblocks_simpleview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_SIMPLEVIEW] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_SIMPLEVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_fullview = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_FULLVIEW,
			);
			foreach ($pageblocks_fullview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_thumbnail = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_THUMBNAIL,
			);
			foreach ($pageblocks_thumbnail as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_THUMBNAIL] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_THUMBNAIL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_list = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_STORIES_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_DISCUSSIONS_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_ANNOUNCEMENTS_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG  => GD_TEMPLATE_BLOCK_BLOG_SCROLL_LIST,
			);
			foreach ($pageblocks_list as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_LIST] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_LIST) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_carousels = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED  => GD_TEMPLATE_BLOCK_FEATURED_CAROUSEL,
			);
			foreach ($pageblocks_carousels as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_CAROUSEL] = $block;

				if ($default_format_section == GD_TEMPLATEFORMAT_CAROUSEL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			// $pageblocks_map = array(
			// 	POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_PROJECTS_SCROLLMAP,
			// );
			// foreach ($pageblocks_map as $page => $block) {
			// 	$ret[$page]['blocks'][GD_TEMPLATEFORMAT_MAP] = $block;
			// }
			$pageblocks_mycontent = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS => GD_TEMPLATE_BLOCK_MYPROJECTS_TABLE_EDIT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES => GD_TEMPLATE_BLOCK_MYSTORIES_TABLE_EDIT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS => GD_TEMPLATE_BLOCK_MYANNOUNCEMENTS_TABLE_EDIT,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS => GD_TEMPLATE_BLOCK_MYDISCUSSIONS_TABLE_EDIT,
			);
			foreach ($pageblocks_mycontent as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_TABLE] = $block;

				if ($default_format_mycontent == GD_TEMPLATEFORMAT_TABLE) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_mycontent_simpleviewpreviews = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS => GD_TEMPLATE_BLOCK_MYPROJECTS_SCROLL_SIMPLEVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES => GD_TEMPLATE_BLOCK_MYSTORIES_SCROLL_SIMPLEVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS => GD_TEMPLATE_BLOCK_MYANNOUNCEMENTS_SCROLL_SIMPLEVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS => GD_TEMPLATE_BLOCK_MYDISCUSSIONS_SCROLL_SIMPLEVIEWPREVIEW,
			);
			foreach ($pageblocks_mycontent_simpleviewpreviews as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_SIMPLEVIEW] = $block;

				if ($default_format_mycontent == GD_TEMPLATEFORMAT_SIMPLEVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_mycontent_fullviewpreviews = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYPROJECTS => GD_TEMPLATE_BLOCK_MYPROJECTS_SCROLL_FULLVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES => GD_TEMPLATE_BLOCK_MYSTORIES_SCROLL_FULLVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS => GD_TEMPLATE_BLOCK_MYANNOUNCEMENTS_SCROLL_FULLVIEWPREVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS => GD_TEMPLATE_BLOCK_MYDISCUSSIONS_SCROLL_FULLVIEWPREVIEW,
			);
			foreach ($pageblocks_mycontent_fullviewpreviews as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_mycontent == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
		}

		// Author page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_AUTHOR) {

			$default_format_authorsection = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_SCREEN_AUTHORSECTION);
			
			$pageblocks_details = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SCROLL_DETAILS,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SCROLL_DETAILS,
			);
			foreach ($pageblocks_details as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_DETAILS] = $block;

				if ($default_format_authorsection == GD_TEMPLATEFORMAT_DETAILS) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_simpleview = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SCROLL_SIMPLEVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SCROLL_SIMPLEVIEW,
			);
			foreach ($pageblocks_simpleview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_SIMPLEVIEW] = $block;

				if ($default_format_authorsection == GD_TEMPLATEFORMAT_SIMPLEVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_fullview = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SCROLL_FULLVIEW,
			);
			foreach ($pageblocks_fullview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_authorsection == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_thumbnail = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SCROLL_THUMBNAIL,
			);
			foreach ($pageblocks_thumbnail as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_THUMBNAIL] = $block;

				if ($default_format_authorsection == GD_TEMPLATEFORMAT_THUMBNAIL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_list = array(
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES  => GD_TEMPLATE_BLOCK_AUTHORSTORIES_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS  => GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SCROLL_LIST,
				POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS  => GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SCROLL_LIST,
			);
			foreach ($pageblocks_list as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_LIST] = $block;

				if ($default_format_authorsection == GD_TEMPLATEFORMAT_LIST) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			// $pageblocks_map = array(
			// 	POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_PROJECTS  => GD_TEMPLATE_BLOCK_AUTHORPROJECTS_SCROLLMAP,
			// );
			// foreach ($pageblocks_map as $page => $block) {
			// 	$ret[$page]['blocks'][GD_TEMPLATEFORMAT_MAP] = $block;
			// }
		}

		// Allow Events Manager to inject the settings for the Map
		$ret = apply_filters('WassupProcessors_Template_SettingsProcessor:page_blocks', $ret, $hierarchy, $include_common);

		return $ret;	
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new PoPTheme_Wassup_SectionProcessors_Template_SettingsProcessor();
