<?php

declare(strict_types=1);

namespace PoPCMSSchema\CustomPosts;

class Environment
{
    public final const CUSTOMPOST_LIST_DEFAULT_LIMIT = 'CUSTOMPOST_LIST_DEFAULT_LIMIT';
    public final const CUSTOMPOST_LIST_MAX_LIMIT = 'CUSTOMPOST_LIST_MAX_LIMIT';
    public final const USE_SINGLE_TYPE_INSTEAD_OF_CUSTOMPOST_UNION_TYPE = 'USE_SINGLE_TYPE_INSTEAD_OF_CUSTOMPOST_UNION_TYPE';
    public final const TREAT_CUSTOMPOST_STATUS_AS_ADMIN_DATA = 'TREAT_CUSTOMPOST_STATUS_AS_ADMIN_DATA';
}
