<?php

declare(strict_types=1);

namespace PoPCMSSchema\CustomPosts;

class Environment
{
    public const CUSTOMPOST_LIST_DEFAULT_LIMIT = 'CUSTOMPOST_LIST_DEFAULT_LIMIT';
    public const CUSTOMPOST_LIST_MAX_LIMIT = 'CUSTOMPOST_LIST_MAX_LIMIT';
    public const USE_SINGLE_TYPE_INSTEAD_OF_CUSTOMPOST_UNION_TYPE = 'USE_SINGLE_TYPE_INSTEAD_OF_CUSTOMPOST_UNION_TYPE';
    public const TREAT_CUSTOMPOST_STATUS_AS_ADMIN_DATA = 'TREAT_CUSTOMPOST_STATUS_AS_ADMIN_DATA';
}
