<?php

declare(strict_types=1);

namespace PoPSchema\UserStateAccessControl\ConditionalOnComponent\CacheControl\RelationalTypeResolverDecorators;

use PoPSchema\UserStateAccessControl\RelationalTypeResolverDecorators\ValidateUserLoggedInForFieldsTypeResolverDecoratorTrait;
use PoPSchema\UserStateAccessControl\ConditionalOnComponent\CacheControl\RelationalTypeResolverDecorators\AbstractNoCacheConfigurableAccessControlForFieldsInPrivateSchemaTypeResolverDecorator;

class ValidateUserLoggedInForFieldsPrivateSchemaTypeResolverDecorator extends AbstractNoCacheConfigurableAccessControlForFieldsInPrivateSchemaTypeResolverDecorator
{
    use ValidateUserLoggedInForFieldsTypeResolverDecoratorTrait;
}
