<?php

// Categories
//--------------------------------------------------------
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS00', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS01', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS02', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS03', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS04', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS05', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS06', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS07', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS08', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS09', false);

define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS10', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS11', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS12', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS13', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS14', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS15', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS16', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS17', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS18', false);
define('POP_CATEGORYPOSTS_CAT_CATEGORYPOSTS19', false);
