<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCK_SECTION_ANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-announcements-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_BLOG_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-blog-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_DISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-discussions-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-featured-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_LOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-locationposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_STORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-stories-sidebar'));

define ('GD_TEMPLATE_BLOCK_SECTION_MYANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-myannouncements-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYDISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-mydiscussions-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYLOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-mylocationposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYSTORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-section-mystories-sidebar'));

define ('GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-tagsection-announcements-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-tagsection-discussions-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-tagsection-featured-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-tagsection-locationposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-tagsection-stories-sidebar'));

define ('GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-authorannouncements-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-authordiscussions-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-authorfeatured-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-authorlocationposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-authorstories-sidebar'));

define ('GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-announcement-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-blog-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-discussion-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-featured-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-locationpost-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR', PoP_TemplateIDUtils::get_template_definition('block-single-story-sidebar'));

class GD_Custom_Template_Processor_CustomSidebarBlocks extends GD_Template_Processor_CustomSidebarBlocksBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCK_SECTION_ANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_BLOG_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_DISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_LOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_STORIES_SIDEBAR,

			GD_TEMPLATE_BLOCK_SECTION_MYANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYDISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYLOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYSTORIES_SIDEBAR,

			GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR,

			GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR,	

			GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR,		
		);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_SECTION_ANNOUNCEMENTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_ANNOUNCEMENTS;

			case GD_TEMPLATE_BLOCK_SECTION_BLOG_SIDEBAR:

				return GD_TEMPLATE_FILTER_BLOG;

			case GD_TEMPLATE_BLOCK_SECTION_DISCUSSIONS_SIDEBAR:

				return GD_TEMPLATE_FILTER_DISCUSSIONS;

			case GD_TEMPLATE_BLOCK_SECTION_FEATURED_SIDEBAR:

				return GD_TEMPLATE_FILTER_FEATURED;

			case GD_TEMPLATE_BLOCK_SECTION_LOCATIONPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_LOCATIONPOSTS;

			case GD_TEMPLATE_BLOCK_SECTION_STORIES_SIDEBAR:

				return GD_TEMPLATE_FILTER_STORIES;

			case GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGANNOUNCEMENTS;

			case GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGDISCUSSIONS;

			case GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGFEATURED;

			case GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGLOCATIONPOSTS;

			case GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGSTORIES;

			case GD_TEMPLATE_BLOCK_SECTION_MYANNOUNCEMENTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYANNOUNCEMENTS;

			case GD_TEMPLATE_BLOCK_SECTION_MYDISCUSSIONS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYDISCUSSIONS;

			case GD_TEMPLATE_BLOCK_SECTION_MYLOCATIONPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYLOCATIONPOSTS;

			case GD_TEMPLATE_BLOCK_SECTION_MYSTORIES_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYSTORIES;

			case GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORANNOUNCEMENTS;

			case GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORDISCUSSIONS;

			case GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORFEATURED;

			case GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORLOCATIONPOSTS;

			case GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORSTORIES;

		}
		
		return parent::get_filter_template($template_id);
	}

	protected function get_block_inner_templates($template_id) {

		$ret = parent::get_block_inner_templates($template_id);

		$orientation = apply_filters(POP_HOOK_BLOCKSIDEBARS_ORIENTATION, 'vertical');
		$vertical = ($orientation == 'vertical');

		$block_inners = array(
			GD_TEMPLATE_BLOCK_SECTION_BLOG_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_BLOG,
			GD_TEMPLATE_BLOCK_SECTION_ANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_ANNOUNCEMENTS,
			GD_TEMPLATE_BLOCK_SECTION_DISCUSSIONS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_DISCUSSIONS,
			GD_TEMPLATE_BLOCK_SECTION_FEATURED_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_FEATURED,
			GD_TEMPLATE_BLOCK_SECTION_LOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_LOCATIONPOSTS,
			GD_TEMPLATE_BLOCK_SECTION_STORIES_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_STORIES,

			GD_TEMPLATE_BLOCK_SECTION_MYANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYANNOUNCEMENTS,
			GD_TEMPLATE_BLOCK_SECTION_MYDISCUSSIONS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYDISCUSSIONS,
			GD_TEMPLATE_BLOCK_SECTION_MYLOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYLOCATIONPOSTS,
			GD_TEMPLATE_BLOCK_SECTION_MYSTORIES_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYSTORIES,

			GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGANNOUNCEMENTS,
			GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGDISCUSSIONS,
			GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGFEATURED,
			GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGLOCATIONPOSTS,
			GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGSTORIES,

			GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORANNOUNCEMENTS,
			GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORDISCUSSIONS,
			GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORFEATURED,
			GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORLOCATIONPOSTS,
			GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORSTORIES,

			GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_ANNOUNCEMENT : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_ANNOUNCEMENT,
			GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_BLOG : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_BLOG,
			GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_DISCUSSION : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_DISCUSSION,
			GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_FEATURED : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_FEATURED,
			GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_LOCATIONPOST : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LOCATIONPOST,
			GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_STORY : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_STORY,
		);

		if ($block_inner = $block_inners[$template_id]) {

			$ret[] = $block_inner;
		}
	
		return $ret;
	}
	
	protected function get_block_hierarchy($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTHORANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_AUTHORDISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_AUTHORFEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCK_AUTHORLOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_AUTHORSTORIES_SIDEBAR:
				
				return GD_SETTINGS_HIERARCHY_AUTHOR;

			case GD_TEMPLATE_BLOCK_TAGSECTION_ANNOUNCEMENTS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_TAGSECTION_DISCUSSIONS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_TAGSECTION_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCK_TAGSECTION_LOCATIONPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_TAGSECTION_STORIES_SIDEBAR:
				
				return GD_SETTINGS_HIERARCHY_TAG;

			case GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR:

				return GD_SETTINGS_HIERARCHY_SINGLE;
		}
		
		return parent::get_block_hierarchy($template_id);
	}

	function get_dataloader($template_id) {

		switch ($template_id) {
					
			case GD_TEMPLATE_BLOCK_SINGLE_ANNOUNCEMENT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_BLOG_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_DISCUSSION_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_FEATURED_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_LOCATIONPOST_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_STORY_SIDEBAR:

				return GD_DATALOADER_SINGLE;
		}
		
		return parent::get_dataloader($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_CustomSidebarBlocks();