<?php

/**---------------------------------------------------------------------------------------------------------------
 *
 * IDs Configuration
 *
 * ---------------------------------------------------------------------------------------------------------------*/

// Placeholders for images
//--------------------------------------------------------
define ('POPTHEME_WASSUPHOSTS_THUMB_MESYM', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_TPPDEBATE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYSIAKINI', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYSIANINSIDER', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_MALAYMAILONLINE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_NST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THESTAR', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_BFM', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_CLEANMALAYSIA', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THIRDWORLDNETWORK', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_MITI', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_JANGANJUALNEGARA', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_FREEMALAYSIATODAY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_BERITADAILY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_SINCHEW', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEEDGEMARKETS', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEMALAYSIANRESERVE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_NANYANG', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEGUARDIAN', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_NYT', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_FB', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_TWITTER', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_LINKEDIN', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_WASHINGTONPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_FTAMALAYSIA', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THERAKYATPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEGLOBEANDMAIL', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_TODAYONLINE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_SEATTLETIMES', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_XINHUANET', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_TECHDIRT', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_EFF', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_ALIRAN', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_REUTERS', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_FOREIGNPOLICY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_BREITBART', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_INFOJUSTICE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_BERITAHARIAN', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_ASTROAWANI', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THANHNIENNEWS', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_POLITICO', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THESUNDAILY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_NZHERALD', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_WSJ', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEJAPANTIMES', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_JAPANTODAY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_MICHAELGEIST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_HUFFINGTONPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_COMMONDREAMS', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_FINANCIALPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_ALTERNET', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEJAKARTAPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_STUFF', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_WASHINGTONTIMES', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_CHICAGOTRIBUNE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_VARIETY', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_HUMANRIGHTSWATCH', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_KINITV', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_BLOOMBERGTYMALAYSIA', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THENATION', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_SOUTHCHINAMORNINGPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_RAPPLER', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_SINARHARIAN', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEBUREAUOFINVESTIGATIVEJOURNALISM', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THETYEE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_RABBLECA', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_ASETUFTSGDAE', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_THEBORNEOPOST', false);
define ('POPTHEME_WASSUPHOSTS_THUMB_RT', false);
