<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Sources
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATESOURCE_ALERT', 'alert');
define ('GD_TEMPLATESOURCE_BLOCK', 'block');
define ('GD_TEMPLATESOURCE_BLOCK_BARE', 'block-bare');
define ('GD_TEMPLATESOURCE_BLOCKGROUP_BLOCKUNITS', 'blockgroup-blockunits');
// define ('GD_TEMPLATESOURCE_BLOCKGROUP_CAROUSEL', 'blockgroup-carousel');
// define ('GD_TEMPLATESOURCE_BLOCKGROUP_COLLAPSEPANELGROUP', 'blockgroup-collapsepanelgroup');
// define ('GD_TEMPLATESOURCE_BLOCKGROUP_TABPANEL', 'blockgroup-tabpanel');
// define ('GD_TEMPLATESOURCE_BLOCKGROUP_VIEWCOMPONENT', 'blockgroup-viewcomponent');
define ('GD_TEMPLATESOURCE_BUTTONGROUP', 'buttongroup');
define ('GD_TEMPLATESOURCE_BUTTON', 'button');
define ('GD_TEMPLATESOURCE_BUTTONINNER', 'buttoninner');
define ('GD_TEMPLATESOURCE_CAROUSEL', 'carousel');
define ('GD_TEMPLATESOURCE_CAROUSEL_CONTROLS', 'carousel-controls');
define ('GD_TEMPLATESOURCE_CAROUSEL_INNER', 'carousel-inner');
define ('GD_TEMPLATESOURCE_CODE', 'code');
define ('GD_TEMPLATESOURCE_CONDITIONWRAPPER', 'conditionwrapper');
define ('GD_TEMPLATESOURCE_CONTENT', 'content');
define ('GD_TEMPLATESOURCE_CONTENTMULTIPLE_INNER', 'contentmultiple-inner');
define ('GD_TEMPLATESOURCE_CONTENTSINGLE_INNER', 'contentsingle-inner');
define ('GD_TEMPLATESOURCE_CONTROL_ANCHOR', 'anchor-control');
define ('GD_TEMPLATESOURCE_CONTROL_BUTTON', 'button-control');
define ('GD_TEMPLATESOURCE_CONTROL_DROPDOWNBUTTON', 'dropdownbutton-control');
define ('GD_TEMPLATESOURCE_CONTROL_RADIOBUTTON', 'radiobutton-control');
define ('GD_TEMPLATESOURCE_CONTROLBUTTONGROUP', 'controlbuttongroup');
define ('GD_TEMPLATESOURCE_CONTROLGROUP', 'controlgroup');
define ('GD_TEMPLATESOURCE_DIVIDER', 'divider');
define ('GD_TEMPLATESOURCE_FETCHMORE', 'fetchmore');
define ('GD_TEMPLATESOURCE_FORM', 'form');
define ('GD_TEMPLATESOURCE_FORM_INNER', 'form-inner');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_BUTTONGROUP', 'formcomponent-buttongroup');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_CAPTCHA', 'formcomponent-captcha');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_CHECKBOX', 'formcomponent-checkbox');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_DATERANGE', 'formcomponent-daterange');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE', 'formcomponent-featuredimage');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE_INNER', 'formcomponent-featuredimage-inner');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_FETCHLINKTYPEAHEAD', 'formcomponent-typeahead-fetchlink');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_INPUTGROUP', 'formcomponent-inputgroup');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_SELECT', 'formcomponent-select');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEAD', 'formcomponent-typeahead-selectable');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER', 'formcomponent-selectabletypeaheadtrigger');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_TEXT', 'formcomponent-text');
define ('GD_TEMPLATESOURCE_FORMCOMPONENT_TEXTAREA', 'formcomponent-textarea');
define ('GD_TEMPLATESOURCE_FORMGROUP', 'formgroup');
define ('GD_TEMPLATESOURCE_HIDEIFEMPTY', 'hideifempty');
define ('GD_TEMPLATESOURCE_LATESTCOUNT', 'latestcount');
define ('GD_TEMPLATESOURCE_LAYOUT_MAXHEIGHT', 'layout-maxheight');
define ('GD_TEMPLATESOURCE_LAYOUT_CONTENT', 'layout-content');
define ('GD_TEMPLATESOURCE_LAYOUT_LINKCONTENT', 'layout-linkcontent');
define ('GD_TEMPLATESOURCE_LAYOUT_APPENDSCRIPT', 'script-append');
define ('GD_TEMPLATESOURCE_LAYOUT_AUTHOR_CONTACT', 'layout-author-contact');
define ('GD_TEMPLATESOURCE_LAYOUT_AUTHOR_USERPHOTO', 'layout-author-userphoto');
define ('GD_TEMPLATESOURCE_LAYOUT_AUTHORCONTENT', 'layout-authorcontent');
define ('GD_TEMPLATESOURCE_LAYOUT_CATEGORIES', 'layout-categories');
define ('GD_TEMPLATESOURCE_LAYOUT_COMMENT', 'layout-comment');
define ('GD_TEMPLATESOURCE_LAYOUT_DATAQUERY_UPDATEDATA', 'layout-dataquery-updatedata');
define ('GD_TEMPLATESOURCE_LAYOUT_EMBEDPREVIEW', 'layout-embedpreview');
define ('GD_TEMPLATESOURCE_LAYOUT_INITJSDELAY', 'layout-initjs-delay');
define ('GD_TEMPLATESOURCE_LAYOUT_FULLOBJECTTITLE', 'layout-fullobjecttitle');
define ('GD_TEMPLATESOURCE_LAYOUT_FULLVIEW', 'layout-fullview');
define ('GD_TEMPLATESOURCE_LAYOUT_FULLUSER', 'layout-fulluser');
define ('GD_TEMPLATESOURCE_LAYOUT_LATESTCOUNTSCRIPT', 'script-latestcount');
define ('GD_TEMPLATESOURCE_LAYOUT_MARKER', 'layout-marker');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_ANCHOR', 'layout-menu-anchor');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON', 'layout-menu-collapsesegmentedbutton');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWN', 'layout-menu-dropdown');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWNBUTTON', 'layout-menu-dropdownbutton');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_INDENT', 'layout-menu-indent');
define ('GD_TEMPLATESOURCE_LAYOUT_MENU_MULTITARGETINDENT', 'layout-menu-multitargetindent');
define ('GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACK', 'layout-messagefeedback');
define ('GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACKFRAME', 'layout-messagefeedbackframe');
define ('GD_TEMPLATESOURCE_LAYOUT_MULTIPLE', 'layout-multiple');
define ('GD_TEMPLATESOURCE_LAYOUT_PAGETAB', 'layout-pagetab');
define ('GD_TEMPLATESOURCE_LAYOUT_POPOVER', 'layout-popover');
define ('GD_TEMPLATESOURCE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL', 'layout-postadditional-multilayout-label');
define ('GD_TEMPLATESOURCE_LAYOUT_POSTSTATUSDATE', 'layout-poststatusdate');
define ('GD_TEMPLATESOURCE_LAYOUT_TAGINFO', 'layout-taginfo');
define ('GD_TEMPLATESOURCE_LAYOUT_POSTTHUMB', 'layout-postthumb');
define ('GD_TEMPLATESOURCE_LAYOUT_PREVIEWPOST', 'layout-previewpost');
define ('GD_TEMPLATESOURCE_LAYOUT_PREVIEWUSER', 'layout-previewuser');
define ('GD_TEMPLATESOURCE_LAYOUT_SCRIPTFRAME', 'layout-scriptframe');
define ('GD_TEMPLATESOURCE_LAYOUT_SEGMENTEDBUTTON_LINK', 'layout-segmentedbutton-link');
define ('GD_TEMPLATESOURCE_LAYOUT_STYLES', 'layout-styles');
define ('GD_TEMPLATESOURCE_LAYOUT_SUBCOMPONENT', 'layout-subcomponent');
define ('GD_TEMPLATESOURCE_LAYOUT_TAG', 'layout-tag');
define ('GD_TEMPLATESOURCE_LAYOUT_USERAVATAR', 'layout-useravatar');
define ('GD_TEMPLATESOURCE_LAYOUT_USERPOSTINTERACTION', 'layout-userpostinteraction');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORAVATAR', 'layoutpost-authoravatar');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORNAME', 'layoutpost-authorname');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_DATE', 'layoutpost-date');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_STATUS', 'layoutpost-status');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_COMPONENT', 'layoutpost-typeahead-component');
define ('GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_SELECTED', 'layoutpost-typeahead-selected');
// define ('GD_TEMPLATESOURCE_LAYOUTSINGLE', 'layoutsingle');
define ('GD_TEMPLATESOURCE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT', 'layoutstatic-typeahead-component');
define ('GD_TEMPLATESOURCE_LAYOUTTAG_TYPEAHEAD_COMPONENT', 'layouttag-typeahead-component');
define ('GD_TEMPLATESOURCE_LAYOUTUSER_MENTION_COMPONENT', 'layoutuser-mention-component');
define ('GD_TEMPLATESOURCE_LAYOUTUSER_QUICKLINKS', 'layoutuser-quicklinks');
define ('GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_COMPONENT', 'layoutuser-typeahead-component');
define ('GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_SELECTED', 'layoutuser-typeahead-selected');
define ('GD_TEMPLATESOURCE_MESSAGE', 'message');
define ('GD_TEMPLATESOURCE_MESSAGEFEEDBACK', 'messagefeedback');
define ('GD_TEMPLATESOURCE_MESSAGEFEEDBACK_INNER', 'messagefeedback-inner');
define ('GD_TEMPLATESOURCE_MULTIPLE', 'multiple');
// define ('GD_TEMPLATESOURCE_PAGESECTION_MODAL', 'pagesection-modal');
// define ('GD_TEMPLATESOURCE_PAGESECTION_PAGETAB', 'pagesection-pagetab');
define ('GD_TEMPLATESOURCE_PAGESECTION_PLAIN', 'pagesection-plain');
// define ('GD_TEMPLATESOURCE_PAGESECTION_TABPANE', 'pagesection-tabpane');
define ('GD_TEMPLATESOURCE_SCRIPT_APPENDCOMMENT', 'script-append-comment');
define ('GD_TEMPLATESOURCE_SCRIPT_LAZYLOADINGREMOVE', 'script-lazyloading-remove');
define ('GD_TEMPLATESOURCE_SCROLL', 'scroll');
define ('GD_TEMPLATESOURCE_SCROLL_INNER', 'scroll-inner');
define ('GD_TEMPLATESOURCE_SOCIALMEDIA', 'sm'); // Comment Leo: renamed from "socialmedia" to "sm" because AdBlockPlus blocks them
define ('GD_TEMPLATESOURCE_SOCIALMEDIA_ITEM', 'sm-item'); // Comment Leo: renamed from "socialmedia" to "sm" because AdBlockPlus blocks them
define ('GD_TEMPLATESOURCE_STATUS', 'status');
define ('GD_TEMPLATESOURCE_SUBMENU', 'submenu');
define ('GD_TEMPLATESOURCE_TABLE', 'table');
define ('GD_TEMPLATESOURCE_TABLE_INNER', 'table-inner');
define ('GD_TEMPLATESOURCE_USERLOGGEDIN', 'userloggedin');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_BUTTON', 'viewcomponent-button');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED', 'viewcomponent-header-commentclipped');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTPOST', 'viewcomponent-header-commentpost');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_POST', 'viewcomponent-header-post');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_REPLYCOMMENT', 'viewcomponent-header-replycomment');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_USER', 'viewcomponent-header-user');
define ('GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_TAG', 'viewcomponent-header-tag');
define ('GD_TEMPLATESOURCE_WIDGET', 'widget');

