<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCK_SECTION_SEARCHPOSTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-searchposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-allcontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_WEBPOSTLINKS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-webpostlinks-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-highlights-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_WEBPOSTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-webposts-sidebar'));

define ('GD_TEMPLATE_BLOCK_SECTION_SEARCHUSERS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-searchusers-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-allusers-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR', PoP_ServerUtils::get_template_definition('block-section-allusers-nofiltersidebar'));

define ('GD_TEMPLATE_BLOCK_SECTION_TRENDINGTAGS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-trendingtags-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_TAGS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-tags-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_AUTHORTAGS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-authortags-sidebar'));

define ('GD_TEMPLATE_BLOCK_SECTION_MYCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-mycontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTLINKS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-mywebpostlinks-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYHIGHLIGHTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-myhighlights-sidebar'));
define ('GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-section-mywebposts-sidebar'));

define ('GD_TEMPLATE_BLOCK_TAGSECTION_MAINALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-tagsection-mainallcontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_ALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-tagsection-allcontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAGSECTION_WEBPOSTS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-tagsection-webposts-sidebar'));
define ('GD_TEMPLATE_BLOCK_TAG_SIDEBAR', PoP_ServerUtils::get_template_definition('block-tag-sidebar'));

define ('GD_TEMPLATE_BLOCK_SINGLE_WEBPOSTLINK_SIDEBAR', PoP_ServerUtils::get_template_definition('block-single-webpostlink-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_HIGHLIGHT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-single-highlight-sidebar'));
define ('GD_TEMPLATE_BLOCK_SINGLE_WEBPOST_SIDEBAR', PoP_ServerUtils::get_template_definition('block-single-webpost-sidebar'));

define ('GD_TEMPLATE_BLOCK_AUTHORSECTION_MAINALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-authorsection-mainallcontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-authorsection-allcontent-sidebar'));
define ('GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLUSERS_SIDEBAR', PoP_ServerUtils::get_template_definition('block-authorsection-allusers-sidebar'));

define ('GD_TEMPLATE_BLOCK_HOMESECTION_ALLCONTENT_SIDEBAR', PoP_ServerUtils::get_template_definition('block-homesection-allcontent-sidebar'));

class GD_Template_Processor_CustomSidebarBlocks extends GD_Template_Processor_CustomSidebarBlocksBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCK_SECTION_SEARCHPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_WEBPOSTLINKS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_WEBPOSTS_SIDEBAR,

			GD_TEMPLATE_BLOCK_SECTION_SEARCHUSERS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR,

			GD_TEMPLATE_BLOCK_SECTION_TRENDINGTAGS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_TAGS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_AUTHORTAGS_SIDEBAR,

			GD_TEMPLATE_BLOCK_SECTION_MYCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTLINKS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYHIGHLIGHTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTS_SIDEBAR,

			GD_TEMPLATE_BLOCK_TAGSECTION_MAINALLCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_ALLCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAGSECTION_WEBPOSTS_SIDEBAR,
			GD_TEMPLATE_BLOCK_TAG_SIDEBAR,
			
			GD_TEMPLATE_BLOCK_SINGLE_WEBPOSTLINK_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_HIGHLIGHT_SIDEBAR,
			GD_TEMPLATE_BLOCK_SINGLE_WEBPOST_SIDEBAR,

			GD_TEMPLATE_BLOCK_AUTHORSECTION_MAINALLCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLCONTENT_SIDEBAR,
			GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLUSERS_SIDEBAR,

			GD_TEMPLATE_BLOCK_HOMESECTION_ALLCONTENT_SIDEBAR,
		);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_SECTION_TAGS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SECTION_AUTHORTAGS_SIDEBAR:

				return GD_TEMPLATE_FILTER_WILDCARDTAGS;

			case GD_TEMPLATE_BLOCK_SECTION_SEARCHPOSTS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_HOMESECTION_ALLCONTENT_SIDEBAR:
				
				return GD_TEMPLATE_FILTER_WILDCARDPOSTS;

			case GD_TEMPLATE_BLOCK_TAGSECTION_MAINALLCONTENT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_TAGSECTION_ALLCONTENT_SIDEBAR:
				
				return GD_TEMPLATE_FILTER_TAGWILDCARDPOSTS;

			case GD_TEMPLATE_BLOCK_AUTHORSECTION_MAINALLCONTENT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLCONTENT_SIDEBAR:
				
				return GD_TEMPLATE_FILTER_AUTHORWILDCARDPOSTS;

			case GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLUSERS_SIDEBAR:

				return GD_TEMPLATE_FILTER_AUTHORWILDCARDUSERS;

			case GD_TEMPLATE_BLOCK_SECTION_WEBPOSTLINKS_SIDEBAR:

				return GD_TEMPLATE_FILTER_LINKS;

			case GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_HIGHLIGHTS;

			case GD_TEMPLATE_BLOCK_SECTION_WEBPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_WEBPOSTS;

			case GD_TEMPLATE_BLOCK_TAGSECTION_WEBPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_TAGWEBPOSTS;

			case GD_TEMPLATE_BLOCK_SECTION_SEARCHUSERS_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR:

				return GD_TEMPLATE_FILTER_WILDCARDUSERS;

			case GD_TEMPLATE_BLOCK_SECTION_MYCONTENT_SIDEBAR:

				return GD_TEMPLATE_FILTER_WILDCARDMYPOSTS;

			case GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTLINKS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYLINKS;

			case GD_TEMPLATE_BLOCK_SECTION_MYHIGHLIGHTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYHIGHLIGHTS;

			case GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTS_SIDEBAR:

				return GD_TEMPLATE_FILTER_MYWEBPOSTS;
		}
		
		return parent::get_filter_template($template_id);
	}

	protected function get_block_inner_templates($template_id) {

		$ret = parent::get_block_inner_templates($template_id);

		$orientation = apply_filters(POP_HOOK_BLOCKSIDEBARS_ORIENTATION, 'vertical');
		$vertical = ($orientation == 'vertical');

		$block_inners = array(
			GD_TEMPLATE_BLOCK_SECTION_SEARCHPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_SEARCHPOSTS,
			GD_TEMPLATE_BLOCK_SECTION_ALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_ALLCONTENT,
			GD_TEMPLATE_BLOCK_SECTION_WEBPOSTLINKS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_WEBPOSTLINKS,
			GD_TEMPLATE_BLOCK_SECTION_HIGHLIGHTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_HIGHLIGHTS,
			GD_TEMPLATE_BLOCK_SECTION_WEBPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_WEBPOSTS,
			
			GD_TEMPLATE_BLOCK_SECTION_SEARCHUSERS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_SEARCHUSERS,
			GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_ALLUSERS,
			GD_TEMPLATE_BLOCK_SECTION_ALLUSERS_NOFILTERSIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_ALLUSERS_NOFILTER,
			
			GD_TEMPLATE_BLOCK_SECTION_TRENDINGTAGS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TRENDINGTAGS,
			GD_TEMPLATE_BLOCK_SECTION_TAGS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_TAGS,
			GD_TEMPLATE_BLOCK_SECTION_AUTHORTAGS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_AUTHORTAGS,

			GD_TEMPLATE_BLOCK_SECTION_MYCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYCONTENT,
			GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTLINKS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYWEBPOSTLINKS,
			GD_TEMPLATE_BLOCK_SECTION_MYHIGHLIGHTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYHIGHLIGHTS,
			GD_TEMPLATE_BLOCK_SECTION_MYWEBPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_SECTION_MYWEBPOSTS,
		
			GD_TEMPLATE_BLOCK_TAGSECTION_MAINALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_TAGSECTION_MAINALLCONTENT,
			GD_TEMPLATE_BLOCK_TAGSECTION_ALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_TAGSECTION_ALLCONTENT,
			GD_TEMPLATE_BLOCK_TAGSECTION_WEBPOSTS_SIDEBAR => GD_TEMPLATE_SIDEBAR_TAGSECTION_WEBPOSTS,

			GD_TEMPLATE_BLOCK_TAG_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_TAG : GD_TEMPLATE_LAYOUT_TAGSIDEBAR_HORIZONTAL,
			
			GD_TEMPLATE_BLOCK_SINGLE_WEBPOSTLINK_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_LINK : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LINK,
			GD_TEMPLATE_BLOCK_SINGLE_HIGHLIGHT_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_HIGHLIGHT : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_HIGHLIGHT,
			GD_TEMPLATE_BLOCK_SINGLE_WEBPOST_SIDEBAR => $vertical ? GD_TEMPLATE_VERTICALSIDEBAR_SINGLE_WEBPOST : GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_WEBPOST,
		
			GD_TEMPLATE_BLOCK_AUTHORSECTION_MAINALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_AUTHORSECTION_MAINALLCONTENT,
			GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_AUTHORSECTION_ALLCONTENT,
			GD_TEMPLATE_BLOCK_AUTHORSECTION_ALLUSERS_SIDEBAR => GD_TEMPLATE_SIDEBAR_AUTHORSECTION_ALLUSERS,

			GD_TEMPLATE_BLOCK_HOMESECTION_ALLCONTENT_SIDEBAR => GD_TEMPLATE_SIDEBAR_HOMESECTION_ALLCONTENT,
		);

		if ($block_inner = $block_inners[$template_id]) {

			$ret[] = $block_inner;
		}
	
		return $ret;
	}

	function get_dataloader($template_id) {

		switch ($template_id) {
					
			case GD_TEMPLATE_BLOCK_SINGLE_WEBPOSTLINK_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_HIGHLIGHT_SIDEBAR:
			case GD_TEMPLATE_BLOCK_SINGLE_WEBPOST_SIDEBAR:

				return GD_DATALOADER_SINGLE;

			case GD_TEMPLATE_BLOCK_TAG_SIDEBAR:

				return GD_DATALOADER_TAG;
		}
		
		return parent::get_dataloader($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Template_Processor_CustomSidebarBlocks();