<?php

// Gravity Forms Field Ids
//--------------------------------------------------------
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FORM_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_NAME_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_EMAIL_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_SUBJECT_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_MESSAGE_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_PAGEURL_ID', false);
define('POP_GENERICFORMS_GF_FORM_CONTACTUSER_FIELDNAME_PAGETITLE_ID', false);
