query GetMediaItems {
  me {
    slug
  }
  
  myMediaItemCount

  myMediaItems(pagination: {
    limit: 3
  }) {
    ...MediaItemData
  }

  myMediaItem(by: { id: 1382 }) {
    ...MediaItemData
  }

  notMine: myMediaItem(by: { id: 1363 }) {
    ...MediaItemData
  }

  nonExisting: myMediaItem(by: { id: 8888 }) {
    ...MediaItemData
  }
}

fragment MediaItemData on Media {
  altText
  author {
    slug
  } 
  caption
  date
  dateStr(format: "F j")
  description
  height
  id
  mimeType
  modifiedDate
  modifiedDateStr
  sizes
  slug
  src
  srcSet
  title
  url
  urlPath
  width
}