{
  # User state
  me {
    id
    roleNames
  }

  # Posts
  existingPost: myPost(by: { id: 1116 }, status: [pending, trash]) {
    id
    title
  }
  nonExistingPost: myPost(by: { id: 8888 }, status: [pending, trash]) {
    id
    title
  }
  myPosts(status: [pending, trash]) {
    id
    title
  }
  myPostCount(status: [pending, trash])

  # Custom Posts
  existingCustomPost: myCustomPost(by: { id: 1116 }, status: [pending, trash]) {
    id
    title
  }
  nonExistingCustomPost: myCustomPost(by: { id: 8888 }, status: [pending, trash]) {
    id
    title
  }
  myCustomPosts(status: [pending, trash]) {
    __typename
    ...on CustomPost {
      id
      title
    }
  }
  myCustomPostCount(status: [pending, trash])

  # Pages
  existingPage: myPage(by: { id: 2 }, status: [pending, trash]) {
    id
    title
  }
  nonExistingPage: myPage(by: { id: 8888 }, status: [pending, trash]) {
    id
    title
  }
  myPages(status: [pending, trash]) {
    id
    title
  }
  myPageCount(status: [pending, trash])
}