query GetTypeInfoByIntrospection {
  __schema {
    tagUnionType: type(name: "TagUnion") {
      name
      possibleTypes {
        name
      }
    }
    tagTaxonomyEnumType: type(name: "TagTaxonomyEnumString") {
      name
      extensions {
        possibleValues
      }
    }
  }
}