<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

/*--------------------------------------------
 * Details: Thumb, title and excerpt
 --------------------------------------------*/
define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-events-scroll-details'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-pastevents-scroll-details'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorevents-scroll-details'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorpastevents-scroll-details'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagevents-scroll-details'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagpastevents-scroll-details'));

/*--------------------------------------------
 * Full Post
 --------------------------------------------*/
define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-events-scroll-simpleview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-pastevents-scroll-simpleview'));

define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-events-scroll-fullview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-pastevents-scroll-fullview'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorevents-scroll-simpleview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorpastevents-scroll-simpleview'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorevents-scroll-fullview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorpastevents-scroll-fullview'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagevents-scroll-simpleview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagpastevents-scroll-simpleview'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagevents-scroll-fullview'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagpastevents-scroll-fullview'));

/*--------------------------------------------
 * Thumbnail
 --------------------------------------------*/
define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-events-scroll-thumbnail'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-pastevents-scroll-thumbnail'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorevents-scroll-thumbnail'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorpastevents-scroll-thumbnail'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagevents-scroll-thumbnail'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagpastevents-scroll-thumbnail'));

/*--------------------------------------------
 * List
 --------------------------------------------*/
define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-events-scroll-list'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-pastevents-scroll-list'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorevents-scroll-list'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-authorpastevents-scroll-list'));

// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagevents-scroll-list'));
// define ('GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST', PoP_TemplateIDUtils::get_template_definition('block-automatedemails-tagpastevents-scroll-list'));

class PoPTheme_Wassup_EM_AE_Template_Processor_SectionBlocks extends PoPTheme_Wassup_AutomatedEmails_Template_Processor_SectionBlocksBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS,
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW,
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW,
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL,
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST,
		);
	}

	protected function get_block_inner_template($template_id) {

		$inner_templates = array(

			/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
			 * Home/Page blocks
			 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/
			
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_DETAILS,
			
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_SIMPLEVIEW,
			
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_FULLVIEW,
			
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_THUMBNAIL,
			
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_LIST,
			
			/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
			 * Author blocks
			 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_DETAILS,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_SIMPLEVIEW,//GD_TEMPLATE_SCROLL_AUTHOREVENTS_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_SIMPLEVIEW,//GD_TEMPLATE_SCROLL_AUTHORPASTEVENTS_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLLAUTOMATEDEMAILS__AUTHOREVENTS_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_AUTHORPASTEVENTS_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_THUMBNAIL,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_LIST,
			
			/*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
			 * Tag blocks
			 *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*/

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_DETAILS,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_THUMBNAIL,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_EVENTS_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST => GD_TEMPLATE_SCROLL_AUTOMATEDEMAILS_PASTEVENTS_LIST,
		);

		return $inner_templates[$template_id];
	}

	function get_title($template_id) {
	
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

				// Important: this text can only be in the title, and not in the description, because the description is saved in pop-cache/,
				// while the title is set on runtime, so only then we can have the date on the title!
				return sprintf(
					__('Upcoming events — %s <small><a href="%s">View online</a></small>', 'poptheme-wassup-automatedemails'),
					date(get_option('date_format')),
					get_permalink(POPTHEME_WASSUP_EM_PAGE_EVENTS)
				);
		}

		return parent::get_title($template_id);
	}

	protected function get_description_abovetitle($template_id, $atts) {
	
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

				return sprintf(
					'<p>%s</p>',
					sprintf(
						__('These are our events for this week. Do you have an event? <a href="%s" target="%s">Click here</a> to share it with our community.', 'poptheme-wassup-automatedemails'),
						get_permalink(POPTHEME_WASSUP_EM_PAGE_ADDEVENT),
						PoPTheme_Wassup_Utils::get_addcontent_target()
					)
				);
		}

		return parent::get_description_abovetitle($template_id, $atts);
	}

	protected function get_description_bottom($template_id, $atts) {
	
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

				return sprintf(
					// '<p>&nbsp;</p><p>%s</p>%s',
					'<p>&nbsp;</p><p>%s</p>',
					sprintf(
						'<a href="%s">%s</a>',
						get_permalink(POPTHEME_WASSUP_EM_PAGE_EVENTS),
						sprintf(
							__('View all events on %s', 'poptheme-wassup-automatedemails'),
							get_bloginfo('name')
						)
					)//,
					// PoP_EmailSender_CustomUtils::get_preferences_footer()
				);
		}

		return parent::get_description_bottom($template_id, $atts);
	}

	// protected function show_status($template_id) {

	// 	switch ($template_id) {

	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

	// 			return false;
	// 	}

	// 	return parent::show_status($template_id);
	// }

	// protected function show_disabled_layer($template_id) {

	// 	switch ($template_id) {

	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

	// 			return false;
	// 	}

	// 	return parent::show_disabled_layer($template_id);
	// }

	protected function get_messagefeedback($template_id) {
	
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

				return GD_TEMPLATE_MESSAGEFEEDBACK_EVENTS;
		}

		return parent::get_messagefeedback($template_id);
	}

	protected function get_messagefeedback_position($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:
			
				return 'bottom';
		}

		return parent::get_messagefeedback_position($template_id);
	}

	function get_filter_template($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST:

				return GD_TEMPLATE_FILTER_EVENTS;

			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST:

			// 	return GD_TEMPLATE_FILTER_AUTHOREVENTS;

			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST:

			// 	return GD_TEMPLATE_FILTER_TAGEVENTS;
		}
		
		return parent::get_filter_template($template_id);
	}

	function get_dataload_source($template_id, $atts) {

		// switch ($template_id) {

		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST:
			
		// 		$ret = GD_Template_Processor_CustomSectionBlocksUtils::get_author_dataloadsource($template_id);
		// 		break;

		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL:
		// 	case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST:

		// 		$ret = GD_Template_Processor_CustomSectionBlocksUtils::get_tag_dataloadsource($template_id);
		// 		break;

		// 	default:

		// 		$ret = parent::get_dataload_source($template_id, $atts);
		// 		break;
		// }

		$ret = parent::get_dataload_source($template_id, $atts);

		// Add the format attr
		$details = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST,

			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST,
		);
		if (in_array($template_id, $details)) {
			
			$format = GD_TEMPLATEFORMAT_DETAILS;
		}
		elseif (in_array($template_id, $simpleviews)) {
			
			$format = GD_TEMPLATEFORMAT_SIMPLEVIEW;
		}
		elseif (in_array($template_id, $fullviews)) {
			
			$format = GD_TEMPLATEFORMAT_FULLVIEW;
		}
		elseif (in_array($template_id, $thumbnails)) {
			
			$format = GD_TEMPLATEFORMAT_THUMBNAIL;
		}
		elseif (in_array($template_id, $lists)) {
			
			$format = GD_TEMPLATEFORMAT_LIST;
		}

		if ($format) {

			$ret = add_query_arg(GD_URLPARAM_FORMAT, $format, $ret);
		}
	
		return $ret;
	}

	protected function get_dataload_query_args($template_id, $atts) {

		$ret = parent::get_dataload_query_args($template_id, $atts);

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:

				// 1 week of events
				$ret['scope'] = 'week';
				break;
		}
		
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW,
		);
		
		if (in_array($template_id, $simpleviews) || in_array($template_id, $fullviews)) {
			
			$ret['limit'] = 6;
		}

		// Allow to override the limit by $atts (eg: for the Website Features, Filter section)
		if ($limit = $this->get_att($template_id, $atts, 'limit')) {
			$ret['limit'] = $limit;
		}

		return $ret;
	}

	// protected function get_runtime_dataload_query_args($template_id, $atts) {

	// 	$ret = parent::get_runtime_dataload_query_args($template_id, $atts);
		
	// 	switch ($template_id) {

	// 		// Filter by the Profile/Community
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST:

	// 			GD_Template_Processor_CustomSectionBlocksUtils::add_dataloadqueryargs_authorcontent($ret);
	// 			break;

	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST:

	// 			GD_Template_Processor_CustomSectionBlocksUtils::add_dataloadqueryargs_tagcontent($ret);
	// 			break;
	// 	}

	// 	return $ret;
	// }

	// function get_title($template_id) {
	
	// 	switch ($template_id) {

	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST:

	// 			return GD_Template_Processor_CustomSectionBlocksUtils::get_author_title();

	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST:
	// 		case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST:

	// 			return GD_Template_Processor_CustomSectionBlocksUtils::get_tag_title();
	// 	}
		
	// 	return parent::get_title($template_id);
	// }

	protected function get_iohandler($template_id) {

		return GD_DATALOAD_IOHANDLER_LIST;
	}

	function get_dataloader($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL:
			case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST:
			
				return GD_DATALOADER_EVENTLIST;

			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL:
			// case GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST:

			// 	return GD_DATALOADER_PASTEVENTLIST;
		}

		return parent::get_dataloader($template_id);
	}

	function get_data_setting($template_id, $atts) {

		$ret = parent::get_data_setting($template_id, $atts);

		// Set the display configuration
		$details = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_DETAILS,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_DETAILS,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_DETAILS,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_DETAILS,
		);
		$simpleviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_SIMPLEVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_SIMPLEVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_FULLVIEW,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_FULLVIEW,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_FULLVIEW,
		);
		$thumbnails = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_THUMBNAIL,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_THUMBNAIL,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_THUMBNAIL,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_EVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_PASTEVENTS_SCROLL_LIST,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHOREVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_AUTHORPASTEVENTS_SCROLL_LIST,
			
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGEVENTS_SCROLL_LIST,
			// GD_TEMPLATE_BLOCK_AUTOMATEDEMAILS_TAGPASTEVENTS_SCROLL_LIST,
		);

		if (in_array($template_id, $details)) {
			
			$format = GD_TEMPLATEFORMAT_DETAILS;
		}
		elseif (in_array($template_id, $simpleviews)) {
			
			$format = GD_TEMPLATEFORMAT_SIMPLEVIEW;
		}
		elseif (in_array($template_id, $fullviews)) {
			
			$format = GD_TEMPLATEFORMAT_FULLVIEW;
		}
		elseif (in_array($template_id, $thumbnails)) {
			
			$format = GD_TEMPLATEFORMAT_THUMBNAIL;
		}
		elseif (in_array($template_id, $lists)) {
			
			$format = GD_TEMPLATEFORMAT_LIST;
		}

		if ($format) {
			$ret['iohandler-atts'][GD_URLPARAM_FORMAT] = $format;
		}
		
		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new PoPTheme_Wassup_EM_AE_Template_Processor_SectionBlocks();