<?php
$helper_functions = array_merge(
	$helper_functions, 
	array(
		// 'breaklines' => 'PoP_ServerSide_HelperCallers::breaklines',
		'showmore' => 'PoP_ServerSide_HelperCallers::showmore',
		'ondate' => 'PoP_ServerSide_HelperCallers::ondate',
		// 'img' => 'PoP_ServerSide_HelperCallers::img',
		'addParam' => 'PoP_ServerSide_HelperCallers::addParam',
		'destroyUrl' => 'PoP_ServerSide_HelperCallers::destroyUrl',
		'statusLabel' => 'PoP_ServerSide_HelperCallers::statusLabel',
		'labelize' => 'PoP_ServerSide_HelperCallers::labelize',
		// 'infoButton' => 'PoP_ServerSide_HelperCallers::infoButton',
		// 'infoCollapse' => 'PoP_ServerSide_HelperCallers::infoCollapse',
		'mod' => 'PoP_ServerSide_HelperCallers::mod',
		'eq' => 'PoP_ServerSide_HelperCallers::eq',
		'or' => 'PoP_ServerSide_HelperCallers::or',
		'compare' => 'PoP_ServerSide_HelperCallers::compare',
		'get' => 'PoP_ServerSide_HelperCallers::get',
		'ifget' => 'PoP_ServerSide_HelperCallers::ifget',
		'withget' => 'PoP_ServerSide_HelperCallers::withget',
		'iffirstload' => 'PoP_ServerSide_HelperCallers::iffirstload',
		'interceptAttr' => 'PoP_ServerSide_HelperCallers::interceptAttr',
		'generateId' => 'PoP_ServerSide_HelperCallers::generateId',
		'lastGeneratedId' => 'PoP_ServerSide_HelperCallers::lastGeneratedId',
		'applyLightTemplate' => 'PoP_ServerSide_HelperCallers::applyLightTemplate',
		'json' => 'PoP_ServerSide_HelperCallers::json',
		'enterModule' => 'PoP_ServerSide_HelperCallers::enterModule',
		'withLayout' => 'PoP_ServerSide_HelperCallers::withLayout',
		'layoutLabel' => 'PoP_ServerSide_HelperCallers::layoutLabel',
		// 'withOptions' => 'PoP_ServerSide_HelperCallers::withOptions',
		'withBlock' => 'PoP_ServerSide_HelperCallers::withBlock',
		'withModule' => 'PoP_ServerSide_HelperCallers::withModule',
		'withSublevel' => 'PoP_ServerSide_HelperCallers::withSublevel',
		'withItemObject' => 'PoP_ServerSide_HelperCallers::withItemObject',
		// 'join',
	)
);