#######################################################
# Argument `size` is mandatory and it has a default
# value, but since it's overridden with `null` then
# it will produce an error
#######################################################
query {
  user(by: {id: 1}) {
    avatar(size: null) {
      id
    }
  }
}