<?php

// Gravity Forms Field Ids
//--------------------------------------------------------
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FORM_ID', false);
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_NAME_ID', false);
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_DESTINATIONEMAILS_ID', false);
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_ADDITIONALMESSAGE_ID', false);
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_PAGEURL_ID', false);
define('POP_GENERICFORMS_GF_FORM_SHAREBYEMAIL_FIELDNAME_PAGETITLE_ID', false);
