<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE', PoP_ServerUtils::get_template_definition('block-locationpost-update'));
define ('GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE', PoP_ServerUtils::get_template_definition('block-locationpostlink-update'));
define ('GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE', PoP_ServerUtils::get_template_definition('block-locationpost-create'));
define ('GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE', PoP_ServerUtils::get_template_definition('block-locationpostlink-create'));
define ('GD_TEMPLATE_BLOCK_STORY_UPDATE', PoP_ServerUtils::get_template_definition('block-story-update'));
define ('GD_TEMPLATE_BLOCK_STORYLINK_UPDATE', PoP_ServerUtils::get_template_definition('block-storylink-update'));
define ('GD_TEMPLATE_BLOCK_STORY_CREATE', PoP_ServerUtils::get_template_definition('block-story-create'));
define ('GD_TEMPLATE_BLOCK_STORYLINK_CREATE', PoP_ServerUtils::get_template_definition('block-storylink-create'));
define ('GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE', PoP_ServerUtils::get_template_definition('block-announcement-update'));
define ('GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE', PoP_ServerUtils::get_template_definition('block-announcementlink-update'));
define ('GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE', PoP_ServerUtils::get_template_definition('block-announcement-create'));
define ('GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE', PoP_ServerUtils::get_template_definition('block-announcementlink-create'));
define ('GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE', PoP_ServerUtils::get_template_definition('block-discussion-update'));
define ('GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE', PoP_ServerUtils::get_template_definition('block-discussionlink-update'));
define ('GD_TEMPLATE_BLOCK_DISCUSSION_CREATE', PoP_ServerUtils::get_template_definition('block-discussion-create'));
define ('GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE', PoP_ServerUtils::get_template_definition('block-discussionlink-create'));
define ('GD_TEMPLATE_BLOCK_FEATURED_UPDATE', PoP_ServerUtils::get_template_definition('block-featured-update'));
define ('GD_TEMPLATE_BLOCK_FEATURED_CREATE', PoP_ServerUtils::get_template_definition('block-featured-create'));

class GD_Custom_Template_Processor_CreateUpdatePostBlocks extends GD_Template_Processor_BlocksBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE,
			GD_TEMPLATE_BLOCK_STORY_UPDATE,
			GD_TEMPLATE_BLOCK_STORYLINK_UPDATE,
			GD_TEMPLATE_BLOCK_STORY_CREATE,
			GD_TEMPLATE_BLOCK_STORYLINK_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE,
			GD_TEMPLATE_BLOCK_FEATURED_UPDATE,
			GD_TEMPLATE_BLOCK_FEATURED_CREATE,
		);
	}

	protected function get_controlgroup_top($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				return GD_TEMPLATE_CONTROLGROUP_CREATEPOST;

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:

				return GD_TEMPLATE_CONTROLGROUP_EDITPOST;
		}
		
		return parent::get_controlgroup_top($template_id);
	}

	protected function get_messagefeedback($template_id) {

		$feedbacks = array(
			GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_LOCATIONPOST_CREATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_LOCATIONPOST_CREATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_LOCATIONPOST_UPDATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_LOCATIONPOST_UPDATE,
			GD_TEMPLATE_BLOCK_STORY_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_STORY_CREATE,
			GD_TEMPLATE_BLOCK_STORYLINK_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_STORY_CREATE,
			GD_TEMPLATE_BLOCK_STORY_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_STORY_UPDATE,
			GD_TEMPLATE_BLOCK_STORYLINK_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_STORY_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_ANNOUNCEMENT_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_ANNOUNCEMENT_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_ANNOUNCEMENT_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_ANNOUNCEMENT_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_DISCUSSION_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_DISCUSSION_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_DISCUSSION_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_DISCUSSION_UPDATE,
			GD_TEMPLATE_BLOCK_FEATURED_CREATE => GD_TEMPLATE_MESSAGEFEEDBACK_FEATURED_CREATE,
			GD_TEMPLATE_BLOCK_FEATURED_UPDATE => GD_TEMPLATE_MESSAGEFEEDBACK_FEATURED_UPDATE,
		);
	
		if ($feedback = $feedbacks[$template_id]) {

			return $feedback;
		}

		return parent::get_messagefeedback($template_id);
	}

	protected function get_block_inner_templates($template_id) {

		$ret = parent::get_block_inner_templates($template_id);

		$block_inners = array(
			GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE => GD_TEMPLATE_FORM_LOCATIONPOST_UPDATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE => GD_TEMPLATE_FORM_LOCATIONPOSTLINK_UPDATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE => GD_TEMPLATE_FORM_LOCATIONPOST_CREATE,
			GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE => GD_TEMPLATE_FORM_LOCATIONPOSTLINK_CREATE,
			GD_TEMPLATE_BLOCK_STORY_UPDATE => GD_TEMPLATE_FORM_STORY_UPDATE,
			GD_TEMPLATE_BLOCK_STORYLINK_UPDATE => GD_TEMPLATE_FORM_STORYLINK_UPDATE,
			GD_TEMPLATE_BLOCK_STORY_CREATE => GD_TEMPLATE_FORM_STORY_CREATE,
			GD_TEMPLATE_BLOCK_STORYLINK_CREATE => GD_TEMPLATE_FORM_STORYLINK_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE => GD_TEMPLATE_FORM_ANNOUNCEMENT_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE => GD_TEMPLATE_FORM_ANNOUNCEMENTLINK_UPDATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE => GD_TEMPLATE_FORM_ANNOUNCEMENT_CREATE,
			GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE => GD_TEMPLATE_FORM_ANNOUNCEMENTLINK_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE => GD_TEMPLATE_FORM_DISCUSSION_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE => GD_TEMPLATE_FORM_DISCUSSIONLINK_UPDATE,
			GD_TEMPLATE_BLOCK_DISCUSSION_CREATE => GD_TEMPLATE_FORM_DISCUSSION_CREATE,
			GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE => GD_TEMPLATE_FORM_DISCUSSIONLINK_CREATE,
			GD_TEMPLATE_BLOCK_FEATURED_UPDATE => GD_TEMPLATE_FORM_FEATURED_UPDATE,
			GD_TEMPLATE_BLOCK_FEATURED_CREATE => GD_TEMPLATE_FORM_FEATURED_CREATE,
		);
		if ($block_inner = $block_inners[$template_id]) {

			$ret[] = $block_inner;
		}
	
		return $ret;
	}

	function get_block_jsmethod($template_id, $atts) {

		$ret = parent::get_block_jsmethod($template_id, $atts);
		
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				$this->add_jsmethod($ret, 'formCreatePostBlock');
				break;
		}
		switch ($template_id) {
		
			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:

				$this->add_jsmethod($ret, 'destroyPageOnUserLoggedOut');
				$this->add_jsmethod($ret, 'refetchBlockOnUserLoggedIn');
				break;
		}
		
		return $ret;
	}

	function init_atts($template_id, &$atts) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				$updates = array(
					GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE,
					GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE,
					GD_TEMPLATE_BLOCK_STORY_UPDATE,
					GD_TEMPLATE_BLOCK_STORYLINK_UPDATE,
					GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE,
					GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE,
					GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE,
					GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE,
					GD_TEMPLATE_BLOCK_FEATURED_UPDATE,
				);
				$class = 'pop-block-createupdatepost ';
				if (in_array($template_id, $updates)) {
					$class .= 'pop-block-update-post';
				}
				else {
					$class .= 'pop-block-create-post';
				}
				$this->append_att($template_id, $atts, 'class', $class);
				$this->add_att(GD_TEMPLATE_STATUS, $atts, 'loading-msg', __('Submitting...', 'poptheme-wassup-sectionprocessors'));
				break;
		}

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				if (PoPTheme_Wassup_Utils::get_addcontent_target() == GD_URLPARAM_TARGET_ADDONS) {
				
					$this->append_att($template_id, $atts, 'class', 'addons-nocontrols');
				}
				break;
		}
		
		return parent::init_atts($template_id, $atts);
	}

	function get_dataloader($template_id) {
	
		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:

				return GD_DATALOADER_EDITPOST;

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				return GD_DATALOADER_NOPOSTS;
		}

		return parent::get_dataloader($template_id);
	}

	protected function get_iohandler($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_BLOCK_LOCATIONPOST_CREATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_STORY_CREATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_CREATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_CREATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_CREATE:
			case GD_TEMPLATE_BLOCK_FEATURED_CREATE:

				return GD_DATALOAD_IOHANDLER_ADDPOST;
					
			case GD_TEMPLATE_BLOCK_LOCATIONPOST_UPDATE:
			case GD_TEMPLATE_BLOCK_LOCATIONPOSTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_STORY_UPDATE:
			case GD_TEMPLATE_BLOCK_STORYLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENT_UPDATE:
			case GD_TEMPLATE_BLOCK_ANNOUNCEMENTLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSION_UPDATE:
			case GD_TEMPLATE_BLOCK_DISCUSSIONLINK_UPDATE:
			case GD_TEMPLATE_BLOCK_FEATURED_UPDATE:

				return GD_DATALOAD_IOHANDLER_EDITPOST;
		}
		
		return parent::get_iohandler($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_CreateUpdatePostBlocks();