<?php

/**---------------------------------------------------------------------------------------------------------------
 *
 * IDs Configuration
 *
 * ---------------------------------------------------------------------------------------------------------------*/

// Forms Pages
//--------------------------------------------------------
define ('POPTHEME_WASSUP_GF_PAGE_CONTACTUS', 16124);
define ('POPTHEME_WASSUP_GF_PAGE_CONTACTUSER', 16126);
define ('POPTHEME_WASSUP_GF_PAGE_SHAREBYEMAIL', 16128);
define ('POPTHEME_WASSUP_GF_PAGE_VOLUNTEER', 22954);
define ('POPTHEME_WASSUP_GF_PAGE_FLAG', 20462);
define ('POPTHEME_WASSUP_GF_PAGE_NEWSLETTER', 18775);


// Gravity Forms Field Ids
//--------------------------------------------------------
define ('POPTHEME_WASSUP_GF_CONTACTUS_FORM_ID', '1');	
define ('POPTHEME_WASSUP_GF_CONTACTUS_FIELDNAME_NAME_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_CONTACTUS_FIELDNAME_EMAIL_ID', 'input_2');	
define ('POPTHEME_WASSUP_GF_CONTACTUS_FIELDNAME_TOPIC_ID', 'input_3');	
define ('POPTHEME_WASSUP_GF_CONTACTUS_FIELDNAME_SUBJECT_ID', 'input_4');	
define ('POPTHEME_WASSUP_GF_CONTACTUS_FIELDNAME_MESSAGE_ID', 'input_5');	

define ('POPTHEME_WASSUP_GF_CONTACTUSER_FORM_ID', '2');	
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_NAME_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_EMAIL_ID', 'input_2');	
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_SUBJECT_ID', 'input_3');	
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_MESSAGE_ID', 'input_4');
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_PAGEURL_ID', 'input_5');
define ('POPTHEME_WASSUP_GF_CONTACTUSER_FIELDNAME_PAGETITLE_ID', 'input_6');

define ('POPTHEME_WASSUP_GF_VOLUNTEER_FORM_ID', '3');	
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_NAME_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_EMAIL_ID', 'input_2');	
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_PHONE_ID', 'input_3');	
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_WHYVOLUNTEER_ID', 'input_4');
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_PAGEURL_ID', 'input_5');
define ('POPTHEME_WASSUP_GF_VOLUNTEER_FIELDNAME_PAGETITLE_ID', 'input_6');

define ('POPTHEME_WASSUP_GF_FLAG_FORM_ID', '6');	
define ('POPTHEME_WASSUP_GF_FLAG_FIELDNAME_NAME_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_FLAG_FIELDNAME_EMAIL_ID', 'input_2');	
define ('POPTHEME_WASSUP_GF_FLAG_FIELDNAME_WHYFLAG_ID', 'input_3');
define ('POPTHEME_WASSUP_GF_FLAG_FIELDNAME_PAGEURL_ID', 'input_4');
define ('POPTHEME_WASSUP_GF_FLAG_FIELDNAME_PAGETITLE_ID', 'input_5');

define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FORM_ID', '4');	
define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FIELDNAME_NAME_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FIELDNAME_DESTINATIONEMAILS_ID', 'input_6');	
define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FIELDNAME_ADDITIONALMESSAGE_ID', 'input_5');	
define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FIELDNAME_PAGEURL_ID', 'input_3');	
define ('POPTHEME_WASSUP_GF_SHAREBYEMAIL_FIELDNAME_PAGETITLE_ID', 'input_4');

define ('POPTHEME_WASSUP_GF_NEWSLETTER_FORM_ID', '5');	
define ('POPTHEME_WASSUP_GF_NEWSLETTER_FIELDNAME_EMAIL_ID', 'input_1');	
define ('POPTHEME_WASSUP_GF_NEWSLETTER_FIELDNAME_NAME_ID', 'input_2');	