<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-searchusers-map'));
define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-allusers-map'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowers-map'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowingusers-map'));

define ('GD_TEMPLATE_SCROLLINNER_LOCATIONS', PoP_ServerUtils::get_template_definition('scrollinner-locations'));

define ('GD_TEMPLATE_SCROLLINNER_MYEVENTS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-myevents-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mypastevents-simpleviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_MYEVENTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-myevents-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mypastevents-fullviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-events-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-navigator'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-events-addons'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-addons'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-events-details'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-details'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-events-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-events-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-fullview'));

// define ('GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorevents-simpleview'));
// define ('GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorpastevents-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorevents-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorpastevents-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-events-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-thumbnail'));

define ('GD_TEMPLATE_SCROLLINNER_EVENTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-events-list'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-list'));

define ('GD_TEMPLATE_SCROLLINNER_LOCATIONS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-locations-map'));
define ('GD_TEMPLATE_SCROLLINNER_EVENTS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-events-map'));
define ('GD_TEMPLATE_SCROLLINNER_PASTEVENTS_MAP', PoP_ServerUtils::get_template_definition('scrollinner-pastevents-map'));
define ('GD_TEMPLATE_SCROLLINNER_EVENTS_HORIZONTALMAP', PoP_ServerUtils::get_template_definition('scrollinner-events-horizontalmap'));

define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_MAP', PoP_ServerUtils::get_template_definition('scrollinner-whoweare-map'));

class GD_EM_Template_Processor_CustomScrollInners extends GD_Template_Processor_ScrollInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_MAP,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_MAP,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_MAP,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_MAP,
			GD_TEMPLATE_SCROLLINNER_LOCATIONS,
			GD_TEMPLATE_SCROLLINNER_MYEVENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYEVENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_EVENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_EVENTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_EVENTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_EVENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_EVENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_EVENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_EVENTS_LIST,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_LIST,
			GD_TEMPLATE_SCROLLINNER_LOCATIONS_MAP,
			GD_TEMPLATE_SCROLLINNER_EVENTS_MAP,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_MAP,
			GD_TEMPLATE_SCROLLINNER_EVENTS_HORIZONTALMAP,
			// GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_MAP,
		);
	}

	function get_layout_grid($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_EVENTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_THUMBNAIL:

				// Allow ThemeStyle Expansive to override the grid
				return apply_filters(
					POP_HOOK_SCROLLINNER_THUMBNAIL_GRID, 
					array(
						'row-items' => 2, 
						'class' => 'col-xsm-6'
					)
				);

			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_MAP:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_MAP:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_MAP:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_MAP:

			case GD_TEMPLATE_SCROLLINNER_MYEVENTS_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_SIMPLEVIEWPREVIEW:

			case GD_TEMPLATE_SCROLLINNER_MYEVENTS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_FULLVIEWPREVIEW:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_NAVIGATOR:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_ADDONS:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_DETAILS:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_SIMPLEVIEW:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_FULLVIEW:

			case GD_TEMPLATE_SCROLLINNER_EVENTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_LIST:

			case GD_TEMPLATE_SCROLLINNER_LOCATIONS_MAP:
			case GD_TEMPLATE_SCROLLINNER_EVENTS_MAP:
			case GD_TEMPLATE_SCROLLINNER_PASTEVENTS_MAP:
			case GD_TEMPLATE_SCROLLINNER_EVENTS_HORIZONTALMAP:

			// case GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_SIMPLEVIEW:
			// case GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_SIMPLEVIEW:

			case GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_FULLVIEW:

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_MAP:
			
				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12'
				);
		}

		return parent::get_layout_grid($template_id, $atts);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		$layouts = array(
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_MAP => GD_TEMPLATE_LAYOUT_MULTIPLEUSER_MAPDETAILS,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_MAP => GD_TEMPLATE_LAYOUT_MULTIPLEUSER_MAPDETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_MAP => GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_MAPDETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_MAP => GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_MAPDETAILS,

			GD_TEMPLATE_SCROLLINNER_LOCATIONS => GD_TEMPLATE_EM_LAYOUT_LOCATIONS,

			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_EVENTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_NAVIGATOR,

			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_ADDONS,
			GD_TEMPLATE_SCROLLINNER_EVENTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_ADDONS,

			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_DETAILS,
			GD_TEMPLATE_SCROLLINNER_EVENTS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_DETAILS,

			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_EVENTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_THUMBNAIL,

			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_LIST,
			GD_TEMPLATE_SCROLLINNER_EVENTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_LIST,

			// GD_TEMPLATE_SCROLLINNER_LOCATIONS_MAP => GD_TEMPLATE_LAYOUTLOCATION_TYPEAHEAD_SELECTED,
			GD_TEMPLATE_SCROLLINNER_EVENTS_MAP => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_MAPDETAILS,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_MAP => GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_MAPDETAILS,
			GD_TEMPLATE_SCROLLINNER_EVENTS_HORIZONTALMAP => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_HORIZONTALMAPDETAILS,

			GD_TEMPLATE_SCROLLINNER_EVENTS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_SIMPLEVIEW,//GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_SIMPLEVIEW,

			GD_TEMPLATE_SCROLLINNER_EVENTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_EVENT,
			GD_TEMPLATE_SCROLLINNER_PASTEVENTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_EVENT,

			// GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_SIMPLEVIEW => GD_TEMPLATE_AUTHORLAYOUT_PREVIEWPOST_EVENT_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_SIMPLEVIEW => GD_TEMPLATE_AUTHORLAYOUT_PREVIEWPOST_PASTEVENT_SIMPLEVIEW,

			GD_TEMPLATE_SCROLLINNER_AUTHOREVENTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_EVENT,
			GD_TEMPLATE_SCROLLINNER_AUTHORPASTEVENTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_EVENT,

			GD_TEMPLATE_SCROLLINNER_MYEVENTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_EVENT_SIMPLEVIEW,//GD_TEMPLATE_LAYOUT_PREVIEWPOST_PASTEVENT_SIMPLEVIEW,
		
			GD_TEMPLATE_SCROLLINNER_MYEVENTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_EVENT,
			GD_TEMPLATE_SCROLLINNER_MYPASTEVENTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_EVENT,
		
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_MAP => GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_MAPDETAILS,
		);

		if ($template_id == GD_TEMPLATE_SCROLLINNER_LOCATIONS_MAP) {

			// $ret[] = GD_TEMPLATE_LAYOUTLOCATION_TYPEAHEAD_SELECTED;
			$ret[] = GD_TEMPLATE_MAP_SCRIPT_MARKERS;
		}
		elseif ($layout = $layouts[$template_id]) {

			$ret[] = $layout;
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_EM_Template_Processor_CustomScrollInners();