<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

class VotingProcessors_Template_SettingsProcessor extends GD_Template_SettingsProcessorBase {

	function get_checkpoints($hierarchy) {

		$ret = array();

		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE) {

			return array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOPINIONATEDVOTE => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_STATIC),
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_MYOPINIONATEDVOTES => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_EDITOPINIONATEDVOTE => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_CANEDIT),
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOREDITOPINIONATEDVOTE => Wassup_SettingsProcessor_CheckpointUtils::get_checkpoint($hierarchy, WASSUP_CHECKPOINT_LOGGEDIN_DATAFROMSERVER),
			);
		}
	
		return parent::get_checkpoints($hierarchy);
	}

	function get_page_blockgroups($hierarchy, $include_common = true) {

		$ret = array();

		// Page or Blocks inserted in Home
		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE || $hierarchy == GD_SETTINGS_HIERARCHY_HOME) {

			$pageblockgroups = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYORGANIZATIONS,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_BYINDIVIDUALS,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_GENERAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_GENERAL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_GENERAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_GENERAL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_GENERAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_GENERAL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_ARTICLE => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_PRO_ARTICLE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_ARTICLE => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_AGAINST_ARTICLE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_ARTICLE => GD_TEMPLATE_BLOCKGROUP_TABPANEL_OPINIONATEDVOTES_NEUTRAL_ARTICLE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_MYOPINIONATEDVOTES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_MYOPINIONATEDVOTES,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		// Author page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_AUTHOR) {

			$pageblockgroups = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHOROPINIONATEDVOTES,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHOROPINIONATEDVOTES_PRO,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHOROPINIONATEDVOTES_NEUTRAL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCKGROUP_TABPANEL_AUTHOROPINIONATEDVOTES_AGAINST,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		// Single page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_SINGLE) {

			$pageblockgroups = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCKGROUP_TABPANEL_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		return $ret;
	}

	function get_page_blocks($hierarchy, $include_common = true) {

		$ret = array();

		// $include_common: used to tell if we include also the common blocks in the response.
		// These common blocks are needed to produce the dataload-source of, eg, the Navigator Blocks, even
		// when first loading the website on an Author or Single page. Without the Navigator blocks placed in
		// common, then we can't get their dataload-source.
		// However, when generating the cache (file generator.php) these are not needed, so then skip them
		// Common blocks
		if ($include_common) {

			// Default
			$pageblocks_allothers = array(
				
				// Add Content
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOPINIONATEDVOTE => GD_TEMPLATE_BLOCK_OPINIONATEDVOTE_CREATE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_EDITOPINIONATEDVOTE => GD_TEMPLATE_BLOCK_OPINIONATEDVOTE_UPDATE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOREDITOPINIONATEDVOTE => $_REQUEST['origin'] == GD_DATALOAD_IOHANDLER_ADDPOSTOPINIONATEDVOTEORIGIN_SINGLEPOSTOPINIONATEDVOTE ? GD_TEMPLATE_BLOCK_SINGLEPOSTOPINIONATEDVOTE_CREATEORUPDATE : GD_TEMPLATE_BLOCK_OPINIONATEDVOTE_CREATEORUPDATE,
			);
			foreach ($pageblocks_allothers as $page => $block) {
				$ret[$page]['blocks']['default'] = $block;
			}

			// Actions 
			$pageactions = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOPINIONATEDVOTE => GD_TEMPLATE_ACTION_OPINIONATEDVOTE_CREATE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_EDITOPINIONATEDVOTE => GD_TEMPLATE_ACTION_OPINIONATEDVOTE_UPDATE,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOREDITOPINIONATEDVOTE => $_REQUEST['origin'] == GD_DATALOAD_IOHANDLER_ADDPOSTOPINIONATEDVOTEORIGIN_SINGLEPOSTOPINIONATEDVOTE ? GD_TEMPLATE_ACTION_SINGLEPOSTOPINIONATEDVOTE_CREATEORUPDATE : GD_TEMPLATE_ACTION_OPINIONATEDVOTE_CREATEORUPDATE,
			);
			foreach ($pageactions as $page => $action) {
				$ret[$page]['action'] = $action;
			}
		}

		// Blocks in the homepage that need to access a PAGE dataload_source
		if ($hierarchy == GD_SETTINGS_HIERARCHY_HOME || $hierarchy == GD_SETTINGS_HIERARCHY_PAGE) {
	
			$default_format_votes = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_VOTINGPROCESSORS_SCREEN_OPINIONATEDVOTES);
			$default_format_myvotes = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_VOTINGPROCESSORS_SCREEN_MYOPINIONATEDVOTES);
			
			$pageblocks_carousels = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_CAROUSEL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_CAROUSEL,
			);
			foreach ($pageblocks_carousels as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_CAROUSEL] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_CAROUSEL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
		// }

		// if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE) {
	
			$pageblocks_typeahead = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_TYPEAHEAD,
			);
			foreach ($pageblocks_typeahead as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_TYPEAHEAD] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_TYPEAHEAD) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}

			$pageblocks_navigator = array(						
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_NAVIGATOR,
			);
			foreach ($pageblocks_navigator as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_NAVIGATOR] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_NAVIGATOR) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}

			$pageblocks_addons = array(						
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_ADDONS,
			);
			foreach ($pageblocks_addons as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_ADDONS] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_ADDONS) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}

			$pageblocks_fullview = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_FULLVIEW,
			);
			foreach ($pageblocks_fullview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_thumbnail = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_THUMBNAIL,
			);
			foreach ($pageblocks_thumbnail as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_THUMBNAIL] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_THUMBNAIL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_list = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYORGANIZATIONS_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_BYINDIVIDUALS_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_GENERAL_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_GENERAL_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_GENERAL  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_GENERAL_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_PRO_ARTICLE_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_AGAINST_ARTICLE_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_ARTICLE  => GD_TEMPLATE_BLOCK_OPINIONATEDVOTES_NEUTRAL_ARTICLE_SCROLL_LIST,
			);
			foreach ($pageblocks_list as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_LIST] = $block;

				if ($default_format_votes == GD_TEMPLATEFORMAT_LIST) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_mycontent = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_MYOPINIONATEDVOTES => GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_TABLE_EDIT,
			);
			foreach ($pageblocks_mycontent as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_TABLE] = $block;

				if ($default_format_myvotes == GD_TEMPLATEFORMAT_TABLE) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_mycontent_previews = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_MYOPINIONATEDVOTES => GD_TEMPLATE_BLOCK_MYOPINIONATEDVOTES_SCROLL_FULLVIEWPREVIEW,
			);
			foreach ($pageblocks_mycontent_previews as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_myvotes == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
		}

		// Author page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_AUTHOR) {

			$default_format_authorvotes = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_VOTINGPROCESSORS_SCREEN_AUTHOROPINIONATEDVOTES);
			
			$pageblocks_fullview = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_PRO_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_NEUTRAL_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_AGAINST_SCROLL_FULLVIEW,
			);
			foreach ($pageblocks_fullview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_authorvotes == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_thumbnail = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_PRO_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_NEUTRAL_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_AGAINST_SCROLL_THUMBNAIL,
			);
			foreach ($pageblocks_thumbnail as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_THUMBNAIL] = $block;

				if ($default_format_authorvotes == GD_TEMPLATEFORMAT_THUMBNAIL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_list = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_PRO_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_NEUTRAL_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_AGAINST_SCROLL_LIST,
			);
			foreach ($pageblocks_list as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_LIST] = $block;

				if ($default_format_authorvotes == GD_TEMPLATEFORMAT_LIST) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_carousels = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES  => GD_TEMPLATE_BLOCK_AUTHOROPINIONATEDVOTES_CAROUSEL,
			);
			foreach ($pageblocks_carousels as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_CAROUSEL] = $block;

				if ($default_format_authorvotes == GD_TEMPLATEFORMAT_CAROUSEL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
		}

		// Single page blocks
		elseif ($hierarchy == GD_SETTINGS_HIERARCHY_SINGLE) {

			$default_format_singlevotes = PoPTheme_Wassup_Utils::get_defaultformat_by_screen(POP_VOTINGPROCESSORS_SCREEN_SINGLEOPINIONATEDVOTES);
			
			$pageblocks_fullview = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_FULLVIEW,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_FULLVIEW,
			);
			foreach ($pageblocks_fullview as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_FULLVIEW] = $block;

				if ($default_format_singlevotes == GD_TEMPLATEFORMAT_FULLVIEW) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_thumbnail = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_THUMBNAIL,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_THUMBNAIL,
			);
			foreach ($pageblocks_thumbnail as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_THUMBNAIL] = $block;

				if ($default_format_singlevotes == GD_TEMPLATEFORMAT_THUMBNAIL) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
			$pageblocks_list = array(
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_PRO_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_AGAINST_SCROLL_LIST,
				POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL => GD_TEMPLATE_BLOCK_SINGLERELATEDOPINIONATEDVOTECONTENT_NEUTRAL_SCROLL_LIST,
			);
			foreach ($pageblocks_list as $page => $block) {
				$ret[$page]['blocks'][GD_TEMPLATEFORMAT_LIST] = $block;

				if ($default_format_singlevotes == GD_TEMPLATEFORMAT_LIST) {
					$ret[$page]['blocks']['default'] = $block;
				}
			}
		}

		return $ret;	
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new VotingProcessors_Template_SettingsProcessor();
