########################################################################
# 
# Variables:
#   - customPostId: The custom post with the origin language, from where all translations will be made
#   - translateDefaultLanguageOnly: Indicate if only execute the translation when the origin post has the default language of the site. It is `true` by default.
#   - translateFromLanguage: Only execute the translation when the origin post has some provided language. It applies only when `translateDefaultLanguageOnly` is `false`
#   - includeLanguagesToTranslate: Limit languages to execute the translation for. If empty, all languages are included
#   - excludeLanguagesToTranslate: Exclude languages from executing the translation
#
# *********************************************************************
#
# === Description ===
#
# This Persisted GraphQL query is an integration for Polylang,
# to create the missing translation posts.
#
# It takes an origin post, and duplicates it into all the other
# languages defined in Polylang for which there is no post yet.
#
# By default, the origin post must have the default language
# of the site, or the logic will not be executed.
# To execute for any language, pass variable
# `$translateDefaultLanguageOnly` with `false`.
#
# Additionally, execute the logic only when the origin post
# has a specific language by providing `$translateFromLanguage`
# with the language code (for instance, `"en"`). It applies only
# when `$translateDefaultLanguageOnly` is `false`.
#
# To limit for what languages to execute the logic, pass
# variables `$includeLanguagesToTranslate` (if empty, all languages
# will be included) and `$excludeLanguagesToTranslate`.
#
########################################################################
query InitializeVariables
  @configureWarningsOnExportingDuplicateVariable(enabled: false)
{
  emptyBool: _echo(value: false)
    @export(as: "canTranslateOriginPost")
    @export(as: "hasMissingTranslationLanguages")
    @export(as: "hasCreatedTranslationPosts")
    @remove

  emptyArray: _echo(value: [])
    @export(as: "createdTranslationPostIDs")
    @remove
}

query ExportOriginCustomPost(
  $customPostId: ID!
  $includeLanguagesToTranslate: [String!]
  $excludeLanguagesToTranslate: [String!]
)
  @depends(on: "InitializeVariables")
{
  defaultLanguage: polylangDefaultLanguage {
    code @export(as: "defaultLanguage")
  }

  enabledLanguages: polylangLanguages(filter: { enabled: true }) {
    code @export(as: "enabledLanguages", type: LIST)
  }

  originCustomPost: customPost(by: { id: $customPostId }, status: any) {
    __typename
    ...on CustomPost {
      id

      
      ################################################################
      # Data needed to duplicate post for missing languages
      ################################################################
      originCustomPostType: customPostType @export(as: "originCustomPostType")
      originCustomPostAuthor: author @export(as: "originCustomPostAuthorID") {
        id
      }
      originCustomPostCategories: categories @export(as: "originCustomPostCategoryIDs") {
        id
      }
      originCustomPostRawContent: rawContent @export(as: "originCustomPostRawContent")
      originCustomPostRawExcerpt: rawExcerpt @export(as: "originCustomPostRawExcerpt")
      originCustomPostFeaturedImage: featuredImage @export(as: "originCustomPostFeaturedImageID") {
        id
      }
      originCustomPostTags: tags @export(as: "originCustomPostTagIDs") {
        id
      }
      originCustomPostRawTitle: rawTitle @export(as: "originCustomPostRawTitle")
      ################################################################


      polylangLanguage {
        code @export(as: "fromLanguage")
      }
      

      polylangTranslationLanguageIDs(filter: {
        includeSelf: true
        includeLanguages: $includeLanguagesToTranslate
        excludeLanguages: $excludeLanguagesToTranslate
      })
        @remove
      customPostIDTranslationLanguageIDs: _echo(value: $__polylangTranslationLanguageIDs)
        @default(value: {})
        @export(as: "customPostIDTranslationLanguageIDs")
    }
  }

  hasOriginCustomPost: _notNull(value: $__originCustomPost)
    @export(as: "hasOriginCustomPost")
}

query ExportOriginCustomPostCanBeTranslated(
  $translateDefaultLanguageOnly: Boolean! = true
  $translateFromLanguage: String
)
  @depends(on: "ExportOriginCustomPost")
  @include(if: $hasOriginCustomPost)
{
  originCustomPostHasDefaultLanguage: _equals(
    value1: $defaultLanguage,
    value2: $fromLanguage
  )

  isTranslateFromLanguageProvided: _notEmpty(value: $translateFromLanguage)

  originCustomPostHasSpecificLanguage: _equals(
    value1: $translateFromLanguage,
    value2: $fromLanguage
  )

  canTranslateOriginPostFromSpecificLanguage: _if(
    condition: $__isTranslateFromLanguageProvided,
    then: $__originCustomPostHasSpecificLanguage,
    else: true
  )

  canTranslateOriginPost: _if(
    condition: $translateDefaultLanguageOnly,
    then: $__originCustomPostHasDefaultLanguage,
    else: $__canTranslateOriginPostFromSpecificLanguage
  )
    @export(as: "canTranslateOriginPost")
}

query ExportMissingTranslationLanguages(
  $includeLanguagesToTranslate: [String!]! = []
  $excludeLanguagesToTranslate: [String!]! = []
)
  @depends(on: "ExportOriginCustomPostCanBeTranslated")
  @include(if: $canTranslateOriginPost)
{
  currentlyExistingTranslationLanguages: _objectProperties(object: $customPostIDTranslationLanguageIDs)
  missingTranslationLanguagesWithoutFilteringByInclude: _arrayDiff(
    arrays: [
      $enabledLanguages,
      $__currentlyExistingTranslationLanguages,
      $excludeLanguagesToTranslate
    ]
  )
  hasIncludeLanguagesToTranslate: _notEmpty(value: $includeLanguagesToTranslate)
  missingTranslationLanguagesWithFilteringByInclude: _arrayIntersect(
    arrays: [
      $__missingTranslationLanguagesWithoutFilteringByInclude,
      $includeLanguagesToTranslate
    ]
  )
  missingTranslationLanguages: _if(
    condition: $__hasIncludeLanguagesToTranslate,
    then: $__missingTranslationLanguagesWithFilteringByInclude,
    else: $__missingTranslationLanguagesWithoutFilteringByInclude
  )
    @export(as: "missingTranslationLanguages")
  hasMissingTranslationLanguages: _notEmpty(value: $__missingTranslationLanguages)
    @export(as: "hasMissingTranslationLanguages")
}

query CreateTranslationPostInputsForMissingLanguages
  @depends(on: "ExportMissingTranslationLanguages")
  @include(if: $hasMissingTranslationLanguages)
{
  createTranslationPostInputs: _echo(value: $missingTranslationLanguages)
    @underEachArrayItem(
      passValueOnwardsAs: "languageCode"
      affectDirectivesUnderPos: [1, 2]
    )
      @applyField(
        name: "_sprintf"
        arguments: {
          string: "%s (%s)"
          values: [$originCustomPostRawTitle, $languageCode]
        }
        passOnwardsAs: "originCustomPostRawTitleForLanguage"
      )
      @applyField(
        name: "_echo",
        arguments: {
          value: {
            customPostType: $originCustomPostType,
            status: draft,
            authorBy: {
              id: $originCustomPostAuthorID
            },
            categoriesBy: {
              ids: $originCustomPostCategoryIDs
            },
            contentAs: {
              html: $originCustomPostRawContent
            },
            excerpt: $originCustomPostRawExcerpt
            featuredImageBy: {
              id: $originCustomPostFeaturedImageID
            },
            tagsBy: {
              ids: $originCustomPostTagIDs
            },
            title: $originCustomPostRawTitleForLanguage,
            polylangLanguageBy: { code: $languageCode }
          }
        },
        setResultInResponse: true
      )
    @export(as: "createTranslationPostInputs")
}

mutation CreateTranslationPostForMissingLanguages
  @depends(on: "CreateTranslationPostInputsForMissingLanguages")
  @include(if: $hasMissingTranslationLanguages)
{
  translationPosts: createCustomPosts(inputs: $createTranslationPostInputs) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    customPost {
      __typename
      ...on CustomPost {
        id
          @export(as: "createdTranslationPostIDs", type: LIST)
        hasCreatedTranslationPosts: _echo(value: true)
          @export(as: "hasCreatedTranslationPosts")
          @remove
        title
        slug
        polylangLanguage {
          code
        }
      }
    }    
  }
}

query ExportAllTranslationPosts
  @depends(on: "CreateTranslationPostForMissingLanguages")
  @include(if: $hasCreatedTranslationPosts)
{
  currentlyExistingTranslationPostIDs: _objectValues(object: $customPostIDTranslationLanguageIDs)
  allTranslationPostIDs: _arrayMerge(
    arrays: [
      $__currentlyExistingTranslationPostIDs,
      $createdTranslationPostIDs,
    ]
  )
    @export(as: "allTranslationPostIDs")
}

mutation CreateMissingTranslationPostsForPolylang
  @depends(on: "ExportAllTranslationPosts")
  @include(if: $hasCreatedTranslationPosts)
{
  polylangSaveCustomPostTranslationAssociation(input: {
    ids: $allTranslationPostIDs
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
  }
}