########################################################################
# 
# Variables:
#   - $username: The username to log into the external site
#   - $appPassword: The application password to log into the external site
#   - $externalSiteURL: The URL of the external site, where all pages will be (translated and) created
#   - (Optional) $externalSiteGraphQLEndpointPath: Path to the GraphQL endpoint on the external site, with the "nested mutations" feature enabled
#
# *********************************************************************
#
# === Description ===
#
# This Persisted GraphQL query works on a WordPress Multisite network,
# to create a Multilingual site, where every site in the network
# is the translation for some language.
# 
# It must be executed on the master site, which must have the PRO plugin.
# All other sites in the network can have the free Gato GraphQL plugin.
#
# The query first connects to the external site, and retrieves its language.
# Then it grabs all the pages from the master site, and it translates them
# all at once (in bulk) to that language, by executing a single call to the
# Google Translate API.
#
# Finally it logs into the external site again, and creates all those pages
# with all the translations.
#
########################################################################

