########################################################################
# 
# Variables:
#   - postId: The ID of the post to do the search and replace
#   - searchRegex: The list of regex to search
#   - replaceWith: The list of strings to replace with
# 
# *********************************************************************
#
# === Description ===
#
# This Persisted GraphQL query retrieves a post, replaces all
# matches of a list of regex strings with a list of strings
# in the post's content and title, and stores the post again.
#
# *********************************************************************
#
# More info:
#   - https://gatographql.com/tutorial/search-replace-and-store-again/
#
########################################################################

query GetPostData(
  $postId: ID!
  $searchRegex: [String!]!,
  $replaceWith: [String!]!
) {
  post(by: { id: $postId }) {
    title
    adaptedPostTitle: _strRegexReplaceMultiple(
      searchRegex: $searchRegex
      replaceWith: $replaceWith
      in: $__title
    )
      @export(as: "adaptedPostTitle")

    rawContent
    adaptedRawContent: _strRegexReplaceMultiple(
      searchRegex: $searchRegex
      replaceWith: $replaceWith
      in: $__rawContent
    )
      @export(as: "adaptedRawContent")
  }
}

mutation UpdatePost($postId: ID!)
  @depends(on: "GetPostData")
{
  updatePost(input: {
    id: $postId,
    title: $adaptedPostTitle,
    contentAs: { html: $adaptedRawContent },
  }) {
    status
    errors {
      __typename
      ...on ErrorPayload {
        message
      }
    }
    post {
      id
      title
      rawContent
    }
  }
}