########################################################################
#
# This Persisted GraphQL query  first filters all posts containing
# "https://my-old-domain.com" in its content, and replaces this string
# with "https://my-new-domain.com"
#
# *********************************************************************
# 
# Variables:
#   - oldDomain: The old domain
#   - newDomain: The new domain
#
# *********************************************************************
# 
# More info:
#   - https://gatographql.com/recipes/site-migrations/
#
########################################################################

mutation ReplaceOldWithNewDomainInPosts(
  $oldDomain: String!,
  $newDomain: String!
) {
  posts(
    filter: {
      search: $oldDomain
    },
    pagination: {
      limit: -1
    }
  ) {
    id
    rawContent
    adaptedRawContent: _strReplace(
      search: $oldDomain
      replaceWith: $newDomain
      in: $__rawContent
    )
    update(input: {
      contentAs: { html: $__adaptedRawContent }
    }) {
      status
      errors {
        __typename
        ...on ErrorPayload {
          message
        }
      }
      post {
        id
        rawContent
      }
    }
  }
}