########################################################################
# 
# Variables:
#   - postId: The post with the origin language, from where to trigger the featured image updates
#   - statusToUpdate: The status that the translation posts must have to be updated. It is `draft` by default. Pass `any` for any status.
#   - triggerUpdateFromDefaultLanguageOnly: Indicate if to only execute the featured image update when the origin post has the default language of the site. It is `true` by default.
#
# *********************************************************************
#
# === Description ===
#
# This Persisted GraphQL query is an integration for Polylang.
#
# It takes an origin post, queries its featured image,
# and updates its translation posts with the corresponding
# featured image for the corresponding language,
# as set-up via Polylang.
#
# All translation posts must have the  `draft` status
# to be updated. To update posts with any other status, use
# variable `$statusToUpdate` (for instance, passing value
# `publish`, `pending` or `any`)
#
# By default, the origin post must have the default language
# of the site, or the update will not be executed.
# To trigger the update from any language, pass variable
# `$triggerUpdateFromDefaultLanguageOnly` with `false`.
#
########################################################################
query InitializeVariables
  @configureWarningsOnExportingDuplicateVariable(enabled: false)
{
  emptyString: _echo(value: null)
    @export(as: "fromLanguage")

  emptyBool: _echo(value: false)
    @export(as: "executeUpdate")
    @export(as: "hasFeaturedImageTranslations")
  
  emptyArray: _echo(value: [])
    @export(as: "originPostTranslationPostIds")
  
  emptyJSON: _echo(value: {})
    @export(as: "featuredImageTranslationLanguageIDs")
}

query ExportDataFromOriginPost($postId: ID!)
  @depends(on: "InitializeVariables")
{
  defaultLanguage: polylangDefaultLanguage
    @export(as: "defaultLanguage")

  originPost: post(by: { id: $postId }, status: any) {
    id

    polylangLanguage
      @export(as: "fromLanguage")
    
    polylangTranslationLanguageIDs
    translationPostIds: _objectValues(object: $__polylangTranslationLanguageIDs)
      @export(as: "originPostTranslationPostIds")

    featuredImage {
      id

      polylangTranslationLanguageIDs
        @export(as: "featuredImageTranslationLanguageIDs")

      hasTranslationPosts: _notEmpty(value: $__polylangTranslationLanguageIDs)
        @export(as: "hasFeaturedImageTranslations")
    }
  }
}

query FilterTranslationPostsToUpdate(
  $statusToUpdate: CustomPostStatusEnum! = draft
  $triggerUpdateFromDefaultLanguageOnly: Boolean! = true
)
  @depends(on: "ExportDataFromOriginPost")
  @include(if: $hasFeaturedImageTranslations)
{
  translationPosts: posts(filter: { ids: $originPostTranslationPostIds, status: $statusToUpdate } ) {
    id
  }

  hasTranslationPosts: _notEmpty(value: $__translationPosts)

  originPostHasDefaultLanguage: _equals(
    value1: $defaultLanguage,
    value2: $fromLanguage
  )

  canTriggerUpdateFromOriginPost: _if(
    condition: $triggerUpdateFromDefaultLanguageOnly,
    then: $__originPostHasDefaultLanguage,
    else: true
  )

  executeUpdate: _and(values: [
    $__hasTranslationPosts,
    $__canTriggerUpdateFromOriginPost
  ])
    @export(as: "executeUpdate")
}

mutation UpdateFeaturedImageForTranslationPosts(
  $statusToUpdate: CustomPostStatusEnum! = draft
)
  @depends(on: "FilterTranslationPostsToUpdate")
  @include(if: $executeUpdate)
{
  updateTranslationPosts: posts(filter: { ids: $originPostTranslationPostIds, status: $statusToUpdate } ) {
    id

    polylangLanguage

    translationFeaturedImageID: _objectProperty(
      object: $featuredImageTranslationLanguageIDs,
      by: {
        key: $__polylangLanguage
      }
    )
      
    setFeaturedImage(input: {
      mediaItemBy: {
        id: $__translationFeaturedImageID
      }
    }) {
      status
      errors {
        __typename
        ...on ErrorPayload {
          message
        }
      }
      customPost {
        __typename
        ...on CustomPost {
          featuredImage {
            id
            polylangLanguage
          }
        }
      }
    }
  }
}
