########################################################################
# 
# Variables:
#   - content: The .po/.pot Poedit (https://poedit.net/) file content
#   - toLang: The language code to translate to, from Google Translate (https://cloud.google.com/translate/docs/languages)
#
# *********************************************************************
#
# === Description ===
#
# This Persisted GraphQL query translates the empty strings from a
# Poedit file (by executing a single call to the Google Translate API),
# and adds those translations in the corresponding entry.
#
########################################################################

query InitializeVariables
  @configureWarningsOnExportingDuplicateVariable(enabled: false)
{
  emptyArray: _echo(value: [])
    @export(as: "stringsToTranslate")
}

query ExportData($fileURL: URL!)
  @depends(on: "InitializeVariables")
{
  _sendHTTPRequest(input: { url: $fileURL, method: GET }) {
    content: body
      @export(as: "content")
  }
  regex: _echo(value: "#msgid \"(.+)\"\nmsgstr \"\"#")
    @export(as: "regex")
}

query ExtractStringsToTranslate
  @depends(on: "ExportData")
{
  stringsToTranslateMatches: _strRegexFindMatches(
    string: $content,
    regex: $regex
  )
  stringsToTranslate: _arrayItem(
    array: $__stringsToTranslateMatches,
    position: 1
  )
     @export(as: "stringsToTranslate")
}

query TranslateStrings(
  $fromLang: String
  $toLang: String!
)
  @depends(on: "ExtractStringsToTranslate")
{  
  translatedStrings: _echo(value: $stringsToTranslate)
    @underEachArrayItem
      @strTranslate(from: $fromLang, to: $toLang)
    @export(as: "translatedStrings")
}

query ExportReplacements
  @depends(on: "TranslateStrings")
{
  entriesCount: _arrayLength(array: $translatedStrings)
  replaceFrom: _arrayPad(
    array: [],
    length: $__entriesCount,
    value: $regex
  )
    @export(as: "replaceFrom")
  replaceWith: _echo(value: $translatedStrings)
    @underEachArrayItem(
      affectDirectivesUnderPos: [1, 2]
    )
      @strPrepend(string: "#msgid \"$1\"\nmsgstr \"")
      @strAppend(string: "\"#")
    @export(as: "replaceWith")
}

query GenerateTranslatedPoeditFile
  @depends(on: "ExportReplacements")
{
  translatedContent: _strRegexReplaceMultiple(
    in: $content,
    searchRegex: $replaceFrom,
    replaceWith: $replaceWith,
    limit: 1
  )
}