<?php

// Placeholders for images
//--------------------------------------------------------
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_IMAGE_NOFEATUREDIMAGEOPINIONATEDVOTEPOST', false);

// Categories
//--------------------------------------------------------
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_CAT_OPINIONATEDVOTES', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_CAT_OPINIONATEDVOTES_PRO', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_CAT_OPINIONATEDVOTES_AGAINST', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_CAT_OPINIONATEDVOTES_NEUTRAL', false);

// Content
//--------------------------------------------------------
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_MYOPINIONATEDVOTES', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOPINIONATEDVOTE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_EDITOPINIONATEDVOTE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_ADDOREDITOPINIONATEDVOTE', false);

define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_GENERAL', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_GENERAL', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_GENERAL', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_PRO_ARTICLE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_AGAINST_ARTICLE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_NEUTRAL_ARTICLE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYORGANIZATIONS', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_PAGE_OPINIONATEDVOTES_BYINDIVIDUALS', false);

// Locations
//--------------------------------------------------------
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_MALAYSIA', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_SINGAPORE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_BRUNEI', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_CHILE', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_NEWZEALAND', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_AUSTRALIA', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_CANADA', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_JAPAN', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_MEXICO', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_PERU', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_UNITEDSTATES', false);
define ('POPTHEME_WASSUP_VOTINGPROCESSORS_LOCATION_VIETNAM', false);