<?php

declare(strict_types=1);

namespace PoPCMSSchema\Comments;

class Environment
{
    public final const ROOT_COMMENT_LIST_DEFAULT_LIMIT = 'ROOT_COMMENT_LIST_DEFAULT_LIMIT';
    public final const CUSTOMPOST_COMMENT_OR_COMMENT_RESPONSE_LIST_DEFAULT_LIMIT = 'CUSTOMPOST_COMMENT_OR_COMMENT_RESPONSE_LIST_DEFAULT_LIMIT';
    public final const COMMENT_LIST_MAX_LIMIT = 'COMMENT_LIST_MAX_LIMIT';
    public final const TREAT_COMMENT_STATUS_AS_ADMIN_DATA = 'TREAT_COMMENT_STATUS_AS_ADMIN_DATA';
}
