<?php

// Categories
//--------------------------------------------------------
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS00', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS01', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS02', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS03', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS04', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS05', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS06', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS07', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS08', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS09', false);

define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS10', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS11', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS12', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS13', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS14', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS15', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS16', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS17', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS18', false);
define('POP_NOSEARCHCATEGORYPOSTS_CAT_NOSEARCHCATEGORYPOSTS19', false);
