query TypesInSchema {
    __schema {
        types {
            name
            possibleTypes {
                name
            }
            fields {
                name
                type {
                    name
                }
            }
        }
    }
}
