<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_LOCATIONPOST', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-locationpost'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_STORY', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-story'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_DISCUSSION', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-discussion'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_BLOG', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-blog'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_ANNOUNCEMENT', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-announcement'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_FEATURED', PoP_ServerUtils::get_template_definition('layout-postsidebar-vertical-featured'));

define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LOCATIONPOST', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-locationpost'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_STORY', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-story'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_DISCUSSION', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-discussion'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_BLOG', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-blog'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_ANNOUNCEMENT', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-announcement'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_FEATURED', PoP_ServerUtils::get_template_definition('layout-postsidebar-horizontal-featured'));

define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_LOCATIONPOST', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-locationpost'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_STORY', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-story'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_DISCUSSION', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-discussion'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_BLOG', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-blog'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_ANNOUNCEMENT', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-announcement'));
define ('GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_FEATURED', PoP_ServerUtils::get_template_definition('layout-postsidebarcompact-horizontal-featured'));

class GD_Custom_Template_Processor_CustomPostLayoutSidebars extends GD_Template_Processor_SidebarsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_FEATURED,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_FEATURED,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_FEATURED,
			
		);
	}

	function get_inner_template($template_id) {

		$sidebarinners = array(
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_LOCATIONPOST => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_STORY => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_DISCUSSION => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_BLOG => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_ANNOUNCEMENT => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_FEATURED => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_VERTICAL_FEATURED,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LOCATIONPOST => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_STORY => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_DISCUSSION => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_BLOG => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_ANNOUNCEMENT => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_FEATURED => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_HORIZONTAL_FEATURED,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_LOCATIONPOST => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_LOCATIONPOST,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_STORY => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_STORY,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_DISCUSSION => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_DISCUSSION,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_BLOG => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_BLOG,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_ANNOUNCEMENT => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_ANNOUNCEMENT,
			GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_FEATURED => GD_TEMPLATE_LAYOUT_POSTSIDEBARINNER_COMPACTHORIZONTAL_FEATURED,
		);

		if ($inner = $sidebarinners[$template_id]) {
			return $inner;
		}

		return parent::get_inner_template($template_id);
	}

	function init_atts($template_id, &$atts) {

		switch ($template_id) {

			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_LOCATIONPOST:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_STORY:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_DISCUSSION:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_BLOG:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_ANNOUNCEMENT:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_VERTICAL_FEATURED:

				$this->append_att($template_id, $atts, 'class', 'vertical');
				break;

			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_LOCATIONPOST:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_STORY:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_DISCUSSION:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_BLOG:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_ANNOUNCEMENT:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBAR_HORIZONTAL_FEATURED:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_LOCATIONPOST:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_STORY:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_DISCUSSION:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_BLOG:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_ANNOUNCEMENT:
			case GD_TEMPLATE_LAYOUT_POSTSIDEBARCOMPACT_HORIZONTAL_FEATURED:

				$this->append_att($template_id, $atts, 'class', 'horizontal');
				break;
		}

		return parent::init_atts($template_id, $atts);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_CustomPostLayoutSidebars();