<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Data Load Library
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('POP_RESOURCELOADER_TEMPLATE_ALERT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_ALERT));
define ('POP_RESOURCELOADER_TEMPLATE_BLOCK_BARE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BLOCK_BARE));
define ('POP_RESOURCELOADER_TEMPLATE_BLOCK_DESCRIPTION', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BLOCK_DESCRIPTION));
define ('POP_RESOURCELOADER_TEMPLATE_BLOCKGROUP_BLOCKUNITS', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BLOCKGROUP_BLOCKUNITS));
define ('POP_RESOURCELOADER_TEMPLATE_BUTTONGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BUTTONGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_BUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_BUTTONINNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_BUTTONINNER));
define ('POP_RESOURCELOADER_TEMPLATE_CAROUSEL', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CAROUSEL));
define ('POP_RESOURCELOADER_TEMPLATE_CAROUSEL_CONTROLS', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CAROUSEL_CONTROLS));
define ('POP_RESOURCELOADER_TEMPLATE_CAROUSEL_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CAROUSEL_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_CODE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CODE));
define ('POP_RESOURCELOADER_TEMPLATE_CONDITIONWRAPPER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONDITIONWRAPPER));
define ('POP_RESOURCELOADER_TEMPLATE_CONTENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTENT));
define ('POP_RESOURCELOADER_TEMPLATE_CONTENTMULTIPLE_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTENTMULTIPLE_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_CONTENTSINGLE_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTENTSINGLE_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROL_ANCHOR', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROL_ANCHOR));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROL_BUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROL_BUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROL_DROPDOWNBUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROL_DROPDOWNBUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROL_RADIOBUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROL_RADIOBUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROLBUTTONGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROLBUTTONGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_CONTROLGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_CONTROLGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_DIVIDER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_DIVIDER));
define ('POP_RESOURCELOADER_TEMPLATE_FETCHMORE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FETCHMORE));
define ('POP_RESOURCELOADER_TEMPLATE_FORM', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORM));
define ('POP_RESOURCELOADER_TEMPLATE_FORM_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORM_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_BUTTONGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_BUTTONGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CAPTCHA', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_CAPTCHA));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CHECKBOX', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_CHECKBOX));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_DATERANGE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_DATERANGE));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FETCHLINKTYPEAHEAD', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_FETCHLINKTYPEAHEAD));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_INPUTGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_INPUTGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_SELECT));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEAD', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEAD));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_TEXT));
define ('POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXTAREA', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMCOMPONENT_TEXTAREA));
define ('POP_RESOURCELOADER_TEMPLATE_FORMGROUP', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_FORMGROUP));
define ('POP_RESOURCELOADER_TEMPLATE_HIDEIFEMPTY', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_HIDEIFEMPTY));
define ('POP_RESOURCELOADER_TEMPLATE_LATESTCOUNT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LATESTCOUNT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MAXHEIGHT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MAXHEIGHT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_CONTENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_CONTENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_LINKCONTENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_LINKCONTENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_APPENDSCRIPT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_APPENDSCRIPT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_CONTACT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_AUTHOR_CONTACT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_USERPHOTO', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_AUTHOR_USERPHOTO));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHORCONTENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_AUTHORCONTENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_CATEGORIES', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_CATEGORIES));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_COMMENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_COMMENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_DATAQUERY_UPDATEDATA', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_DATAQUERY_UPDATEDATA));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_EMBEDPREVIEW', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_EMBEDPREVIEW));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_INITJSDELAY', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_INITJSDELAY));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLOBJECTTITLE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_FULLOBJECTTITLE));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLVIEW', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_FULLVIEW));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLUSER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_FULLUSER));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_LATESTCOUNTSCRIPT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_LATESTCOUNTSCRIPT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MARKER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MARKER));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_ANCHOR', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_ANCHOR));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWN', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWN));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWNBUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWNBUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_INDENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_INDENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_MULTITARGETINDENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MENU_MULTITARGETINDENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACK', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACK));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACKFRAME));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_MULTIPLE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_MULTIPLE));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_PAGETAB', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_PAGETAB));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_POPOVER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_POPOVER));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTSTATUSDATE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_POSTSTATUSDATE));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAGINFO', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_TAGINFO));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTTHUMB', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_POSTTHUMB));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWPOST', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_PREVIEWPOST));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWUSER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_PREVIEWUSER));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_SCRIPTFRAME', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_SCRIPTFRAME));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_SEGMENTEDBUTTON_LINK', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_SEGMENTEDBUTTON_LINK));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_STYLES', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_STYLES));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_SUBCOMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_SUBCOMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAG', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_TAG));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERAVATAR', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_USERAVATAR));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERPOSTINTERACTION', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUT_USERPOSTINTERACTION));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORAVATAR', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORAVATAR));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORNAME', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORNAME));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_DATE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_DATE));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_STATUS', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_STATUS));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_COMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_COMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_SELECTED', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_SELECTED));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTTAG_TYPEAHEAD_COMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTTAG_TYPEAHEAD_COMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_MENTION_COMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTUSER_MENTION_COMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_QUICKLINKS', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTUSER_QUICKLINKS));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_COMPONENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_COMPONENT));
define ('POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_SELECTED', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_SELECTED));
define ('POP_RESOURCELOADER_TEMPLATE_MESSAGE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_MESSAGE));
define ('POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_MESSAGEFEEDBACK));
define ('POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_MESSAGEFEEDBACK_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_MULTIPLE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_MULTIPLE));
define ('POP_RESOURCELOADER_TEMPLATE_PAGESECTION_PLAIN', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_PAGESECTION_PLAIN));
define ('POP_RESOURCELOADER_TEMPLATE_SCRIPT_APPENDCOMMENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SCRIPT_APPENDCOMMENT));
define ('POP_RESOURCELOADER_TEMPLATE_SCRIPT_LAZYLOADINGREMOVE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SCRIPT_LAZYLOADINGREMOVE));
define ('POP_RESOURCELOADER_TEMPLATE_SCROLL', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SCROLL));
define ('POP_RESOURCELOADER_TEMPLATE_SCROLL_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SCROLL_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SOCIALMEDIA));
define ('POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA_ITEM', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SOCIALMEDIA_ITEM));
define ('POP_RESOURCELOADER_TEMPLATE_STATUS', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_STATUS));
define ('POP_RESOURCELOADER_TEMPLATE_SUBMENU', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_SUBMENU));
define ('POP_RESOURCELOADER_TEMPLATE_TABLE', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_TABLE));
define ('POP_RESOURCELOADER_TEMPLATE_TABLE_INNER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_TABLE_INNER));
define ('POP_RESOURCELOADER_TEMPLATE_USERLOGGEDIN', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_USERLOGGEDIN));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_BUTTON', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_BUTTON));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTPOST', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTPOST));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_POST', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_POST));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_REPLYCOMMENT', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_REPLYCOMMENT));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_USER', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_USER));
define ('POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_TAG', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_TAG));
define ('POP_RESOURCELOADER_TEMPLATE_WIDGET', PoP_TemplateIDUtils::get_template_definition(GD_TEMPLATESOURCE_WIDGET));

class PoP_CoreProcessors_TemplateResourceLoaderProcessor extends PoP_TemplateResourceLoaderProcessor {

	function get_resources_to_process() {

		return array(
			POP_RESOURCELOADER_TEMPLATE_ALERT,
			POP_RESOURCELOADER_TEMPLATE_BLOCK_BARE,
			POP_RESOURCELOADER_TEMPLATE_BLOCK_DESCRIPTION,
			POP_RESOURCELOADER_TEMPLATE_BLOCKGROUP_BLOCKUNITS,
			POP_RESOURCELOADER_TEMPLATE_BUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_BUTTONINNER,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL_CONTROLS,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL_INNER,
			POP_RESOURCELOADER_TEMPLATE_CODE,
			POP_RESOURCELOADER_TEMPLATE_CONDITIONWRAPPER,
			POP_RESOURCELOADER_TEMPLATE_CONTENT,
			POP_RESOURCELOADER_TEMPLATE_CONTENTMULTIPLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_CONTENTSINGLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_ANCHOR,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_DROPDOWNBUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_RADIOBUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROLBUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_CONTROLGROUP,
			POP_RESOURCELOADER_TEMPLATE_DIVIDER,
			POP_RESOURCELOADER_TEMPLATE_FETCHMORE,
			POP_RESOURCELOADER_TEMPLATE_FORM,
			POP_RESOURCELOADER_TEMPLATE_FORM_INNER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_BUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CAPTCHA,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CHECKBOX,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_DATERANGE,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE_INNER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FETCHLINKTYPEAHEAD,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_INPUTGROUP,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECT,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEAD,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXT,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXTAREA,
			POP_RESOURCELOADER_TEMPLATE_FORMGROUP,
			POP_RESOURCELOADER_TEMPLATE_HIDEIFEMPTY,
			POP_RESOURCELOADER_TEMPLATE_LATESTCOUNT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MAXHEIGHT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_CONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_LINKCONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_APPENDSCRIPT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_CONTACT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_USERPHOTO,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHORCONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_CATEGORIES,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_COMMENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_DATAQUERY_UPDATEDATA,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_EMBEDPREVIEW,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_INITJSDELAY,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLOBJECTTITLE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLVIEW,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLUSER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_LATESTCOUNTSCRIPT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MARKER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_ANCHOR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWN,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWNBUTTON,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_INDENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_MULTITARGETINDENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACK,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MULTIPLE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PAGETAB,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POPOVER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTSTATUSDATE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAGINFO,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTTHUMB,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWPOST,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWUSER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SCRIPTFRAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SEGMENTEDBUTTON_LINK,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_STYLES,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SUBCOMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAG,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERAVATAR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERPOSTINTERACTION,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORAVATAR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORNAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_DATE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_STATUS,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_SELECTED,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTTAG_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_MENTION_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_QUICKLINKS,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_SELECTED,
			POP_RESOURCELOADER_TEMPLATE_MESSAGE,
			POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK,
			POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK_INNER,
			POP_RESOURCELOADER_TEMPLATE_MULTIPLE,
			POP_RESOURCELOADER_TEMPLATE_PAGESECTION_PLAIN,
			POP_RESOURCELOADER_TEMPLATE_SCRIPT_APPENDCOMMENT,
			POP_RESOURCELOADER_TEMPLATE_SCRIPT_LAZYLOADINGREMOVE,
			POP_RESOURCELOADER_TEMPLATE_SCROLL,
			POP_RESOURCELOADER_TEMPLATE_SCROLL_INNER,
			POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA,
			POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA_ITEM,
			POP_RESOURCELOADER_TEMPLATE_STATUS,
			POP_RESOURCELOADER_TEMPLATE_SUBMENU,
			POP_RESOURCELOADER_TEMPLATE_TABLE,
			POP_RESOURCELOADER_TEMPLATE_TABLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_USERLOGGEDIN,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTPOST,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_POST,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_REPLYCOMMENT,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_USER,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_TAG,
			POP_RESOURCELOADER_TEMPLATE_WIDGET,
		);
	}
	
	// function is_extension($resource) {

	// 	switch ($resource) {

	// 		case POP_RESOURCELOADER_TEMPLATE_BLOCKGROUP_BLOCKUNITS:

	// 			return true;
	// 	}
	
	// 	return parent::is_extension($resource);
	// }
	
	function get_filename($resource) {
	
		$filenames = array(
			POP_RESOURCELOADER_TEMPLATE_ALERT => GD_TEMPLATESOURCE_ALERT,
			POP_RESOURCELOADER_TEMPLATE_BLOCK_BARE => GD_TEMPLATESOURCE_BLOCK_BARE,
			POP_RESOURCELOADER_TEMPLATE_BLOCK_DESCRIPTION => GD_TEMPLATESOURCE_BLOCK_DESCRIPTION,
			POP_RESOURCELOADER_TEMPLATE_BLOCKGROUP_BLOCKUNITS => GD_TEMPLATESOURCE_BLOCKGROUP_BLOCKUNITS,
			POP_RESOURCELOADER_TEMPLATE_BUTTONGROUP => GD_TEMPLATESOURCE_BUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_BUTTON => GD_TEMPLATESOURCE_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_BUTTONINNER => GD_TEMPLATESOURCE_BUTTONINNER,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL => GD_TEMPLATESOURCE_CAROUSEL,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL_CONTROLS => GD_TEMPLATESOURCE_CAROUSEL_CONTROLS,
			POP_RESOURCELOADER_TEMPLATE_CAROUSEL_INNER => GD_TEMPLATESOURCE_CAROUSEL_INNER,
			POP_RESOURCELOADER_TEMPLATE_CODE => GD_TEMPLATESOURCE_CODE,
			POP_RESOURCELOADER_TEMPLATE_CONDITIONWRAPPER => GD_TEMPLATESOURCE_CONDITIONWRAPPER,
			POP_RESOURCELOADER_TEMPLATE_CONTENT => GD_TEMPLATESOURCE_CONTENT,
			POP_RESOURCELOADER_TEMPLATE_CONTENTMULTIPLE_INNER => GD_TEMPLATESOURCE_CONTENTMULTIPLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_CONTENTSINGLE_INNER => GD_TEMPLATESOURCE_CONTENTSINGLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_ANCHOR => GD_TEMPLATESOURCE_CONTROL_ANCHOR,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_BUTTON => GD_TEMPLATESOURCE_CONTROL_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_DROPDOWNBUTTON => GD_TEMPLATESOURCE_CONTROL_DROPDOWNBUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROL_RADIOBUTTON => GD_TEMPLATESOURCE_CONTROL_RADIOBUTTON,
			POP_RESOURCELOADER_TEMPLATE_CONTROLBUTTONGROUP => GD_TEMPLATESOURCE_CONTROLBUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_CONTROLGROUP => GD_TEMPLATESOURCE_CONTROLGROUP,
			POP_RESOURCELOADER_TEMPLATE_DIVIDER => GD_TEMPLATESOURCE_DIVIDER,
			POP_RESOURCELOADER_TEMPLATE_FETCHMORE => GD_TEMPLATESOURCE_FETCHMORE,
			POP_RESOURCELOADER_TEMPLATE_FORM => GD_TEMPLATESOURCE_FORM,
			POP_RESOURCELOADER_TEMPLATE_FORM_INNER => GD_TEMPLATESOURCE_FORM_INNER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_BUTTONGROUP => GD_TEMPLATESOURCE_FORMCOMPONENT_BUTTONGROUP,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CAPTCHA => GD_TEMPLATESOURCE_FORMCOMPONENT_CAPTCHA,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_CHECKBOX => GD_TEMPLATESOURCE_FORMCOMPONENT_CHECKBOX,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_DATERANGE => GD_TEMPLATESOURCE_FORMCOMPONENT_DATERANGE,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE => GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FEATUREDIMAGE_INNER => GD_TEMPLATESOURCE_FORMCOMPONENT_FEATUREDIMAGE_INNER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_FETCHLINKTYPEAHEAD => GD_TEMPLATESOURCE_FORMCOMPONENT_FETCHLINKTYPEAHEAD,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_INPUTGROUP => GD_TEMPLATESOURCE_FORMCOMPONENT_INPUTGROUP,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECT => GD_TEMPLATESOURCE_FORMCOMPONENT_SELECT,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEAD => GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEAD,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER => GD_TEMPLATESOURCE_FORMCOMPONENT_SELECTABLETYPEAHEADTRIGGER,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXT => GD_TEMPLATESOURCE_FORMCOMPONENT_TEXT,
			POP_RESOURCELOADER_TEMPLATE_FORMCOMPONENT_TEXTAREA => GD_TEMPLATESOURCE_FORMCOMPONENT_TEXTAREA,
			POP_RESOURCELOADER_TEMPLATE_FORMGROUP => GD_TEMPLATESOURCE_FORMGROUP,
			POP_RESOURCELOADER_TEMPLATE_HIDEIFEMPTY => GD_TEMPLATESOURCE_HIDEIFEMPTY,
			POP_RESOURCELOADER_TEMPLATE_LATESTCOUNT => GD_TEMPLATESOURCE_LATESTCOUNT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MAXHEIGHT => GD_TEMPLATESOURCE_LAYOUT_MAXHEIGHT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_CONTENT => GD_TEMPLATESOURCE_LAYOUT_CONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_LINKCONTENT => GD_TEMPLATESOURCE_LAYOUT_LINKCONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_APPENDSCRIPT => GD_TEMPLATESOURCE_LAYOUT_APPENDSCRIPT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_CONTACT => GD_TEMPLATESOURCE_LAYOUT_AUTHOR_CONTACT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHOR_USERPHOTO => GD_TEMPLATESOURCE_LAYOUT_AUTHOR_USERPHOTO,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_AUTHORCONTENT => GD_TEMPLATESOURCE_LAYOUT_AUTHORCONTENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_CATEGORIES => GD_TEMPLATESOURCE_LAYOUT_CATEGORIES,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_COMMENT => GD_TEMPLATESOURCE_LAYOUT_COMMENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_DATAQUERY_UPDATEDATA => GD_TEMPLATESOURCE_LAYOUT_DATAQUERY_UPDATEDATA,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_EMBEDPREVIEW => GD_TEMPLATESOURCE_LAYOUT_EMBEDPREVIEW,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_INITJSDELAY => GD_TEMPLATESOURCE_LAYOUT_INITJSDELAY,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLOBJECTTITLE => GD_TEMPLATESOURCE_LAYOUT_FULLOBJECTTITLE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLVIEW => GD_TEMPLATESOURCE_LAYOUT_FULLVIEW,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_FULLUSER => GD_TEMPLATESOURCE_LAYOUT_FULLUSER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_LATESTCOUNTSCRIPT => GD_TEMPLATESOURCE_LAYOUT_LATESTCOUNTSCRIPT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MARKER => GD_TEMPLATESOURCE_LAYOUT_MARKER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_ANCHOR => GD_TEMPLATESOURCE_LAYOUT_MENU_ANCHOR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON => GD_TEMPLATESOURCE_LAYOUT_MENU_COLLAPSESEGMENTEDBUTTON,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWN => GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWN,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_DROPDOWNBUTTON => GD_TEMPLATESOURCE_LAYOUT_MENU_DROPDOWNBUTTON,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_INDENT => GD_TEMPLATESOURCE_LAYOUT_MENU_INDENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MENU_MULTITARGETINDENT => GD_TEMPLATESOURCE_LAYOUT_MENU_MULTITARGETINDENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACK => GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACK,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MESSAGEFEEDBACKFRAME => GD_TEMPLATESOURCE_LAYOUT_MESSAGEFEEDBACKFRAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_MULTIPLE => GD_TEMPLATESOURCE_LAYOUT_MULTIPLE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PAGETAB => GD_TEMPLATESOURCE_LAYOUT_PAGETAB,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POPOVER => GD_TEMPLATESOURCE_LAYOUT_POPOVER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL => GD_TEMPLATESOURCE_LAYOUT_POSTADDITIONAL_MULTILAYOUT_LABEL,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTSTATUSDATE => GD_TEMPLATESOURCE_LAYOUT_POSTSTATUSDATE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAGINFO => GD_TEMPLATESOURCE_LAYOUT_TAGINFO,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_POSTTHUMB => GD_TEMPLATESOURCE_LAYOUT_POSTTHUMB,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWPOST => GD_TEMPLATESOURCE_LAYOUT_PREVIEWPOST,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_PREVIEWUSER => GD_TEMPLATESOURCE_LAYOUT_PREVIEWUSER,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SCRIPTFRAME => GD_TEMPLATESOURCE_LAYOUT_SCRIPTFRAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SEGMENTEDBUTTON_LINK => GD_TEMPLATESOURCE_LAYOUT_SEGMENTEDBUTTON_LINK,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_STYLES => GD_TEMPLATESOURCE_LAYOUT_STYLES,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_SUBCOMPONENT => GD_TEMPLATESOURCE_LAYOUT_SUBCOMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_TAG => GD_TEMPLATESOURCE_LAYOUT_TAG,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERAVATAR => GD_TEMPLATESOURCE_LAYOUT_USERAVATAR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUT_USERPOSTINTERACTION => GD_TEMPLATESOURCE_LAYOUT_USERPOSTINTERACTION,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORAVATAR => GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORAVATAR,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_AUTHORNAME => GD_TEMPLATESOURCE_LAYOUTPOST_AUTHORNAME,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_DATE => GD_TEMPLATESOURCE_LAYOUTPOST_DATE,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_STATUS => GD_TEMPLATESOURCE_LAYOUTPOST_STATUS,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_COMPONENT => GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTPOST_TYPEAHEAD_SELECTED => GD_TEMPLATESOURCE_LAYOUTPOST_TYPEAHEAD_SELECTED,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT => GD_TEMPLATESOURCE_LAYOUTSTATIC_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTTAG_TYPEAHEAD_COMPONENT => GD_TEMPLATESOURCE_LAYOUTTAG_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_MENTION_COMPONENT => GD_TEMPLATESOURCE_LAYOUTUSER_MENTION_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_QUICKLINKS => GD_TEMPLATESOURCE_LAYOUTUSER_QUICKLINKS,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_COMPONENT => GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_COMPONENT,
			POP_RESOURCELOADER_TEMPLATE_LAYOUTUSER_TYPEAHEAD_SELECTED => GD_TEMPLATESOURCE_LAYOUTUSER_TYPEAHEAD_SELECTED,
			POP_RESOURCELOADER_TEMPLATE_MESSAGE => GD_TEMPLATESOURCE_MESSAGE,
			POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK => GD_TEMPLATESOURCE_MESSAGEFEEDBACK,
			POP_RESOURCELOADER_TEMPLATE_MESSAGEFEEDBACK_INNER => GD_TEMPLATESOURCE_MESSAGEFEEDBACK_INNER,
			POP_RESOURCELOADER_TEMPLATE_MULTIPLE => GD_TEMPLATESOURCE_MULTIPLE,
			POP_RESOURCELOADER_TEMPLATE_PAGESECTION_PLAIN => GD_TEMPLATESOURCE_PAGESECTION_PLAIN,
			POP_RESOURCELOADER_TEMPLATE_SCRIPT_APPENDCOMMENT => GD_TEMPLATESOURCE_SCRIPT_APPENDCOMMENT,
			POP_RESOURCELOADER_TEMPLATE_SCRIPT_LAZYLOADINGREMOVE => GD_TEMPLATESOURCE_SCRIPT_LAZYLOADINGREMOVE,
			POP_RESOURCELOADER_TEMPLATE_SCROLL => GD_TEMPLATESOURCE_SCROLL,
			POP_RESOURCELOADER_TEMPLATE_SCROLL_INNER => GD_TEMPLATESOURCE_SCROLL_INNER,
			POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA => GD_TEMPLATESOURCE_SOCIALMEDIA,
			POP_RESOURCELOADER_TEMPLATE_SOCIALMEDIA_ITEM => GD_TEMPLATESOURCE_SOCIALMEDIA_ITEM,
			POP_RESOURCELOADER_TEMPLATE_STATUS => GD_TEMPLATESOURCE_STATUS,
			POP_RESOURCELOADER_TEMPLATE_SUBMENU => GD_TEMPLATESOURCE_SUBMENU,
			POP_RESOURCELOADER_TEMPLATE_TABLE => GD_TEMPLATESOURCE_TABLE,
			POP_RESOURCELOADER_TEMPLATE_TABLE_INNER => GD_TEMPLATESOURCE_TABLE_INNER,
			POP_RESOURCELOADER_TEMPLATE_USERLOGGEDIN => GD_TEMPLATESOURCE_USERLOGGEDIN,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_BUTTON => GD_TEMPLATESOURCE_VIEWCOMPONENT_BUTTON,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTCLIPPED,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_COMMENTPOST => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_COMMENTPOST,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_POST => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_POST,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_REPLYCOMMENT => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_REPLYCOMMENT,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_USER => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_USER,
			POP_RESOURCELOADER_TEMPLATE_VIEWCOMPONENT_HEADER_TAG => GD_TEMPLATESOURCE_VIEWCOMPONENT_HEADER_TAG,
			POP_RESOURCELOADER_TEMPLATE_WIDGET => GD_TEMPLATESOURCE_WIDGET,
		);
		if ($filename = $filenames[$resource]) {
			return $filename;
		}

		return parent::get_filename($resource);
	}
	
	function get_version($resource) {
	
		return POP_COREPROCESSORS_VERSION;
	}
	
	function get_path($resource) {
	
		return POP_COREPROCESSORS_URI.'/js/dist/templates';
	}
	
	function get_globalscope_method_calls($resource) {

		switch ($resource) {

			case POP_RESOURCELOADER_TEMPLATE_LAYOUT_INITJSDELAY:

				return array(
					'popManager' => array(
						'getBlock',
					),
				);
		}

		return parent::get_globalscope_method_calls($resource);
	}

}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new PoP_CoreProcessors_TemplateResourceLoaderProcessor();
