<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts00'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts01'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts02'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts03'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts04'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts05'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts06'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts07'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts08'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts09'));

define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts00'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts01'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts02'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts03'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts04'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts05'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts06'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts07'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts08'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts09'));

define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts00-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts01-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts02-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts03-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts04-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts05-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts06-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts07-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts08-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categoryposts09-content'));

define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts00-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts01-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts02-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts03-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts04-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts05-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts06-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts07-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts08-content'));
define ('GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT', PoP_ServerUtils::get_template_definition('carouselinner-categorywebposts09-content'));

class CPP_Template_Processor_CarouselInners extends GD_Template_Processor_CarouselInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT,
		);
	}

	function get_layout_grid($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09:

				// if ($grid = $this->get_att($template_id, $atts, 'layout-grid')) {
				// 	return $grid;
				// }

				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12',
					'divider' => 3,
				);

			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT:
			case GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT:

				// if ($grid = $this->get_att($template_id, $atts, 'layout-grid')) {
				// 	return $grid;
				// }

				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12',
					'divider' => 1,
				);
		}

		return parent::get_layout_grid($template_id, $atts);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		$layouts = array(
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09 => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
			GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_LAYOUT_CONTENT_POST,
		);
		if ($layout = $layouts[$template_id]) {
			$ret[] =$layout;
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CarouselInners();