<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts00'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts01'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts02'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts03'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts04'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts05'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts06'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts07'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts08'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts09'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts00'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts01'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts02'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts03'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts04'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts05'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts06'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts07'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts08'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts09'));

define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categoryposts09-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-categorywebposts09-content'));

define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts00'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts01'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts02'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts03'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts04'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts05'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts06'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts07'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts08'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts09'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts00'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts01'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts02'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts03'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts04'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts05'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts06'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts07'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts08'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts09'));

define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategoryposts09-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-authorcategorywebposts09-content'));

define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts00'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts01'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts02'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts03'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts04'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts05'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts06'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts07'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts08'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts09'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts00'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts01'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts02'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts03'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts04'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts05'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts06'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts07'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts08'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts09'));

define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategoryposts09-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts00-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts01-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts02-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts03-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts04-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts05-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts06-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts07-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts08-content'));
define ('GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT', PoP_TemplateIDUtils::get_template_definition('carousel-tagcategorywebposts09-content'));

class CPP_Template_Processor_Carousels extends GD_Template_Processor_CarouselsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT,
		);
	}

	function init_atts($template_id, &$atts) {
			
		// switch ($template_id) {

		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT:

		// 		$this->append_att($template_id, $atts, 'class', 'slide');
		// 		$this->append_att($template_id, $atts, 'class', 'widget widget-info');
		// 		break;
		// }
		$this->append_att($template_id, $atts, 'class', 'slide');
		$this->append_att($template_id, $atts, 'class', 'widget widget-info');
		
		return parent::init_atts($template_id, $atts);
	}

	function get_inner_template($template_id) {

		$inners = array(
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYPOSTS09_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS00_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS01_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS02_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS03_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS04_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS05_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS06_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS07_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS08_CONTENT,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELINNER_CATEGORYWEBPOSTS09_CONTENT,
		);
		if ($inner = $inners[$template_id]) {
			return $inner;
		}

		return parent::get_inner_template($template_id);
	}

	function get_mode($template_id, $atts) {

		// switch ($template_id) {

		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_AUTHORCATEGORYWEBPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT:
		// 	case GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT:

		// 		return 'static';
		// }

		// return parent::get_mode($template_id, $atts);
		return 'static';
	}


	function get_controls_top_template($template_id) {

		$controls = array(
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_CATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_AUTHROCATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09 => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS00_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS00,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS01_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS01,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS02_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS02,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS03_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS03,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS04_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS04,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS05_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS05,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS06_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS06,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS07_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS07,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS08_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS08,
			GD_TEMPLATE_CAROUSEL_TAGCATEGORYWEBPOSTS09_CONTENT => GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYWEBPOSTS09,
		);
		if ($control = $controls[$template_id]) {
			return $control;
		}

		return parent::get_controls_top_template($template_id);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_Carousels();