<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts00'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts01'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts02'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts03'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts04'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts05'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts06'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts07'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts08'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts09'));

define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts00'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts01'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts02'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts03'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts04'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts05'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts06'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts07'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts08'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('carouselcontrols-authorcategoryposts09'));

define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts00'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts01'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts02'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts03'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts04'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts05'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts06'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts07'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts08'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('carouselcontrols-tagcategoryposts09'));

class CPP_Template_Processor_CarouselControls extends GD_Template_Processor_CarouselControlsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09,
		);
	}

	function get_control_class($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09:

				return 'btn btn-link btn-compact';
		}

		return parent::get_control_class($template_id);
	}

	function get_title_class($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09:

				return 'btn btn-link btn-compact';
		}

		return parent::get_title_class($template_id);
	}
	function get_title($template_id) {

		$pages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		if ($page = $pages[$template_id]) {
			return get_the_title($page);
		}

		return parent::get_title($template_id);
	}
	protected function get_title_link($template_id) {

		$pages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		$authorpages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_AUTHORCATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		$tagpages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_TAGCATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		if ($page = $pages[$template_id]) {
			return get_permalink($page);
		}
		elseif ($page = $authorpages[$template_id]) {

			$url = get_author_posts_url($author);
			return GD_TemplateManager_Utils::add_tab($url, $page);
		}
		elseif ($page = $tagpages[$template_id]) {
			
			$url = get_tag_link(get_queried_object_id());
			return GD_TemplateManager_Utils::add_tab($url, $page);
		}

		return parent::get_title_link($template_id);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CarouselControls();