<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts00'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts01'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts02'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts03'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts04'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts05'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts06'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts07'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts08'));
define ('GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09', PoP_ServerUtils::get_template_definition('carouselcontrols-categoryposts09'));

class CPP_Template_Processor_CarouselControls extends GD_Template_Processor_CarouselControlsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09,
		);
	}

	function get_control_class($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09:

				return 'btn btn-link btn-compact';
		}

		return parent::get_control_class($template_id);
	}

	function get_title_class($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08:
			case GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09:

				return 'btn btn-link btn-compact';
		}

		return parent::get_title_class($template_id);
	}
	function get_title($template_id) {

		$pages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		if ($page = $pages[$template_id]) {
			return get_the_title($page);
		}

		return parent::get_title($template_id);
	}
	protected function get_title_link($template_id) {

		$pages = array(
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS00 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS00,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS01 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS01,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS02 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS02,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS03 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS03,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS04 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS04,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS05 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS05,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS06 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS06,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS07 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS07,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS08 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS08,
			GD_TEMPLATE_CAROUSELCONTROLS_CATEGORYPOSTS09 => POPTHEME_WASSUP_CATEGORYPROCESSORS_PAGE_CATEGORYPOSTS09,
		);
		if ($page = $pages[$template_id]) {
			return get_permalink($page);
		}

		return parent::get_title_link($template_id);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new CPP_Template_Processor_CarouselControls();