<?php

/**---------------------------------------------------------------------------------------------------------------
 *
 * IDs Configuration
 *
 * ---------------------------------------------------------------------------------------------------------------*/

// Categories
//--------------------------------------------------------
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_MESSAGES_HOME', 1397);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_STORIES', 1687);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_STORYLINKS', 1614);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_THOUGHTS', 1399);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_LOCATIONPOSTS', 1621);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_LOCATIONPOSTLINKS', 1622);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_DISCUSSIONS', 1686);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_DISCUSSIONLINKS', 1613);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_BLOG', 1105);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_ANNOUNCEMENTS', 1684);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_ANNOUNCEMENTLINKS', 1615);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_FEATURED', 1685);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_CAT_UNCATEGORIZED', 1423);

// Pages from the Main Navigation
//--------------------------------------------------------
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_LOCATIONPOSTS', 22931);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_STORIES', 16099);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ANNOUNCEMENTS', 16101);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_DISCUSSIONS', 16103);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_FEATURED', 16105);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_RESOURCES', 16107);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_THOUGHTS', 16134);

// About us Pages
//--------------------------------------------------------
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_BLOG', 16109);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT', 16068);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_HOWTOUSEWEBSITE', 20810);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_CONTENTGUIDELINES', 22459);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURMISSION', 16114);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_WHOWEARE', 16116);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSTORY', 16118);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_VOLUNTEERWITHUS', 16120);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_SPONSORUS', 16480);
define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_INTHEMEDIA', 18866);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ABOUT_OURSPONSORS', 16724);

// Add / Edit / List Content Pages
//--------------------------------------------------------
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYLOCATIONPOSTS', 22933);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDLOCATIONPOST', 16174);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITLOCATIONPOST', 16176);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDLOCATIONPOSTLINK', 22958);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITLOCATIONPOSTLINK', 22960);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYSTORIES', 16178);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORY', 16180);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORY', 16182);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDSTORYLINK', 21541);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITSTORYLINK', 21543);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYDISCUSSIONS', 16184);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSION', 16186);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSION', 16188);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDDISCUSSIONLINK', 21545);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITDISCUSSIONLINK', 21547);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDFEATURED', 20039);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITFEATURED', 20037);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_MYANNOUNCEMENTS', 16190);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENT', 16192);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENT', 16194);	
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_ADDANNOUNCEMENTLINK', 21549);
// define ('POPTHEME_WASSUP_SECTIONPROCESSORS_PAGE_EDITANNOUNCEMENTLINK', 21551);	
