<?php

declare(strict_types=1);

namespace PoPSchema\SchemaCommons\ObjectTypeResolverPickers;

use PoP\ComponentModel\ObjectTypeResolverPickers\AbstractTransientObjectObjectTypeResolverPicker;

abstract class AbstractErrorPayloadObjectTypeResolverPicker extends AbstractTransientObjectObjectTypeResolverPicker implements GenericErrorPayloadObjectTypeResolverPickerInterface
{
}
