<?php

if (!defined('POP_USERAVATAR_FILEUPLOAD_SIZES')) {
    define('POP_USERAVATAR_FILEUPLOAD_SIZES', array(16, 50, 100, 150));
}
if (!defined('POP_USERAVATAR_RELATIVEBASEDIR')) {
    define('POP_USERAVATAR_RELATIVEBASEDIR', DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR);
}
