<?php

declare(strict_types=1);

namespace GatoGraphQL\GatoGraphQL\Registries;

class PersistedQueryEndpointSchemaConfigurationExecuterRegistry extends AbstractSchemaConfigurationExecuterRegistry implements PersistedQueryEndpointSchemaConfigurationExecuterRegistryInterface
{
}
