<?php
namespace PoP\CMSModel;

interface FunctionAPI extends \PoP\CMS\FunctionAPI
{

    /**
     * Most functions below are 1 to 1 with WordPress signature
     */
    public function getPostStatus($post_id);
    public function getPosts($query, array $options = []);
    public function getPostTypes($query = array());
    // public function getObjectTaxonomies($object, $output = 'names');
    public function getPageIdByPath($page_path);
    // public function getUserdata($user_id);
    public function getComments($query, array $options = []);
    public function getComment($comment_id);
    public function getPost($post_id);
    public function getTag($tag_id);
    public function getNavMenuLocations();
    public function getNavigationMenuObject($menu_object_id);
    public function getNavigationMenuItems($menu);
    public function addRole($role, $display_name, $capabilities = array());
    public function addRoleToUser($user_id, $role);
    public function removeRoleFromUser($user_id, $role);
    public function getTags($query, array $options = []);
    public function getUserById($value);
    public function getUserByEmail($value);
    public function getUserBySlug($value);
    public function getUserByLogin($value);
    public function getUserRoles($user_id);
    public function getUsers($query = array(), array $options = []);
    public function getTheAuthorMeta($field, $user_id);
    public function getUserDisplayName($user_id);
    public function getUserEmail($user_id);
    public function getUserFirstname($user_id);
    public function getUserLastname($user_id);
    public function getUserLogin($user_id);
    public function getUserDescription($user_id);
    public function getUserRegistrationDate($user_id);
    public function getAuthorPostsUrl($user_id);
    public function getPostType($post);
    public function getCommentsNumber($post_id);
    public function getTheCategory($post_id = false);
    public function getPostCategories($post_id = 0, array $query = [], array $options = []);
    public function getPostTags($post_id = 0, array $query = [], array $options = []);
    public function getObjectTerms($object_ids, $taxonomies, $args = array());
    public function getPermalink($post_id);
    public function getTheExcerpt($post_id);
    public function hasPostThumbnail($post_id);
    public function getPostThumbnailId($post_id);
    public function getAttachmentImageSrc($image_id, $size = null);
    public function getEditPostLink($post_id);
    public function getDeletePostLink($post_id);
    public function getTagLink($tag_id);
    public function getPostMimeType($post_thumb_id);
    public function getTheTitle($post = 0);
    public function getSinglePostTitle($post);
    public function getSearchQuery($escaped = true);
    public function getCatTitle($cat);
    public function getTagTitle($tag);
    // public function getQueryVar($var, $default = '');
    public function getCategoryIds($args = array());
    public function getQueryFromRequestUri();
    public function isUserLoggedIn();
    public function getCurrentUser();
    public function getCurrentUserId();
    public function getTheUserRole($user_id);
    public function getHomeStaticPage();
    public function logout();
    public function insertComment($comment_data);
    public function insertPost($post_data);
    public function updatePost($post_data);
    public function insertUser($user_data);
    public function getAllowedPostTags();
    public function getCategoryName($cat_id);
    public function getPostSlug($post_id);
    public function getPostTitle($post_id);
    public function getPostContent($post_id);
    public function getPostEditorContent($post_id);
    public function getBasicPostContent($post_id);
    public function getMenuItemTitle($menu_item);
    public function getExcerptMore();
    public function getExcerptLength();
    public function getPostCount($query);
    public function getCategoryPath($category_id);
    public function getAuthorBase();
    public function getTagBase();
    public function getPasswordResetKey($user_data);
    public function getTrendingHashtagIds($days, $number, $offset);
    public function login($credentials);
    public function checkPassword($password, $hash);
    public function checkPasswordResetKey($key, $login);
    public function dequeueScript($handle);
    public function dequeueStyle($handle);
    public function enqueueScript($handle, $src = '', $deps = array(), $ver = false, $in_footer = false);
    public function enqueueStyle($handle, $src = '', $deps = array(), $ver = false, $media = 'all');
    public function registerScript($handle, $src, $deps = array(), $ver = false, $in_footer = false);
    public function registerStyle($handle, $src, $deps = array(), $ver = false, $media = 'all');
    public function printFooterHTML();
    public function printHeadHTML();
    public function localizeScript($handle, $object_name, $l10n);
    public function updateUser($user_data);
    public function resetPassword($user, $pwd);
    public function getLoginURL();
    public function getLogoutURL();
    public function getLostPasswordURL();
    public function setPostTags($post_id, array $tags, bool $append = false);
    public function setPostTerms($post_id, $tags, $taxonomy, $append = false);
}
