<?php

const POP_PAGEMODULEGROUP_MAINCONTENT = 'maincontent';
const POP_PAGEMODULEGROUP_TOPLEVEL_CONTENTPAGESECTION = 'toplevel-contentpagesection';
const POP_PAGEMODULEGROUP_TOPLEVEL_TABSPAGESECTION = 'toplevel-tabspagesection';
// const POP_PAGEMODULEGROUP_TOPLEVEL_ADDONTABSPAGESECTION = 'toplevel-addontabspagesection';
const POP_PAGEMODULEGROUP_TOPLEVEL_SIDEINFOPAGESECTION = 'toplevel-sideinfopagesection';
const POP_PAGEMODULEGROUP_PAGESECTION_TOPFRAMECONTENT = 'pagesection-topframecontent';
const POP_PAGEMODULEGROUP_PAGESECTION_SIDEFRAMECONTENT = 'pagesection-sideframecontent';
const POP_PAGEMODULEGROUP_PAGESECTION_BACKGROUNDFRAMECONTENT = 'pagesection-backgroundframecontent';
const POP_PAGEMODULEGROUP_PAGESECTION_MAINCONTENT = 'pagesection-maincontent';
const POP_PAGEMODULEGROUP_PAGESECTION_BODYFRAMEOPTIONS = 'pagesection-bodyframeoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_BODYFRAMETOPOPTIONS = 'pagesection-bodyframetopoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_BODYFRAMEBOTTOMOPTIONS = 'pagesection-bodyframebottomoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_QUICKVIEWFRAMETOPOPTIONS = 'pagesection-quickviewframetopoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_QUICKVIEWFRAMEBOTTOMOPTIONS = 'pagesection-quickviewframebottomoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_SIDEINFOCONTENT = 'pagesection-sideinfocontent';
const POP_PAGEMODULEGROUP_PAGESECTION_SIDEINFOFRAMEOPTIONS = 'pagesection-sideinfoframeoptions';
const POP_PAGEMODULEGROUP_PAGESECTION_TAB = 'pagesection-tab';
