<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLL_HOMEMESSAGES', PoP_ServerUtils::get_template_definition('scroll-homemessages'));

define ('GD_TEMPLATE_SCROLL_MYCONTENT_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mycontent-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYLINKS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mylinks-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYWEBPOSTS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mywebposts-simpleviewpreview'));

define ('GD_TEMPLATE_SCROLL_MYCONTENT_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mycontent-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYLINKS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mylinks-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYHIGHLIGHTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-myhighlights-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYWEBPOSTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-mywebposts-fullviewpreview'));
// define ('GD_TEMPLATE_SCROLL_MYRESOURCES_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scroll-myresources-fullviewpreview'));

define ('GD_TEMPLATE_SCROLL_ALLCONTENT_NAVIGATOR', PoP_ServerUtils::get_template_definition('scroll-allcontent-navigator'));
define ('GD_TEMPLATE_SCROLL_LINKS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scroll-links-navigator'));
define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scroll-highlights-navigator'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scroll-webposts-navigator'));

define ('GD_TEMPLATE_SCROLL_ALLUSERS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scroll-allusers-navigator'));

define ('GD_TEMPLATE_SCROLL_ALLCONTENT_ADDONS', PoP_ServerUtils::get_template_definition('scroll-allcontent-addons'));
define ('GD_TEMPLATE_SCROLL_LINKS_ADDONS', PoP_ServerUtils::get_template_definition('scroll-links-addons'));
define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_ADDONS', PoP_ServerUtils::get_template_definition('scroll-highlights-addons'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_ADDONS', PoP_ServerUtils::get_template_definition('scroll-webposts-addons'));

define ('GD_TEMPLATE_SCROLL_ALLUSERS_ADDONS', PoP_ServerUtils::get_template_definition('scroll-allusers-addons'));

define ('GD_TEMPLATE_SCROLL_SEARCHPOSTS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-searchposts-details'));
define ('GD_TEMPLATE_SCROLL_ALLCONTENT_DETAILS', PoP_ServerUtils::get_template_definition('scroll-allcontent-details'));
define ('GD_TEMPLATE_SCROLL_LINKS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-links-details'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-webposts-details'));
// define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-highlights-details'));

define ('GD_TEMPLATE_SCROLL_SEARCHUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-searchusers-details'));
define ('GD_TEMPLATE_SCROLL_ALLUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-allusers-details'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-authorfollowers-details'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scroll-authorfollowingusers-details'));

define ('GD_TEMPLATE_SCROLL_SEARCHPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-searchposts-simpleview'));
define ('GD_TEMPLATE_SCROLL_ALLCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-allcontent-simpleview'));
define ('GD_TEMPLATE_SCROLL_LINKS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-links-simpleview'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-webposts-simpleview'));

define ('GD_TEMPLATE_SCROLL_SEARCHPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-searchposts-fullview'));
define ('GD_TEMPLATE_SCROLL_ALLCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-allcontent-fullview'));
define ('GD_TEMPLATE_SCROLL_LINKS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-links-fullview'));
define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-highlights-fullview'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-webposts-fullview'));

define ('GD_TEMPLATE_SCROLL_SEARCHUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-searchusers-fullview'));
define ('GD_TEMPLATE_SCROLL_ALLUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-allusers-fullview'));

// define ('GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-authorallcontent-simpleview'));
// define ('GD_TEMPLATE_SCROLL_AUTHORLINKS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-authorlinks-simpleview'));
// define ('GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-authorwebposts-simpleview'));
// define ('GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-authorrecommendedposts-simpleview'));

define ('GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorallcontent-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORLINKS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorlinks-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORHIGHLIGHTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorhighlights-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorwebposts-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorfollowers-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorfollowingusers-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-authorrecommendedposts-fullview'));

// define ('GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scroll-singlerelatedcontent-simpleview'));

define ('GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-singlerelatedcontent-fullview'));
define ('GD_TEMPLATE_SCROLL_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-singlerelatedhighlightcontent-fullview'));
define ('GD_TEMPLATE_SCROLL_SINGLEAUTHORS_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-singleauthors-fullview'));

define ('GD_TEMPLATE_SCROLL_SEARCHPOSTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-searchposts-thumbnail'));
define ('GD_TEMPLATE_SCROLL_ALLCONTENT_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-allcontent-thumbnail'));
define ('GD_TEMPLATE_SCROLL_LINKS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-links-thumbnail'));
define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-highlights-thumbnail'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-webposts-thumbnail'));

define ('GD_TEMPLATE_SCROLL_SEARCHUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-searchusers-thumbnail'));
define ('GD_TEMPLATE_SCROLL_ALLUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-allusers-thumbnail'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-authorfollowers-thumbnail'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-authorfollowingusers-thumbnail'));

define ('GD_TEMPLATE_SCROLL_SEARCHPOSTS_LIST', PoP_ServerUtils::get_template_definition('scroll-searchposts-list'));
define ('GD_TEMPLATE_SCROLL_ALLCONTENT_LIST', PoP_ServerUtils::get_template_definition('scroll-allcontent-list'));
define ('GD_TEMPLATE_SCROLL_LINKS_LIST', PoP_ServerUtils::get_template_definition('scroll-links-list'));
define ('GD_TEMPLATE_SCROLL_HIGHLIGHTS_LIST', PoP_ServerUtils::get_template_definition('scroll-highlights-list'));
define ('GD_TEMPLATE_SCROLL_WEBPOSTS_LIST', PoP_ServerUtils::get_template_definition('scroll-webposts-list'));
define ('GD_TEMPLATE_SCROLL_TAGS_LIST', PoP_ServerUtils::get_template_definition('scroll-tags-list'));

define ('GD_TEMPLATE_SCROLL_SEARCHUSERS_LIST', PoP_ServerUtils::get_template_definition('scroll-searchusers-list'));
define ('GD_TEMPLATE_SCROLL_ALLUSERS_LIST', PoP_ServerUtils::get_template_definition('scroll-allusers-list'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_LIST', PoP_ServerUtils::get_template_definition('scroll-authorfollowers-list'));
define ('GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_LIST', PoP_ServerUtils::get_template_definition('scroll-authorfollowingusers-list'));

define ('GD_TEMPLATE_SCROLL_WHOWEARE_DETAILS', PoP_ServerUtils::get_template_definition('scroll-whoweare-details'));
define ('GD_TEMPLATE_SCROLL_WHOWEARE_THUMBNAIL', PoP_ServerUtils::get_template_definition('scroll-whoweare-thumbnail'));
define ('GD_TEMPLATE_SCROLL_WHOWEARE_LIST', PoP_ServerUtils::get_template_definition('scroll-whoweare-list'));
define ('GD_TEMPLATE_SCROLL_WHOWEARE_FULLVIEW', PoP_ServerUtils::get_template_definition('scroll-whoweare-fullview'));
define ('GD_TEMPLATE_SCROLL_OURSPONSORS', PoP_ServerUtils::get_template_definition('scroll-oursponsors'));
define ('GD_TEMPLATE_SCROLL_OURSUPPORTERS', PoP_ServerUtils::get_template_definition('scroll-oursupporters'));
define ('GD_TEMPLATE_SCROLL_OURSPONSORS_SMALLDETAILS', PoP_ServerUtils::get_template_definition('scroll-oursponsors-smalldetails'));

class GD_Template_Processor_CustomScrolls extends GD_Template_Processor_ScrollsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLL_HOMEMESSAGES,
			GD_TEMPLATE_SCROLL_MYCONTENT_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYCONTENT_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYHIGHLIGHTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_FULLVIEWPREVIEW,
			// GD_TEMPLATE_SCROLL_MYRESOURCES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_NAVIGATOR,
			GD_TEMPLATE_SCROLL_LINKS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_WEBPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ALLUSERS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ALLCONTENT_ADDONS,
			GD_TEMPLATE_SCROLL_LINKS_ADDONS,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_ADDONS,
			GD_TEMPLATE_SCROLL_WEBPOSTS_ADDONS,
			GD_TEMPLATE_SCROLL_ALLUSERS_ADDONS,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLCONTENT_DETAILS,
			GD_TEMPLATE_SCROLL_LINKS_DETAILS,
			GD_TEMPLATE_SCROLL_WEBPOSTS_DETAILS,
			// GD_TEMPLATE_SCROLL_HIGHLIGHTS_DETAILS,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LINKS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_LINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_ALLUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLCONTENT_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LINKS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_WEBPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_LIST,
			GD_TEMPLATE_SCROLL_ALLCONTENT_LIST,
			GD_TEMPLATE_SCROLL_LINKS_LIST,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_LIST,
			GD_TEMPLATE_SCROLL_WEBPOSTS_LIST,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_LIST,
			GD_TEMPLATE_SCROLL_ALLUSERS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_LIST,
			GD_TEMPLATE_SCROLL_WEBPOSTS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_LIST,
			GD_TEMPLATE_SCROLL_TAGS_LIST,
			// GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORLINKS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORHIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_FULLVIEW,
			// GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLEAUTHORS_FULLVIEW,
			GD_TEMPLATE_SCROLL_WHOWEARE_DETAILS,
			GD_TEMPLATE_SCROLL_WHOWEARE_THUMBNAIL,
			GD_TEMPLATE_SCROLL_WHOWEARE_LIST,
			GD_TEMPLATE_SCROLL_WHOWEARE_FULLVIEW,
			GD_TEMPLATE_SCROLL_OURSPONSORS,
			GD_TEMPLATE_SCROLL_OURSUPPORTERS,
			GD_TEMPLATE_SCROLL_OURSPONSORS_SMALLDETAILS,
		);
	}


	function get_inner_template($template_id) {

		$inners = array(
			GD_TEMPLATE_SCROLL_HOMEMESSAGES => GD_TEMPLATE_SCROLLINNER_HOMEMESSAGES,
			GD_TEMPLATE_SCROLL_MYCONTENT_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYCONTENT_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYLINKS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYCONTENT_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYCONTENT_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYLINKS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYHIGHLIGHTS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYHIGHLIGHTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_FULLVIEWPREVIEW,
			// GD_TEMPLATE_SCROLL_MYRESOURCES_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYRESOURCES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_NAVIGATOR,
			GD_TEMPLATE_SCROLL_LINKS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_LINKS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_WEBPOSTS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ALLUSERS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_ALLUSERS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ALLCONTENT_ADDONS => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_ADDONS,
			GD_TEMPLATE_SCROLL_LINKS_ADDONS => GD_TEMPLATE_SCROLLINNER_LINKS_ADDONS,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_ADDONS => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_ADDONS,
			GD_TEMPLATE_SCROLL_WEBPOSTS_ADDONS => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_ADDONS,
			GD_TEMPLATE_SCROLL_ALLUSERS_ADDONS => GD_TEMPLATE_SCROLLINNER_ALLUSERS_ADDONS,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_DETAILS => GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLCONTENT_DETAILS => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_DETAILS,
			GD_TEMPLATE_SCROLL_LINKS_DETAILS => GD_TEMPLATE_SCROLLINNER_LINKS_DETAILS,
			GD_TEMPLATE_SCROLL_WEBPOSTS_DETAILS => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_DETAILS,
			// GD_TEMPLATE_SCROLL_HIGHLIGHTS_DETAILS => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_DETAILS,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_DETAILS => GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLUSERS_DETAILS => GD_TEMPLATE_SCROLLINNER_ALLUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_DETAILS => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_DETAILS => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LINKS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_LINKS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_ALLCONTENT_FULLVIEW => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_LINKS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_LINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_ALLUSERS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_ALLUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLCONTENT_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LINKS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_LINKS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_WEBPOSTS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLUSERS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_ALLUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_LIST => GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_LIST,
			GD_TEMPLATE_SCROLL_ALLCONTENT_LIST => GD_TEMPLATE_SCROLLINNER_ALLCONTENT_LIST,
			GD_TEMPLATE_SCROLL_LINKS_LIST => GD_TEMPLATE_SCROLLINNER_LINKS_LIST,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_LIST => GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_LIST,
			GD_TEMPLATE_SCROLL_WEBPOSTS_LIST => GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LIST,
			GD_TEMPLATE_SCROLL_SEARCHUSERS_LIST => GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_LIST,
			GD_TEMPLATE_SCROLL_ALLUSERS_LIST => GD_TEMPLATE_SCROLLINNER_ALLUSERS_LIST,
			GD_TEMPLATE_SCROLL_TAGS_LIST => GD_TEMPLATE_SCROLLINNER_TAGS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_LIST => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_LIST => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_LIST,
			// GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORLINKS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLINKS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORHIGHLIGHTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORHIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_FULLVIEW,
			// GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_FULLVIEW => GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW => GD_TEMPLATE_SCROLLINNER_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLEAUTHORS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_FULLVIEW,
			GD_TEMPLATE_SCROLL_WHOWEARE_DETAILS => GD_TEMPLATE_SCROLLINNER_WHOWEARE_DETAILS,
			GD_TEMPLATE_SCROLL_WHOWEARE_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_WHOWEARE_THUMBNAIL,
			GD_TEMPLATE_SCROLL_WHOWEARE_LIST => GD_TEMPLATE_SCROLLINNER_WHOWEARE_LIST,
			GD_TEMPLATE_SCROLL_WHOWEARE_FULLVIEW => GD_TEMPLATE_SCROLLINNER_WHOWEARE_FULLVIEW,
			GD_TEMPLATE_SCROLL_OURSPONSORS => GD_TEMPLATE_SCROLLINNER_OURSPONSORS,
			GD_TEMPLATE_SCROLL_OURSUPPORTERS => GD_TEMPLATE_SCROLLINNER_OURSUPPORTERS,
			GD_TEMPLATE_SCROLL_OURSPONSORS_SMALLDETAILS => GD_TEMPLATE_SCROLLINNER_OURSPONSORS_SMALLDETAILS,
		);

		if ($inner = $inners[$template_id]) {

			return $inner;
		}

		return parent::get_inner_template($template_id);
	}

	function init_atts($template_id, &$atts) {
			
		// Extra classes
		$thumbnails = array(
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLCONTENT_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LINKS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_WEBPOSTS_THUMBNAIL,
			
			GD_TEMPLATE_SCROLL_SEARCHUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ALLUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_THUMBNAIL,
			
			GD_TEMPLATE_SCROLL_OURSUPPORTERS,
		
			GD_TEMPLATE_SCROLL_WHOWEARE_THUMBNAIL,
		);
		$independentitem_thumbnails = array(
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_THUMBNAIL,
			// GD_TEMPLATE_SCROLL_WEBPOSTS_THUMBNAIL,
		);
		$lists = array(
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_LIST,
			GD_TEMPLATE_SCROLL_ALLCONTENT_LIST,
			GD_TEMPLATE_SCROLL_LINKS_LIST,
			GD_TEMPLATE_SCROLL_TAGS_LIST,
			GD_TEMPLATE_SCROLL_WEBPOSTS_LIST,
			
			GD_TEMPLATE_SCROLL_SEARCHUSERS_LIST,
			GD_TEMPLATE_SCROLL_ALLUSERS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_LIST,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_LIST,
		
			GD_TEMPLATE_SCROLL_WHOWEARE_LIST,
		);
		$independentitem_lists = array(
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_LIST,
			// GD_TEMPLATE_SCROLL_WEBPOSTS_LIST,
		);
		$details = array(
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLCONTENT_DETAILS,
			GD_TEMPLATE_SCROLL_LINKS_DETAILS,
			GD_TEMPLATE_SCROLL_WEBPOSTS_DETAILS,
			// GD_TEMPLATE_SCROLL_HIGHLIGHTS_DETAILS,
			
			GD_TEMPLATE_SCROLL_SEARCHUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_ALLUSERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_DETAILS,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_DETAILS,

			GD_TEMPLATE_SCROLL_WHOWEARE_DETAILS,
			GD_TEMPLATE_SCROLL_OURSPONSORS,
		);
		$smalldetails = array(
			GD_TEMPLATE_SCROLL_OURSPONSORS_SMALLDETAILS,
		);
		$navigators = array(
			GD_TEMPLATE_SCROLL_ALLCONTENT_NAVIGATOR,			
			GD_TEMPLATE_SCROLL_LINKS_NAVIGATOR,			
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_NAVIGATOR,			
			GD_TEMPLATE_SCROLL_WEBPOSTS_NAVIGATOR,			
			GD_TEMPLATE_SCROLL_ALLUSERS_NAVIGATOR,
		);
		$addons = array(
			GD_TEMPLATE_SCROLL_ALLCONTENT_ADDONS,			
			GD_TEMPLATE_SCROLL_LINKS_ADDONS,			
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_ADDONS,			
			GD_TEMPLATE_SCROLL_WEBPOSTS_ADDONS,			
			GD_TEMPLATE_SCROLL_ALLUSERS_ADDONS,
		);
		$simpleviews = array(
			GD_TEMPLATE_SCROLL_MYCONTENT_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_SIMPLEVIEWPREVIEW,
			
			GD_TEMPLATE_SCROLL_ALLCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LINKS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_SIMPLEVIEW,
			
			// GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORLINKS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW,

			// GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_SCROLL_MYCONTENT_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLINKS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYHIGHLIGHTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYWEBPOSTS_FULLVIEWPREVIEW,
			// GD_TEMPLATE_SCROLL_MYRESOURCES_FULLVIEWPREVIEW,
			
			GD_TEMPLATE_SCROLL_ALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_LINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_HIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_WEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_SEARCHPOSTS_FULLVIEW,
			
			GD_TEMPLATE_SCROLL_SEARCHUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_ALLUSERS_FULLVIEW,

			GD_TEMPLATE_SCROLL_AUTHORALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLINKS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORHIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORWEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORFOLLOWINGUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORRECOMMENDEDPOSTS_FULLVIEW,

			GD_TEMPLATE_SCROLL_SINGLERELATEDCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLL_SINGLEAUTHORS_FULLVIEW,

			GD_TEMPLATE_SCROLL_WHOWEARE_FULLVIEW,
		);
		
		$extra_class = '';
		if (in_array($template_id, $navigators)) {
			$extra_class = 'navigator text-inverse';
		}
		elseif (in_array($template_id, $addons)) {
			$extra_class = 'addons';
		}
		elseif (in_array($template_id, $simpleviews)) {
			$extra_class = 'simpleview';
		}
		elseif (in_array($template_id, $fullviews)) {
			$extra_class = 'fullview';
		}
		elseif (in_array($template_id, $details)) {
			$extra_class = 'details';
		}
		elseif (in_array($template_id, $smalldetails)) {
			$extra_class = 'smalldetails';
		}
		elseif (in_array($template_id, $thumbnails)) {
			$extra_class = 'thumb';
		}
		elseif (in_array($template_id, $independentitem_thumbnails)) {
			$extra_class = 'thumb independent';
		}
		elseif (in_array($template_id, $lists)) {
			$extra_class = 'list';
		}
		elseif (in_array($template_id, $independentitem_lists)) {
			$extra_class = 'list independent';
		}
		$this->append_att($template_id, $atts, 'class', $extra_class);


		$inner = $this->get_inner_template($template_id);
		if (in_array($template_id, $navigators)) {

			// Make it activeItem: highlight on viewing the corresponding fullview
			$this->append_att($inner, $atts, 'class', 'pop-activeitem');
		}
		// elseif (in_array($template_id, $fullviews)) {

			// For the waypoint, save the original URL before it's changed, and change it back when scrolling up the page
			// $this->append_att($template_id, $atts, 'class', 'waypoint template-historystate original');
			// $this->merge_block_jsmethod_att($template_id, $atts, array('waypointsHistoryStateOriginal'));
		// }
		
		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Template_Processor_CustomScrolls();