<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLLINNER_THOUGHTS', PoP_ServerUtils::get_template_definition('scrollinner-thoughts'));
define ('GD_TEMPLATE_SCROLLINNER_HOMEMESSAGES', PoP_ServerUtils::get_template_definition('scrollinner-homemessages'));

define ('GD_TEMPLATE_SCROLLINNER_MYCONTENT_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mycontent-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYLINKS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mylinks-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_SIMPLEVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mywebposts-simpleviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_MYCONTENT_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mycontent-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYLINKS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mylinks-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYHIGHLIGHTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-myhighlights-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-mywebposts-fullviewpreview'));
// define ('GD_TEMPLATE_SCROLLINNER_MYRESOURCES_FULLVIEWPREVIEW', PoP_ServerUtils::get_template_definition('scrollinner-myresources-fullviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-links-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-highlights-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-webposts-navigator'));

define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_NAVIGATOR', PoP_ServerUtils::get_template_definition('scrollinner-allusers-navigator'));

define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-addons'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-links-addons'));
define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-highlights-addons'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-webposts-addons'));

define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_ADDONS', PoP_ServerUtils::get_template_definition('scrollinner-allusers-addons'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-searchposts-details'));
define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-details'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-links-details'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-webposts-details'));
// define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-highlights-details'));
define ('GD_TEMPLATE_SCROLLINNER_TAGS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-tags-details'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-searchusers-details'));
define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-allusers-details'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowers-details'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowingusers-details'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-authorsubscribedtotags-details'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-authorrecommendedposts-details'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-searchposts-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-links-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-webposts-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-searchposts-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-links-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-highlights-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-webposts-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-searchusers-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-allusers-fullview'));

// define ('GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorallcontent-simpleview'));
// define ('GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorlinks-simpleview'));
// define ('GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorwebposts-simpleview'));
// define ('GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorrecommendedposts-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorallcontent-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorlinks-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORHIGHLIGHTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorhighlights-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorwebposts-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowers-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowingusers-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-authorrecommendedposts-fullview'));

// define ('GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_SIMPLEVIEW', PoP_ServerUtils::get_template_definition('scrollinner-singlerelatedcontent-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-singlerelatedcontent-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-singlerelatedhighlightcontent-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-singleauthors-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-searchposts-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-links-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-highlights-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-webposts-thumbnail'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-searchusers-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-allusers-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowers-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowingusers-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-authorrecommendedposts-thumbnail'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-searchposts-list'));
define ('GD_TEMPLATE_SCROLLINNER_ALLCONTENT_LIST', PoP_ServerUtils::get_template_definition('scrollinner-allcontent-list'));
define ('GD_TEMPLATE_SCROLLINNER_LINKS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-links-list'));
define ('GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-highlights-list'));
define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-webposts-list'));
define ('GD_TEMPLATE_SCROLLINNER_TAGS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-tags-list'));

define ('GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LINE', PoP_ServerUtils::get_template_definition('scrollinner-webposts-line'));

define ('GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-searchusers-list'));
define ('GD_TEMPLATE_SCROLLINNER_ALLUSERS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-allusers-list'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowers-list'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-authorfollowingusers-list'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-authorsubscribedtotags-list'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_LIST', PoP_ServerUtils::get_template_definition('scrollinner-authorrecommendedposts-list'));

define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_DETAILS', PoP_ServerUtils::get_template_definition('scrollinner-whoweare-details'));
define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_THUMBNAIL', PoP_ServerUtils::get_template_definition('scrollinner-whoweare-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_LIST', PoP_ServerUtils::get_template_definition('scrollinner-whoweare-list'));
define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_FULLVIEW', PoP_ServerUtils::get_template_definition('scrollinner-whoweare-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_OURSPONSORS', PoP_ServerUtils::get_template_definition('scrollinner-oursponsors'));
define ('GD_TEMPLATE_SCROLLINNER_OURSUPPORTERS', PoP_ServerUtils::get_template_definition('scrollinner-oursupporters'));
define ('GD_TEMPLATE_SCROLLINNER_OURSPONSORS_SMALLDETAILS', PoP_ServerUtils::get_template_definition('scrollinner-oursponsors-smalldetails'));


class GD_Template_Processor_CustomScrollInners extends GD_Template_Processor_ScrollInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLLINNER_HOMEMESSAGES,
			GD_TEMPLATE_SCROLLINNER_MYCONTENT_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYLINKS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYCONTENT_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYLINKS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYHIGHLIGHTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_FULLVIEWPREVIEW,
			// GD_TEMPLATE_SCROLLINNER_MYRESOURCES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_LINKS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_ADDONS,
			GD_TEMPLATE_SCROLLINNER_LINKS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_DETAILS,
			GD_TEMPLATE_SCROLLINNER_LINKS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_DETAILS,
			// GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_TAGS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_LINKS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_LINKS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_LINKS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_LIST,
			GD_TEMPLATE_SCROLLINNER_ALLCONTENT_LIST,
			GD_TEMPLATE_SCROLLINNER_LINKS_LIST,
			GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_LIST,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LIST,
			GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_LIST,
			GD_TEMPLATE_SCROLLINNER_ALLUSERS_LIST,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_LIST,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_LIST,
			GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_LIST,
			GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_LIST,
			GD_TEMPLATE_SCROLLINNER_TAGS_LIST,
			GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LINE,
			// GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_SIMPLEVIEW,
			// GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORHIGHLIGHTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_FULLVIEW,
			// GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_DETAILS,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_LIST,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_OURSPONSORS,
			GD_TEMPLATE_SCROLLINNER_OURSUPPORTERS,
			GD_TEMPLATE_SCROLLINNER_OURSPONSORS_SMALLDETAILS,
		);
	}

	function get_layout_grid($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_LINKS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_THUMBNAIL:
			
			case GD_TEMPLATE_SCROLLINNER_OURSUPPORTERS:

				// Allow ThemeStyle Expansive to override the grid
				return apply_filters(
					POP_HOOK_SCROLLINNER_THUMBNAIL_GRID, 
					array(
						'row-items' => 2, 
						'class' => 'col-xsm-6'
					)
				);

			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_THUMBNAIL:

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_THUMBNAIL:

				return array(
					'row-items' => 4, 
					'class' => 'col-xsm-3'
				);

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_LIST:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_OURSPONSORS:
			case GD_TEMPLATE_SCROLLINNER_HOMEMESSAGES:

			case GD_TEMPLATE_SCROLLINNER_MYCONTENT_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYLINKS_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_SIMPLEVIEWPREVIEW:

			case GD_TEMPLATE_SCROLLINNER_MYCONTENT_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYLINKS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYHIGHLIGHTS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_FULLVIEWPREVIEW:
			// case GD_TEMPLATE_SCROLLINNER_MYRESOURCES_FULLVIEWPREVIEW:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_LINKS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_NAVIGATOR:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_LINKS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_ADDONS:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_LINKS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_DETAILS:
			// case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_TAGS_DETAILS:
			
			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_DETAILS:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_LINKS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_SIMPLEVIEW:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_LINKS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_FULLVIEW:
			
			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_FULLVIEW:

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_LIST:
			case GD_TEMPLATE_SCROLLINNER_LINKS_LIST:
			case GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_TAGS_LIST:
			
			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_LIST:

			case GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LINE:

			// case GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_SIMPLEVIEW:
			// case GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_SIMPLEVIEW:
			// case GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_SIMPLEVIEW:
			// case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW:

			case GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORHIGHLIGHTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_FULLVIEW:

			// case GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_SIMPLEVIEW:

			case GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW:

			case GD_TEMPLATE_SCROLLINNER_OURSPONSORS_SMALLDETAILS:

				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12'
				);
		}

		return parent::get_layout_grid($template_id, $atts);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_NAVIGATOR:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_NAVIGATOR;
				break;

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_ADDONS:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_ADDONS;
				break;

			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_NAVIGATOR:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_NAVIGATOR;
				break;

			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_ADDONS:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_ADDONS;
				break;

			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_DETAILS:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_DETAILS:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_DETAILS:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_THUMBNAIL:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_THUMBNAIL:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_THUMBNAIL:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_LIST:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_LIST;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_LIST:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_LIST:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_LIST;
				break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_LIST:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_LIST:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_LIST;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYCONTENT_SIMPLEVIEWPREVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWPOST_MULTIPLESIMPLEVIEW;//GD_TEMPLATE_LAYOUT_MULTIPLEPOST_SIMPLEVIEW;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHPOSTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_ALLCONTENT_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYCONTENT_FULLVIEWPREVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEPOST_FULLVIEW;
				break;

			case GD_TEMPLATE_SCROLLINNER_SEARCHUSERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_ALLUSERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_FULLVIEW:
				
				$ret[] = GD_TEMPLATE_LAYOUT_MULTIPLEUSER_FULLUSER;
				break;
			
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWERS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORFOLLOWINGUSERS_FULLVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEUSER_FULLUSER;
				break;

			case GD_TEMPLATE_SCROLLINNER_SINGLEAUTHORS_FULLVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_SINGLEMULTIPLEUSER_FULLUSER;
				break;

			// case GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_SIMPLEVIEW:
			// case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_SIMPLEVIEW:

			// 	$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEPOST_SIMPLEVIEW;
			// 	break;

			case GD_TEMPLATE_SCROLLINNER_AUTHORALLCONTENT_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORRECOMMENDEDPOSTS_FULLVIEW:

				$ret[] = GD_TEMPLATE_LAYOUT_AUTHORMULTIPLEPOST_FULLVIEW;
				break;

			// case GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_SIMPLEVIEW:
		
			// 	$ret[] = GD_TEMPLATE_LAYOUT_SINGLEMULTIPLEPOST_SIMPLEVIEW;
			// 	break;

			case GD_TEMPLATE_SCROLLINNER_SINGLERELATEDCONTENT_FULLVIEW:
		
				$ret[] = GD_TEMPLATE_LAYOUT_SINGLEMULTIPLEPOST_FULLVIEW;
				break;

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_OURSPONSORS:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_SPONSOR_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_OURSUPPORTERS:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_SPONSOR_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_OURSPONSORS_SMALLDETAILS:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_SPONSOR_SMALLDETAILS;
				break;

			default:

				$layouts = array(
					GD_TEMPLATE_SCROLLINNER_HOMEMESSAGES => GD_TEMPLATE_ALERT_HOMEMESSAGE,
					
					// GD_TEMPLATE_SCROLLINNER_MYRESOURCES_FULLVIEWPREVIEW => null,
				
					GD_TEMPLATE_SCROLLINNER_LINKS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_CONTENT, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_NAVIGATOR, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_NAVIGATOR,

					GD_TEMPLATE_SCROLLINNER_LINKS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_ADDONS,
					GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_CONTENT, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_ADDONS,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_ADDONS, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_ADDONS,

					GD_TEMPLATE_SCROLLINNER_LINKS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_DETAILS,
					// Allow to override for compatibility issues
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_DETAILS => apply_filters('GD_Template_Processor_CustomScrollInners:layout:webpost', GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_DETAILS),
					// GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_CONTENT, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_DETAILS,
					GD_TEMPLATE_SCROLLINNER_TAGS_DETAILS => GD_TEMPLATE_LAYOUT_TAG_DETAILS,
					GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_DETAILS => GD_TEMPLATE_LAYOUT_TAG_DETAILS,

					GD_TEMPLATE_SCROLLINNER_LINKS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_CONTENT, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_THUMBNAIL, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_THUMBNAIL,

					GD_TEMPLATE_SCROLLINNER_LINKS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_LIST,
					GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_CONTENT, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_LIST,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_LIST, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_HIGHLIGHT_LIST,
					GD_TEMPLATE_SCROLLINNER_TAGS_LIST => GD_TEMPLATE_LAYOUT_TAG,
					GD_TEMPLATE_SCROLLINNER_AUTHORSUBSCRIBEDTOTAGS_LIST => GD_TEMPLATE_LAYOUT_TAG,

					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_LINE => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LINE,
					
					GD_TEMPLATE_SCROLLINNER_LINKS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_SIMPLEVIEW,

					GD_TEMPLATE_SCROLLINNER_LINKS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_LINK,
					GD_TEMPLATE_SCROLLINNER_HIGHLIGHTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_HIGHLIGHT,
					GD_TEMPLATE_SCROLLINNER_WEBPOSTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_WEBPOST,
					GD_TEMPLATE_SCROLLINNER_SINGLERELATEDHIGHLIGHTCONTENT_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_HIGHLIGHT,

					// GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_SIMPLEVIEW => GD_TEMPLATE_AUTHORLAYOUT_SIMPLEVIEW_LINK,
					// GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_SIMPLEVIEW => GD_TEMPLATE_AUTHORLAYOUT_SIMPLEVIEW_WEBPOST,

					GD_TEMPLATE_SCROLLINNER_AUTHORLINKS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_LINK,
					GD_TEMPLATE_SCROLLINNER_AUTHORHIGHLIGHTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_HIGHLIGHT,
					GD_TEMPLATE_SCROLLINNER_AUTHORWEBPOSTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_WEBPOST,

					GD_TEMPLATE_SCROLLINNER_MYLINKS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOSTLINK_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_WEBPOST_SIMPLEVIEW,

					GD_TEMPLATE_SCROLLINNER_MYLINKS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_LINK,
					GD_TEMPLATE_SCROLLINNER_MYHIGHLIGHTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_HIGHLIGHT,
					GD_TEMPLATE_SCROLLINNER_MYWEBPOSTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_WEBPOST,
				);

				if ($layout = $layouts[$template_id]) {

					$ret[] = $layout;
				}
				break;
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Template_Processor_CustomScrollInners();