{
  postTags: tags(taxonomy: post_tag) {
    ...TagData
  }
  postTag: tag(taxonomy: post_tag, by: { id: 15 }) {
    ...TagData
  }
  postTagCount: tagCount(taxonomy: post_tag)
  postTagNames: tagNames(taxonomy: post_tag)

  dummyTags: tags(taxonomy: "dummy-tag") {
    ...TagData
  }
  dummyTag: tag(taxonomy: "dummy-tag", by: { id: 36 }) {
    ...TagData
  }
  dummyTagCount: tagCount(taxonomy: "dummy-tag")
  dummyTagNames: tagNames(taxonomy: "dummy-tag")

  postFormats: tags(taxonomy: post_format) {
    ...TagData
  }
  postFormat: tag(taxonomy: post_format, by: { id: 43 }) {
    ...TagData
  }
  postFormatCount: tagCount(taxonomy: post_format)
  # Watch out, there's a bug in WP:
  # Executing `get_tags($query)` with `$query['taxonomy'] = "post_format"` does not bring the names!
  # That's why the response for this field in tags:1.json is empty
  postFormatNames: tagNames(taxonomy: post_format)
}

fragment TagData on Tag {
  __typename
  taxonomy
  id
  name
}
