<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLL_THOUGHTS', PoP_TemplateIDUtils::get_template_definition('scroll-thoughts'));

define ('GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-myannouncements-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYDISCUSSIONS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mydiscussions-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mylocationposts-fullviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYSTORIES_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mystories-fullviewpreview'));

define ('GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-myannouncements-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYDISCUSSIONS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mydiscussions-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mylocationposts-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLL_MYSTORIES_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-mystories-simpleviewpreview'));

define ('GD_TEMPLATE_SCROLL_BLOG_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-blog-navigator'));
define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-navigator'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-navigator'));
define ('GD_TEMPLATE_SCROLL_FEATURED_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-featured-navigator'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-navigator'));
define ('GD_TEMPLATE_SCROLL_STORIES_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scroll-stories-navigator'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-addons'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-addons'));
define ('GD_TEMPLATE_SCROLL_FEATURED_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-featured-addons'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-addons'));
define ('GD_TEMPLATE_SCROLL_STORIES_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-stories-addons'));
define ('GD_TEMPLATE_SCROLL_BLOG_ADDONS', PoP_TemplateIDUtils::get_template_definition('scroll-blog-addons'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-details'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-details'));
define ('GD_TEMPLATE_SCROLL_FEATURED_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-featured-details'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-details'));
define ('GD_TEMPLATE_SCROLL_STORIES_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-stories-details'));
define ('GD_TEMPLATE_SCROLL_BLOG_DETAILS', PoP_TemplateIDUtils::get_template_definition('scroll-blog-details'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-simpleview'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-simpleview'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-simpleview'));
define ('GD_TEMPLATE_SCROLL_STORIES_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-stories-simpleview'));
define ('GD_TEMPLATE_SCROLL_FEATURED_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-featured-simpleview'));
define ('GD_TEMPLATE_SCROLL_BLOG_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-blog-simpleview'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-fullview'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-fullview'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-fullview'));
define ('GD_TEMPLATE_SCROLL_STORIES_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-stories-fullview'));
define ('GD_TEMPLATE_SCROLL_FEATURED_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-featured-fullview'));
define ('GD_TEMPLATE_SCROLL_BLOG_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-blog-fullview'));

define ('GD_TEMPLATE_SCROLL_AUTHORANNOUNCEMENTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-authorannouncements-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORDISCUSSIONS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-authordiscussions-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORLOCATIONPOSTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-authorlocationposts-fullview'));
define ('GD_TEMPLATE_SCROLL_AUTHORSTORIES_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scroll-authorstories-fullview'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-thumbnail'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-thumbnail'));
define ('GD_TEMPLATE_SCROLL_FEATURED_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-featured-thumbnail'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-thumbnail'));
define ('GD_TEMPLATE_SCROLL_STORIES_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-stories-thumbnail'));
// define ('GD_TEMPLATE_SCROLL_BLOG_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scroll-blog-thumbnail'));

define ('GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-announcements-list'));
define ('GD_TEMPLATE_SCROLL_DISCUSSIONS_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-discussions-list'));
define ('GD_TEMPLATE_SCROLL_FEATURED_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-featured-list'));
define ('GD_TEMPLATE_SCROLL_LOCATIONPOSTS_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-locationposts-list'));
define ('GD_TEMPLATE_SCROLL_STORIES_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-stories-list'));
define ('GD_TEMPLATE_SCROLL_BLOG_LIST', PoP_TemplateIDUtils::get_template_definition('scroll-blog-list'));

define ('GD_TEMPLATE_SCROLL_WHOWEARE_CORE', PoP_TemplateIDUtils::get_template_definition('scroll-whoweare-core'));
define ('GD_TEMPLATE_SCROLL_WHOWEARE_VOLUNTEERS', PoP_TemplateIDUtils::get_template_definition('scroll-whoweare-volunteers'));
define ('GD_TEMPLATE_SCROLL_WHOWEARE_ADVISORS', PoP_TemplateIDUtils::get_template_definition('scroll-whoweare-advisors'));

class GD_Custom_Template_Processor_CustomScrolls extends GD_Template_Processor_ScrollsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLL_THOUGHTS,
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_BLOG_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_FEATURED_NAVIGATOR,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_STORIES_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_ADDONS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_ADDONS,
			GD_TEMPLATE_SCROLL_FEATURED_ADDONS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_ADDONS,
			GD_TEMPLATE_SCROLL_STORIES_ADDONS,
			GD_TEMPLATE_SCROLL_BLOG_ADDONS,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_DETAILS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_DETAILS,
			GD_TEMPLATE_SCROLL_FEATURED_DETAILS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_STORIES_DETAILS,
			GD_TEMPLATE_SCROLL_BLOG_DETAILS,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_STORIES_FULLVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_FULLVIEW,
			GD_TEMPLATE_SCROLL_BLOG_FULLVIEW,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_STORIES_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_BLOG_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_FEATURED_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_STORIES_THUMBNAIL,
			// GD_TEMPLATE_SCROLL_BLOG_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_LIST,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_LIST,
			GD_TEMPLATE_SCROLL_FEATURED_LIST,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_LIST,
			GD_TEMPLATE_SCROLL_STORIES_LIST,
			GD_TEMPLATE_SCROLL_BLOG_LIST,
			GD_TEMPLATE_SCROLL_AUTHORANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORDISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORSTORIES_FULLVIEW,
			GD_TEMPLATE_SCROLL_WHOWEARE_ADVISORS,
			GD_TEMPLATE_SCROLL_WHOWEARE_CORE,
			GD_TEMPLATE_SCROLL_WHOWEARE_VOLUNTEERS,
		);
	}


	function get_inner_template($template_id) {

		$inners = array(
			GD_TEMPLATE_SCROLL_THOUGHTS => GD_TEMPLATE_SCROLLINNER_THOUGHTS,
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_SIMPLEVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYSTORIES_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_FULLVIEWPREVIEW => GD_TEMPLATE_SCROLLINNER_MYSTORIES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_BLOG_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_BLOG_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_FEATURED_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_FEATURED_NAVIGATOR,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_STORIES_NAVIGATOR => GD_TEMPLATE_SCROLLINNER_STORIES_NAVIGATOR,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_ADDONS => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_ADDONS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_ADDONS => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_ADDONS,
			GD_TEMPLATE_SCROLL_FEATURED_ADDONS => GD_TEMPLATE_SCROLLINNER_FEATURED_ADDONS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_ADDONS => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_ADDONS,
			GD_TEMPLATE_SCROLL_STORIES_ADDONS => GD_TEMPLATE_SCROLLINNER_STORIES_ADDONS,
			GD_TEMPLATE_SCROLL_BLOG_ADDONS => GD_TEMPLATE_SCROLLINNER_BLOG_ADDONS,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_DETAILS => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_DETAILS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_DETAILS => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_DETAILS,
			GD_TEMPLATE_SCROLL_FEATURED_DETAILS => GD_TEMPLATE_SCROLLINNER_FEATURED_DETAILS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_DETAILS => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_STORIES_DETAILS => GD_TEMPLATE_SCROLLINNER_STORIES_DETAILS,
			GD_TEMPLATE_SCROLL_BLOG_DETAILS => GD_TEMPLATE_SCROLLINNER_BLOG_DETAILS,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_STORIES_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_STORIES_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_FEATURED_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_BLOG_SIMPLEVIEW => GD_TEMPLATE_SCROLLINNER_BLOG_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_STORIES_FULLVIEW => GD_TEMPLATE_SCROLLINNER_STORIES_FULLVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_FULLVIEW => GD_TEMPLATE_SCROLLINNER_FEATURED_FULLVIEW,
			GD_TEMPLATE_SCROLL_BLOG_FULLVIEW => GD_TEMPLATE_SCROLLINNER_BLOG_FULLVIEW,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_FEATURED_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_FEATURED_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_STORIES_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_STORIES_THUMBNAIL,
			// GD_TEMPLATE_SCROLL_BLOG_THUMBNAIL => GD_TEMPLATE_SCROLLINNER_BLOG_THUMBNAIL,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_LIST => GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_LIST,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_LIST => GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_LIST,
			GD_TEMPLATE_SCROLL_FEATURED_LIST => GD_TEMPLATE_SCROLLINNER_FEATURED_LIST,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_LIST => GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_LIST,
			GD_TEMPLATE_SCROLL_STORIES_LIST => GD_TEMPLATE_SCROLLINNER_STORIES_LIST,
			GD_TEMPLATE_SCROLL_BLOG_LIST => GD_TEMPLATE_SCROLLINNER_BLOG_LIST,
			GD_TEMPLATE_SCROLL_AUTHORANNOUNCEMENTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORDISCUSSIONS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORDISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLOCATIONPOSTS_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORLOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORSTORIES_FULLVIEW => GD_TEMPLATE_SCROLLINNER_AUTHORSTORIES_FULLVIEW,
			GD_TEMPLATE_SCROLL_WHOWEARE_ADVISORS => GD_TEMPLATE_SCROLLINNER_WHOWEARE_ADVISORS,
			GD_TEMPLATE_SCROLL_WHOWEARE_CORE => GD_TEMPLATE_SCROLLINNER_WHOWEARE_CORE,
			GD_TEMPLATE_SCROLL_WHOWEARE_VOLUNTEERS => GD_TEMPLATE_SCROLLINNER_WHOWEARE_VOLUNTEERS,
		);

		if ($inner = $inners[$template_id]) {

			return $inner;
		}

		return parent::get_inner_template($template_id);
	}

	function init_atts($template_id, &$atts) {
			
		// Extra classes
		$thumbnails = array(
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLL_FEATURED_THUMBNAIL,
			GD_TEMPLATE_SCROLL_STORIES_THUMBNAIL,

			GD_TEMPLATE_SCROLL_WHOWEARE_ADVISORS,
			GD_TEMPLATE_SCROLL_WHOWEARE_VOLUNTEERS,
		);
		$lists = array(
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_LIST,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_LIST,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_LIST,
			GD_TEMPLATE_SCROLL_FEATURED_LIST,
			GD_TEMPLATE_SCROLL_STORIES_LIST,
			GD_TEMPLATE_SCROLL_BLOG_LIST,
		);
		$details = array(
			GD_TEMPLATE_SCROLL_BLOG_DETAILS,
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_DETAILS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_DETAILS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_DETAILS,
			GD_TEMPLATE_SCROLL_FEATURED_DETAILS,
			GD_TEMPLATE_SCROLL_STORIES_DETAILS,

			GD_TEMPLATE_SCROLL_WHOWEARE_CORE,
		);
		$navigators = array(
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_FEATURED_NAVIGATOR,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLL_STORIES_NAVIGATOR,
			GD_TEMPLATE_SCROLL_BLOG_NAVIGATOR,
		);
		$addons = array(
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_ADDONS,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_ADDONS,
			GD_TEMPLATE_SCROLL_FEATURED_ADDONS,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_ADDONS,
			GD_TEMPLATE_SCROLL_STORIES_ADDONS,
			GD_TEMPLATE_SCROLL_BLOG_ADDONS,
		);
		$simpleviews = array(
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_SIMPLEVIEWPREVIEW,
			
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_STORIES_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_SIMPLEVIEW,
			GD_TEMPLATE_SCROLL_BLOG_SIMPLEVIEW,
		);
		$fullviews = array(
			GD_TEMPLATE_SCROLL_MYANNOUNCEMENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYDISCUSSIONS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYLOCATIONPOSTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLL_MYSTORIES_FULLVIEWPREVIEW,
			
			GD_TEMPLATE_SCROLL_ANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_DISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_LOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_STORIES_FULLVIEW,
			GD_TEMPLATE_SCROLL_FEATURED_FULLVIEW,
			GD_TEMPLATE_SCROLL_BLOG_FULLVIEW,
			
			GD_TEMPLATE_SCROLL_AUTHORANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORDISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORLOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLL_AUTHORSTORIES_FULLVIEW,
		);

		$extra_class = '';
		if (in_array($template_id, $navigators)) {
			$extra_class = 'navigator text-inverse';
		}
		elseif (in_array($template_id, $addons)) {
			$extra_class = 'addons';
		}
		elseif (in_array($template_id, $simpleviews)) {
			$extra_class = 'simpleview';
		}
		elseif (in_array($template_id, $fullviews)) {
			$extra_class = 'fullview';
		}
		elseif (in_array($template_id, $details)) {
			$extra_class = 'details';
		}
		elseif (in_array($template_id, $thumbnails)) {
			$extra_class = 'thumb';
		}
		elseif (in_array($template_id, $lists)) {
			$extra_class = 'list';
		}
		$this->append_att($template_id, $atts, 'class', $extra_class);


		$inner = $this->get_inner_template($template_id);
		if (in_array($template_id, $navigators)) {

			// Make it activeItem: highlight on viewing the corresponding fullview
			$this->append_att($inner, $atts, 'class', 'pop-activeitem');
		}
		// elseif (in_array($template_id, $fullviews)) {

			// For the waypoint, save the original URL before it's changed, and change it back when scrolling up the page
			// $this->append_att($template_id, $atts, 'class', 'waypoint template-historystate original');
			// $this->merge_block_jsmethod_att($template_id, $atts, array('waypointsHistoryStateOriginal'));
		// }
		
		return parent::init_atts($template_id, $atts);
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_CustomScrolls();