<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_SCROLLINNER_THOUGHTS', PoP_TemplateIDUtils::get_template_definition('scrollinner-thoughts'));

define ('GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-myannouncements-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mydiscussions-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mylocationposts-simpleviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYSTORIES_SIMPLEVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mystories-simpleviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-myannouncements-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mydiscussions-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mylocationposts-fullviewpreview'));
define ('GD_TEMPLATE_SCROLLINNER_MYSTORIES_FULLVIEWPREVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-mystories-fullviewpreview'));

define ('GD_TEMPLATE_SCROLLINNER_BLOG_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-navigator'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_NAVIGATOR', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-navigator'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-addons'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-addons'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-addons'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-addons'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-addons'));
define ('GD_TEMPLATE_SCROLLINNER_BLOG_ADDONS', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-addons'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-details'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-details'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-details'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-details'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-details'));
define ('GD_TEMPLATE_SCROLLINNER_BLOG_DETAILS', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-details'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-simpleview'));
define ('GD_TEMPLATE_SCROLLINNER_BLOG_SIMPLEVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-simpleview'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_BLOG_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_AUTHORANNOUNCEMENTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-authorannouncements-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORDISCUSSIONS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-authordiscussions-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORLOCATIONPOSTS_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-authorlocationposts-fullview'));
define ('GD_TEMPLATE_SCROLLINNER_AUTHORSTORIES_FULLVIEW', PoP_TemplateIDUtils::get_template_definition('scrollinner-authorstories-fullview'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-thumbnail'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-thumbnail'));
// define ('GD_TEMPLATE_SCROLLINNER_BLOG_THUMBNAIL', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-thumbnail'));

define ('GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-announcements-list'));
define ('GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-discussions-list'));
define ('GD_TEMPLATE_SCROLLINNER_FEATURED_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-featured-list'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-list'));
define ('GD_TEMPLATE_SCROLLINNER_STORIES_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-stories-list'));
define ('GD_TEMPLATE_SCROLLINNER_BLOG_LIST', PoP_TemplateIDUtils::get_template_definition('scrollinner-blog-list'));

define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_MAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-map'));
define ('GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_HORIZONTALMAP', PoP_TemplateIDUtils::get_template_definition('scrollinner-locationposts-horizontalmap'));

define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_CORE', PoP_TemplateIDUtils::get_template_definition('scrollinner-whoweare-core'));
define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_VOLUNTEERS', PoP_TemplateIDUtils::get_template_definition('scrollinner-whoweare-volunteers'));
define ('GD_TEMPLATE_SCROLLINNER_WHOWEARE_ADVISORS', PoP_TemplateIDUtils::get_template_definition('scrollinner-whoweare-advisors'));

class GD_Custom_Template_Processor_CustomScrollInners extends GD_Template_Processor_ScrollInnersBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_SCROLLINNER_THOUGHTS,
			GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYSTORIES_FULLVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_MYSTORIES_SIMPLEVIEWPREVIEW,
			GD_TEMPLATE_SCROLLINNER_BLOG_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_FEATURED_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_STORIES_NAVIGATOR,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_FEATURED_ADDONS,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_ADDONS,
			GD_TEMPLATE_SCROLLINNER_STORIES_ADDONS,
			GD_TEMPLATE_SCROLLINNER_BLOG_ADDONS,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_FEATURED_DETAILS,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_DETAILS,
			GD_TEMPLATE_SCROLLINNER_STORIES_DETAILS,
			GD_TEMPLATE_SCROLLINNER_BLOG_DETAILS,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_STORIES_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_FEATURED_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_BLOG_SIMPLEVIEW,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_STORIES_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_FEATURED_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_BLOG_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_FEATURED_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_STORIES_THUMBNAIL,
			// GD_TEMPLATE_SCROLLINNER_BLOG_THUMBNAIL,
			GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_LIST,
			GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_LIST,
			GD_TEMPLATE_SCROLLINNER_FEATURED_LIST,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_LIST,
			GD_TEMPLATE_SCROLLINNER_STORIES_LIST,
			GD_TEMPLATE_SCROLLINNER_BLOG_LIST,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_MAP,
			GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_HORIZONTALMAP,
			GD_TEMPLATE_SCROLLINNER_AUTHORANNOUNCEMENTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORDISCUSSIONS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORLOCATIONPOSTS_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_AUTHORSTORIES_FULLVIEW,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_ADVISORS,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_CORE,
			GD_TEMPLATE_SCROLLINNER_WHOWEARE_VOLUNTEERS,
		);
	}

	function get_layout_grid($template_id, $atts) {

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_THUMBNAIL:
			case GD_TEMPLATE_SCROLLINNER_STORIES_THUMBNAIL:
			// case GD_TEMPLATE_SCROLLINNER_BLOG_THUMBNAIL:

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_ADVISORS:
			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_VOLUNTEERS:

				// Allow ThemeStyle Expansive to override the grid
				return apply_filters(
					POP_HOOK_SCROLLINNER_THUMBNAIL_GRID, 
					array(
						'row-items' => 2, 
						'class' => 'col-xsm-6'
					)
				);

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_CORE:
			
			case GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYSTORIES_SIMPLEVIEWPREVIEW:
			
			case GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_FULLVIEWPREVIEW:
			case GD_TEMPLATE_SCROLLINNER_MYSTORIES_FULLVIEWPREVIEW:
			
			case GD_TEMPLATE_SCROLLINNER_BLOG_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_NAVIGATOR:
			case GD_TEMPLATE_SCROLLINNER_STORIES_NAVIGATOR:
			
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_STORIES_ADDONS:
			case GD_TEMPLATE_SCROLLINNER_BLOG_ADDONS:
			
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_STORIES_DETAILS:
			case GD_TEMPLATE_SCROLLINNER_BLOG_DETAILS:
			
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_STORIES_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_SIMPLEVIEW:
			case GD_TEMPLATE_SCROLLINNER_BLOG_SIMPLEVIEW:
			
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_STORIES_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_BLOG_FULLVIEW:
			
			case GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_LIST:
			case GD_TEMPLATE_SCROLLINNER_FEATURED_LIST:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_LIST:
			case GD_TEMPLATE_SCROLLINNER_STORIES_LIST:
			case GD_TEMPLATE_SCROLLINNER_BLOG_LIST:

			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_MAP:
			case GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_HORIZONTALMAP:
			
			case GD_TEMPLATE_SCROLLINNER_AUTHORANNOUNCEMENTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORDISCUSSIONS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORLOCATIONPOSTS_FULLVIEW:
			case GD_TEMPLATE_SCROLLINNER_AUTHORSTORIES_FULLVIEW:
			
				return array(
					'row-items' => 1, 
					'class' => 'col-sm-12'
				);
		}

		return parent::get_layout_grid($template_id, $atts);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		switch ($template_id) {

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_CORE:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_TEAMSTAFF_DETAILS;
				break;

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_VOLUNTEERS:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_TEAMSTAFF_THUMBNAIL;
				break;

			case GD_TEMPLATE_SCROLLINNER_WHOWEARE_ADVISORS:

				$ret[] = GD_TEMPLATE_LAYOUT_PREVIEWUSER_INDIVIDUAL_NAVIGATOR;
				break;

			default:

				$layouts = array(
					GD_TEMPLATE_SCROLLINNER_THOUGHTS => GD_TEMPLATE_TALKINGSPEECHBUBBLE_THOUGHT,

					GD_TEMPLATE_SCROLLINNER_BLOG_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_BLOG_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_FEATURED_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_NAVIGATOR,
					GD_TEMPLATE_SCROLLINNER_STORIES_NAVIGATOR => GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_NAVIGATOR,

					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_ADDONS,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_ADDONS,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_ADDONS,
					GD_TEMPLATE_SCROLLINNER_FEATURED_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_ADDONS,
					GD_TEMPLATE_SCROLLINNER_STORIES_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_ADDONS,
					GD_TEMPLATE_SCROLLINNER_BLOG_ADDONS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_BLOG_ADDONS,

					GD_TEMPLATE_SCROLLINNER_BLOG_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_BLOG_DETAILS,
					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_DETAILS,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_DETAILS,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_DETAILS,
					GD_TEMPLATE_SCROLLINNER_FEATURED_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_DETAILS,
					GD_TEMPLATE_SCROLLINNER_STORIES_DETAILS => GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_DETAILS,

					// GD_TEMPLATE_SCROLLINNER_BLOG_THUMBNAIL => GD_TEMPLATE_LAYOUT_NOTHUMBPREVIEWPOST_BLOG,
					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_FEATURED_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_THUMBNAIL,
					GD_TEMPLATE_SCROLLINNER_STORIES_THUMBNAIL => GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_THUMBNAIL,

					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_LIST,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_LIST,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_LIST,
					GD_TEMPLATE_SCROLLINNER_FEATURED_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_LIST,
					GD_TEMPLATE_SCROLLINNER_STORIES_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_LIST,
					GD_TEMPLATE_SCROLLINNER_BLOG_LIST => GD_TEMPLATE_LAYOUT_PREVIEWPOST_BLOG_LIST,

					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_MAP => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_MAPDETAILS,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_HORIZONTALMAP => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_HORIZONTALMAPDETAILS,

					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_FEATURED_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_FEATURED_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_STORIES_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_BLOG_SIMPLEVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_BLOG_SIMPLEVIEW,

					GD_TEMPLATE_SCROLLINNER_ANNOUNCEMENTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_ANNOUNCEMENT,
					GD_TEMPLATE_SCROLLINNER_DISCUSSIONS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_DISCUSSION,
					GD_TEMPLATE_SCROLLINNER_LOCATIONPOSTS_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_LOCATIONPOST,				
					GD_TEMPLATE_SCROLLINNER_STORIES_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_STORY,
					GD_TEMPLATE_SCROLLINNER_FEATURED_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_FEATURED,
					GD_TEMPLATE_SCROLLINNER_BLOG_FULLVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_BLOG,

					GD_TEMPLATE_SCROLLINNER_AUTHORANNOUNCEMENTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_ANNOUNCEMENT,
					GD_TEMPLATE_SCROLLINNER_AUTHORDISCUSSIONS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_DISCUSSION,
					GD_TEMPLATE_SCROLLINNER_AUTHORLOCATIONPOSTS_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_LOCATIONPOST,				
					GD_TEMPLATE_SCROLLINNER_AUTHORSTORIES_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_STORY,
					GD_TEMPLATE_SCROLLINNER_AUTHORFEATURED_FULLVIEW => GD_TEMPLATE_AUTHORLAYOUT_FULLVIEW_FEATURED,

					GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_ANNOUNCEMENT_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_DISCUSSION_SIMPLEVIEW,
					GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_LOCATIONPOST_SIMPLEVIEW,				
					GD_TEMPLATE_SCROLLINNER_MYSTORIES_SIMPLEVIEWPREVIEW => GD_TEMPLATE_LAYOUT_PREVIEWPOST_SIMPLEVIEW, //GD_TEMPLATE_LAYOUT_PREVIEWPOST_STORY_SIMPLEVIEW,

					GD_TEMPLATE_SCROLLINNER_MYANNOUNCEMENTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_ANNOUNCEMENT,
					GD_TEMPLATE_SCROLLINNER_MYDISCUSSIONS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_DISCUSSION,
					GD_TEMPLATE_SCROLLINNER_MYLOCATIONPOSTS_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_LOCATIONPOST,				
					GD_TEMPLATE_SCROLLINNER_MYSTORIES_FULLVIEWPREVIEW => GD_TEMPLATE_LAYOUT_FULLVIEW_STORY,
				);

				if ($layout = $layouts[$template_id]) {

					$ret[] = $layout;
				}
				break;
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_CustomScrollInners();