<?php

define ('GD_DATALOAD_QUERYHANDLERRESPONSE_ERRORCODES', 'errorcodes');
define ('GD_DATALOAD_QUERYHANDLERRESPONSE_ERRORSTRINGS', 'errorstrings');
define ('GD_DATALOAD_QUERYHANDLERRESPONSE_SUCCESS', 'success');
define ('GD_DATALOAD_QUERYHANDLERRESPONSE_SUCCESSSTRINGS', 'successstrings');
