<?php

const GD_DATALOAD_QUERYHANDLERRESPONSE_ERRORCODES = 'errorcodes';
const GD_DATALOAD_QUERYHANDLERRESPONSE_ERRORSTRINGS = 'errorstrings';
const GD_DATALOAD_QUERYHANDLERRESPONSE_SUCCESS = 'success';
const GD_DATALOAD_QUERYHANDLERRESPONSE_SUCCESSSTRINGS = 'successstrings';
