<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

class GetPoP_Processors_Template_SettingsProcessor extends GD_Template_SettingsProcessorBase {

	function get_page_blockgroups($hierarchy, $include_common = true) {

		$ret = array();

		// Page or Home
		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE) {

			$pageblockgroups = array(
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_OVERVIEW => GD_GETPOP_TEMPLATE_BLOCKGROUP_OVERVIEW,
			);
			foreach ($pageblockgroups as $page => $blockgroup) {
				
				// Also Default
				$ret[$page]['blockgroups']['default'] = $blockgroup;
			}
		}

		return $ret;
	}

	function get_page_blocks($hierarchy, $include_common = true) {

		$ret = array();

		// Page or Home
		if ($hierarchy == GD_SETTINGS_HIERARCHY_PAGE || $hierarchy == GD_SETTINGS_HIERARCHY_HOME) {

			$pageblocks = array(
				GETPOP_PROCESSORS_PAGE_CONTACTABOUTUS => GD_TEMPLATE_BLOCK_CONTACTABOUTUS,
				GETPOP_PROCESSORS_PAGE_WHATISIT => GD_TEMPLATE_BLOCK_WHATISIT,
				// GETPOP_PROCESSORS_PAGE_DISCOVER => GD_TEMPLATE_BLOCK_DISCOVER,
				GETPOP_PROCESSORS_PAGE_FRAMEWORK => GD_TEMPLATE_BLOCK_FRAMEWORK,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONARCHITECTURE => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION_SECTIONARCHITECTURE,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONCONTROLLER => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION_SECTIONCONTROLLER,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONMODEL => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION_SECTIONMODEL,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONVIEW => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION_SECTIONVIEW,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_SECTIONAPPLICATIONLOGIC => GD_TEMPLATE_BLOCK_MENU_BODY_DOCUMENTATION_SECTIONAPPLICATIONLOGIC,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_OVERVIEW => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_POPENGINE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_PLUGINSHIERARCHY => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULARITY => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_MODULEHIERARCHY => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_PROPERTIES => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSONSTRUCTURE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_APPLICATIONSTATE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_USABILITY => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_BACKGROUNDLOADING => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_LAZYLOADING => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CACHE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CHECKPOINTS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_CRAWLABLE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_IOHANDLER => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATALOADING => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DATAPOSTING => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FORMS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FILTERS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_FRONTENDOVERVIEW => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSFUNCTIONS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_INITIALIZINGJS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSOBJECTSTATE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				// GETPOP_PROCESSORS_PAGE_DOCUMENTATION_JSLIFECYCLE => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DYNAMICTEMPLATES => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_DOMINTERACTION => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_REPLICATION => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_BOOTSTRAP => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_USERROLES => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				GETPOP_PROCESSORS_PAGE_DOCUMENTATION_EVENTS => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
				// GETPOP_PROCESSORS_PAGE_DOCUMENTATION_COMINGSOON => GD_TEMPLATE_BLOCK_SINGLEABOUT_CONTENT,
			);
			foreach ($pageblocks as $page => $block) {
				
				// Also Default
				$ret[$page]['blocks']['default'] = $block;
			}
		}

		return $ret;
	}
}

/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GetPoP_Processors_Template_SettingsProcessor();
