############################################################
# Test that, upon disabling the Schema Configuration module,
# the custom endpoint still works, just without the corresponding
# SchemaConfig rules
############################################################
{
  dummyCustomPosts: customPosts(
    pagination: { limit: 3 }
    sort: { by: ID, order: ASC }
    filter:{
      customPostTypes: "dummy-cpt"
    }
  ) {
    __typename
    ...on GenericCustomPost {
      id
      title
      customPostType
    }
  }
}