<?php

declare(strict_types=1);

namespace PoPCMSSchema\Pages\TypeResolvers\InputObjectType;

use PoPCMSSchema\CustomPosts\TypeResolvers\InputObjectType\WithParentCustomPostsFilterInputObjectTypeResolverInterface;

interface PagesFilterInputObjectTypeResolverInterface extends WithParentCustomPostsFilterInputObjectTypeResolverInterface
{
}
