<?php

declare(strict_types=1);

namespace PoPSchema\UserStateAccessControl\RelationalTypeResolverDecorators;

use PoPSchema\UserStateAccessControl\RelationalTypeResolverDecorators\ValidateUserLoggedInForDirectivesTypeResolverDecoratorTrait;

class ValidateUserLoggedInForDirectivesPublicSchemaTypeResolverDecorator extends AbstractUserStateConfigurableAccessControlForDirectivesInPublicSchemaTypeResolverDecorator
{
    use ValidateUserLoggedInForDirectivesTypeResolverDecoratorTrait;
}
