############################################################
# The content of this file doesn't matter!
# The actual GraphQL query comes from the persisted query.
############################################################
{
  id
}