<?php

declare(strict_types=1);

namespace GraphQLAPI\GraphQLAPI;

class Environment
{
    public final const MODULE_URL_BASE = 'MODULE_URL_BASE';
    public final const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public final const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public final const NO_ITEMS_SELECTED_LABEL = 'NO_ITEMS_SELECTED_LABEL';
    public final const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public final const ENDPOINT_SLUG_BASE = 'ENDPOINT_SLUG_BASE';
    public final const PERSISTED_QUERY_SLUG_BASE = 'PERSISTED_QUERY_SLUG_BASE';
    public final const EDITING_ACCESS_SCHEME = 'EDITING_ACCESS_SCHEME';
    public final const ENABLE_LOW_LEVEL_PERSISTED_QUERY_EDITING = 'ENABLE_LOW_LEVEL_PERSISTED_QUERY_EDITING';
    public final const ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME = 'ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME';
    public final const DISPLAY_PRO_PLUGIN_INFORMATION_IN_MAIN_PLUGIN = 'DISPLAY_PRO_PLUGIN_INFORMATION_IN_MAIN_PLUGIN';
    public final const PRO_PLUGIN_WEBSITE_URL = 'PRO_PLUGIN_WEBSITE_URL';
    public final const USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER = 'USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER';
}
