<?php

declare(strict_types=1);

namespace GatoGraphQL\GatoGraphQL;

class Environment
{
    public final const PLUGIN_NAMESPACE_FOR_DB = 'PLUGIN_NAMESPACE_FOR_DB';
    public final const MODULE_URL_BASE = 'MODULE_URL_BASE';
    public final const ADD_EXCERPT_AS_DESCRIPTION = 'ADD_EXCERPT_AS_DESCRIPTION';
    public final const GROUP_FIELDS_UNDER_TYPE_FOR_PRINT = 'GROUP_FIELDS_UNDER_TYPE_FOR_PRINT';
    public final const NO_ITEMS_SELECTED_LABEL = 'NO_ITEMS_SELECTED_LABEL';
    public final const SETTINGS_VALUE_LABEL = 'SETTINGS_VALUE_LABEL';
    public final const EDITING_ACCESS_SCHEME = 'EDITING_ACCESS_SCHEME';
    public final const ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME = 'ENABLE_SETTING_CLIENT_IP_ADDRESS_SERVER_PROPERTY_NAME';
    public final const GATOGRAPHQL_WEBSITE_URL = 'GATOGRAPHQL_WEBSITE_URL';
    public final const GATOGRAPHQL_REQUEST_EXTENSION_PAGE_URL = 'GATOGRAPHQL_REQUEST_EXTENSION_PAGE_URL';
    public final const GATOGRAPHQL_SHOP_MYORDERS_URL = 'GATOGRAPHQL_SHOP_MYORDERS_URL';
    public final const GATOGRAPHQL_BUNDLES_PAGE_URL = 'GATOGRAPHQL_BUNDLES_PAGE_URL';
    public final const GATOGRAPHQL_EXTENSIONS_PAGE_URL = 'GATOGRAPHQL_EXTENSIONS_PAGE_URL';
    public final const GATOGRAPHQL_EXTENSIONS_REFERENCE_PAGE_URL = 'GATOGRAPHQL_EXTENSIONS_REFERENCE_PAGE_URL';
    public final const USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER = 'USE_SCHEMA_CONFIGURATION_IN_INTERNAL_GRAPHQL_SERVER';
    public final const ENABLE_SCHEMA_TUTORIAL_PAGE = 'ENABLE_SCHEMA_TUTORIAL_PAGE';
    public final const ENABLE_LOGS = 'ENABLE_LOGS';
    public final const INSTALL_PLUGIN_SETUP_DATA = 'INSTALL_PLUGIN_SETUP_DATA';
    public final const SHOW_BUNDLES_CONTAINING_REFERENCED_EXTENSIONS_ON_TUTORIAL = 'SHOW_BUNDLES_CONTAINING_REFERENCED_EXTENSIONS_ON_TUTORIAL';
    public final const IS_SCHEMA_CONFIGURATION_ENABLED_BY_DEFAULT = 'IS_SCHEMA_CONFIGURATION_ENABLED_BY_DEFAULT';
    public final const DISPLAY_ENABLE_LOGS_SETTINGS_OPTION = 'DISPLAY_ENABLE_LOGS_SETTINGS_OPTION';
}
