<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERNAME', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-username'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_EMAIL', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-email'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_CURRENTPASSWORD', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-currentpassword'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORD', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-password'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORD', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-newpassword'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORDREPEAT', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-passwordrepeat'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORDREPEAT', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-newpasswordrepeat'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_FIRSTNAME', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-firstname'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERURL', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-userurl'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_DESCRIPTION', PoP_ServerUtils::get_template_definition('formcomponentgroup-cuu-description'));

// My Preferences
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_NEWPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-general-newpost'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_SPECIALPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-general-specialpost'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_CREATEDPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-createdpost'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_RECOMMENDEDPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-recommendedpost'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_FOLLOWEDUSER', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-followeduser'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_SUBSCRIBEDTOTOPIC', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-subscribedtotopic'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_ADDEDCOMMENT', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-addedcomment'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_UPDOWNVOTEDPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-network-updownvotedpost'));
// define ('GD_URE_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_JOINSCOMMUNITY', PoP_ServerUtils::get_template_definition('ure-formcomponentgroup-emailnotifications-network-joinscommunity'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_CREATEDPOST', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-subscribedtopic-createdpost'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_ADDEDCOMMENT', PoP_ServerUtils::get_template_definition('formcomponentgroup-emailnotifications-subscribedtopic-addedcomment'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYCONTENT', PoP_ServerUtils::get_template_definition('formcomponentgroup-emaildigests-dailynewcontent'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_BIWEEKLYUPCOMINGEVENTS', PoP_ServerUtils::get_template_definition('formcomponentgroup-emaildigests-biweeklyupcomingevents'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYNETWORKACTIVITY', PoP_ServerUtils::get_template_definition('formcomponentgroup-emaildigests-dailynetworkactivity'));
define ('GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYSUBSCRIBEDTOPICSACTIVITY', PoP_ServerUtils::get_template_definition('formcomponentgroup-emaildigests-dailysubscribedtopicsactivity'));

class GD_Template_Processor_UserFormGroups extends GD_Template_Processor_FormComponentGroupsBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERNAME,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_EMAIL,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_CURRENTPASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORDREPEAT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORDREPEAT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_FIRSTNAME,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERURL,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_DESCRIPTION,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_NEWPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_SPECIALPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_CREATEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_RECOMMENDEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_FOLLOWEDUSER,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_SUBSCRIBEDTOTOPIC,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_ADDEDCOMMENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_UPDOWNVOTEDPOST,
			// GD_URE_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_JOINSCOMMUNITY,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_CREATEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_ADDEDCOMMENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYCONTENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_BIWEEKLYUPCOMINGEVENTS,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYNETWORKACTIVITY,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYSUBSCRIBEDTOPICSACTIVITY,
		);
	}

	function get_label($template_id, $atts) {

		$ret = parent::get_label($template_id, $atts);

		switch ($template_id) {

			case GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERURL:

				$ret = '<i class="fa fa-fw fa-home"></i>'.$ret;
				break;
		}
		
		return $ret;
	}

	function get_component($template_id) {

		$components = array(
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERNAME => GD_TEMPLATE_FORMCOMPONENT_CUU_USERNAME,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_EMAIL => GD_TEMPLATE_FORMCOMPONENT_CUU_EMAIL,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_CURRENTPASSWORD => GD_TEMPLATE_FORMCOMPONENT_CUU_CURRENTPASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORD => GD_TEMPLATE_FORMCOMPONENT_CUU_PASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORD => GD_TEMPLATE_FORMCOMPONENT_CUU_NEWPASSWORD,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_PASSWORDREPEAT => GD_TEMPLATE_FORMCOMPONENT_CUU_PASSWORDREPEAT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_NEWPASSWORDREPEAT => GD_TEMPLATE_FORMCOMPONENT_CUU_NEWPASSWORDREPEAT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_FIRSTNAME => GD_TEMPLATE_FORMCOMPONENT_CUU_FIRSTNAME,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_USERURL => GD_TEMPLATE_FORMCOMPONENT_CUU_USERURL,
			GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_DESCRIPTION => GD_TEMPLATE_FORMCOMPONENT_CUU_DESCRIPTION,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_NEWPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_GENERAL_NEWPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_SPECIALPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_GENERAL_SPECIALPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_CREATEDPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_CREATEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_RECOMMENDEDPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_RECOMMENDEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_FOLLOWEDUSER => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_FOLLOWEDUSER,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_SUBSCRIBEDTOTOPIC => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_SUBSCRIBEDTOTOPIC,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_ADDEDCOMMENT => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_ADDEDCOMMENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_UPDOWNVOTEDPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_UPDOWNVOTEDPOST,
			// GD_URE_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_JOINSCOMMUNITY => GD_URE_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_NETWORK_JOINSCOMMUNITY,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_CREATEDPOST => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_CREATEDPOST,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_ADDEDCOMMENT => GD_TEMPLATE_FORMCOMPONENT_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_ADDEDCOMMENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYCONTENT => GD_TEMPLATE_FORMCOMPONENT_EMAILDIGESTS_DAILYCONTENT,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_BIWEEKLYUPCOMINGEVENTS => GD_TEMPLATE_FORMCOMPONENT_EMAILDIGESTS_BIWEEKLYUPCOMINGEVENTS,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYNETWORKACTIVITY => GD_TEMPLATE_FORMCOMPONENT_EMAILDIGESTS_DAILYNETWORKACTIVITY,
			GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYSUBSCRIBEDTOPICSACTIVITY => GD_TEMPLATE_FORMCOMPONENT_EMAILDIGESTS_DAILYSUBSCRIBEDTOPICSACTIVITY,
		);

		if ($component = $components[$template_id]) {

			return $component;
		}
		
		return parent::get_component($template_id);
	}

	function get_info($template_id, $atts) {
	
		switch ($template_id) {
		
			case GD_TEMPLATE_FORMCOMPONENTGROUP_CUU_EMAIL:
			
				return __('Please be careful to fill-in the email properly! It will not only appear in the profile page, but also be used by our system to send you notifications.', 'pop-coreprocessors');
		}
		
		return parent::get_info($template_id, $atts);
	}

	function use_component_configuration($template_id) {

		switch ($template_id) {

			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_NEWPOST:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_GENERAL_SPECIALPOST:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_CREATEDPOST:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_RECOMMENDEDPOST:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_FOLLOWEDUSER:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_SUBSCRIBEDTOTOPIC:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_ADDEDCOMMENT:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_UPDOWNVOTEDPOST:
			// case GD_URE_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_NETWORK_JOINSCOMMUNITY:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_CREATEDPOST:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILNOTIFICATIONS_SUBSCRIBEDTOPIC_ADDEDCOMMENT:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYCONTENT:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_BIWEEKLYUPCOMINGEVENTS:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYNETWORKACTIVITY:
			case GD_TEMPLATE_FORMCOMPONENTGROUP_EMAILDIGESTS_DAILYSUBSCRIBEDTOPICSACTIVITY:
				
				return false;
		}

		return parent::use_component_configuration($template_id);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Template_Processor_UserFormGroups();