{
  customPosts(
    pagination: {
      limit: 3
    }
  ) {
    __typename
    isObjectTypeWithNamespacing: _isObjectType(type: "PoPCMSSchema_Posts_Post")
    isObjectTypeWithoutNamespacing: _isObjectType(type: "Post")
    isObjectTypeWithWrongNamespacing: _isObjectType(type: "NonExisting_PoPCMSSchema_Posts_Post")
    implementsWithNamespacing: _implements(interface: "PoPCMSSchema_CustomPosts_IsCustomPost")
    implementsWithoutNamespacing: _implements(interface: "IsCustomPost")
    implementsWithWrongNamespacing: _implements(interface: "NonExisting_PoPCMSSchema_CustomPosts_IsCustomPost")
    isInUnionTypeWithNamespacing: _isInUnionType(type: "PoPCMSSchema_CustomPosts_CustomPostUnion")
    isInUnionTypeWithoutNamespacing: _isInUnionType(type: "CustomPostUnion")
    isInUnionTypeWithWrongNamespacing: _isInUnionType(type: "NonExisting_PoPCMSSchema_CustomPosts_CustomPostUnion")
  }

  users(
    pagination: {
      limit: 3
    }
  ) {
    __typename
    isObjectTypeWithNamespacing: _isObjectType(type: "PoPCMSSchema_Posts_Post")
    isObjectTypeWithoutNamespacing: _isObjectType(type: "Post")
    isObjectTypeWithWrongNamespacing: _isObjectType(type: "NonExisting_PoPCMSSchema_Posts_Post")
    implementsWithNamespacing: _implements(interface: "PoPCMSSchema_CustomPosts_IsCustomPost")
    implementsWithoutNamespacing: _implements(interface: "IsCustomPost")
    implementsWithWrongNamespacing: _implements(interface: "NonExisting_PoPCMSSchema_CustomPosts_IsCustomPost")
    isInUnionTypeWithNamespacing: _isInUnionType(type: "PoPCMSSchema_CustomPosts_CustomPostUnion")
    isInUnionTypeWithoutNamespacing: _isInUnionType(type: "CustomPostUnion")
    isInUnionTypeWithWrongNamespacing: _isInUnionType(type: "NonExisting_PoPCMSSchema_CustomPosts_CustomPostUnion")
  }
}