<?php
/**---------------------------------------------------------------------------------------------------------------
 *
 * Template Manager (Handlebars)
 *
 * ---------------------------------------------------------------------------------------------------------------*/

define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FAVICON', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-favicon'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_ORIGINALFEATUREDIMAGE', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-originalfeaturedimage'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-featuredimage'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE_VOLUNTEER', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-featuredimage-volunteer'));

define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_XSMALL', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-xsmall'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedsmall'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedmedium'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedfeed'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_EDIT', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedsmall-edit'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_VOLUNTEER', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedsmall-volunteer'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedmedium-volunteer'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED_VOLUNTEER', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-croppedfeed-volunteer'));

define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-linkselfcroppedfeed'));
define ('GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER', PoP_ServerUtils::get_template_definition('layoutwrapper-postthumb-linkselfcroppedfeed-volunteer'));

class GD_Custom_Template_Processor_PostThumbLayoutWrappers extends GD_Template_Processor_ConditionWrapperBase {

	function get_templates_to_process() {
	
		return array(
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FAVICON,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_ORIGINALFEATUREDIMAGE,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_XSMALL,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_EDIT,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER,

		);
	}

	function get_layouts($template_id) {

		$ret = parent::get_layouts($template_id);

		$layouts = array(
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FAVICON => GD_TEMPLATE_LAYOUT_POSTTHUMB_FAVICON,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_ORIGINALFEATUREDIMAGE => GD_TEMPLATE_LAYOUT_POSTTHUMB_ORIGINALFEATUREDIMAGE,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE => GD_TEMPLATE_LAYOUT_POSTTHUMB_FEATUREDIMAGE,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE_VOLUNTEER => GD_TEMPLATE_LAYOUT_POSTTHUMB_FEATUREDIMAGE_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_XSMALL => GD_TEMPLATE_LAYOUT_POSTTHUMB_XSMALL,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDSMALL,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDMEDIUM,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDFEED,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_EDIT => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDSMALL_EDIT,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_VOLUNTEER => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDSMALL_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED_VOLUNTEER => GD_TEMPLATE_LAYOUT_POSTTHUMB_CROPPEDFEED_VOLUNTEER,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED => GD_TEMPLATE_LAYOUT_POSTTHUMB_LINKSELFCROPPEDFEED,
			GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER => GD_TEMPLATE_LAYOUT_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER,
		);

		if ($layout = $layouts[$template_id]) {
			$ret[] = $layout;
		}

		return $ret;
	}

	function get_condition_field($template_id) {

		switch ($template_id) {
			
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FAVICON:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_ORIGINALFEATUREDIMAGE:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_FEATUREDIMAGE_VOLUNTEER:
			
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_XSMALL:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_EDIT:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_VOLUNTEER:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED_VOLUNTEER:

			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER:

				return 'has-thumb';
		}

		return parent::get_condition_field($template_id);
	}

	function init_atts($template_id, &$atts) {

		switch ($template_id) {

			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_XSMALL:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_EDIT:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDSMALL_VOLUNTEER:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDMEDIUM_VOLUNTEER:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_CROPPEDFEED_VOLUNTEER:

			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED:
			case GD_TEMPLATE_LAYOUTWRAPPER_POSTTHUMB_LINKSELFCROPPEDFEED_VOLUNTEER:

				$this->append_att($template_id, $atts, 'class', 'wrapper-featuredimage');
				break;
		}

		return parent::init_atts($template_id, $atts);
	}
}


/**---------------------------------------------------------------------------------------------------------------
 * Initialization
 * ---------------------------------------------------------------------------------------------------------------*/
new GD_Custom_Template_Processor_PostThumbLayoutWrappers();