############################################################
# The content of this query doesn't matter!
# The GraphQL query will be taken from the "User account"
# persisted query
############################################################
{}