<?php

// Routes
//--------------------------------------------------------
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS00')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS00', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS01')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS01', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS02')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS02', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS03')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS03', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS04')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS04', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS05')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS05', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS06')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS06', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS07')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS07', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS08')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS08', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS09')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS09', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS10')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS10', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS11')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS11', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS12')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS12', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS13')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS13', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS14')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS14', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS15')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS15', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS16')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS16', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS17')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS17', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS18')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS18', false);
}
if (!defined('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS19')) {
	define('POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS19', false);
}

\PoP\Root\App::addFilter(
    \PoP\RoutingWP\HookNames::ROUTES,
    function($routes) {
    	return array_merge(
    		$routes,
    		array_filter([
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS00,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS01,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS02,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS03,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS04,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS05,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS06,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS07,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS08,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS09,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS10,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS11,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS12,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS13,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS14,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS15,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS16,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS17,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS18,
				POP_CATEGORYPOSTS_ROUTE_CATEGORYPOSTS19,
    		])
    	);
    }
);
