<?php

declare(strict_types=1);

namespace PHPUnitForGatoGraphQL\GatoGraphQL\Unit\Faker;

use GraphQLByPoP\GraphQLServer\Unit\EnabledFixtureQueryExecutionGraphQLServerTestCaseTrait;

class EnabledCommentableCustomPostWPFakerFixtureQueryExecutionGraphQLServerTest extends AbstractCommentableCustomPostWPFakerFixtureQueryExecutionGraphQLServerTestCase
{
    use EnabledFixtureQueryExecutionGraphQLServerTestCaseTrait;
}
